# -*- coding: utf-8 -*-
"""词条的主题归类与中文释义。

主题用官方词表第 4 页的 Themen 清单，不另起一套——考试就是按这十个
主题范围出题的，归类跟着它走，复习范围才和考纲对得上。

但字母序词表里有大量词不属于任何主题（介词、代词、情态动词、以及
「做 / 说 / 好 / 快」这类通用词），官方 Themen 里没有它们的位置。
这些另立两个桶，在界面上也标明不是官方主题：
    funktion  语法功能词——考试不单独考，但每句话都要用
    basis     通用词——跨主题的高频动词与形容词

释义只给例句里的那个义项。A1 阶段一词多义会分散注意力，
需要时在例句里自然遇到就够了。可分动词标「可分」，
支配特定格或介词的动词把要求写进释义，这两样错了句子就废了。
"""

# 官方主题（顺序照词表第 4 页）
THEMEN = [
    ('person',   '个人信息',   '姓名 · 地址 · 年龄 · 家庭 · 外貌 · 日常作息'),
    ('wohnen',   '居住',       '住房 · 房间 · 家具 · 家电 · 房租 · 搬家'),
    ('umwelt',   '自然环境',   '植物 · 动物 · 气候与天气'),
    ('reisen',   '出行交通',   '公共与私人交通 · 旅行 · 住宿 · 行李'),
    ('essen',    '饮食',       '食品 · 三餐 · 菜肴 · 饮料 · 餐馆咖啡馆'),
    ('kauf',     '购物日用',   '商店 · 价格与付款 · 食品 · 服装'),
    ('dienst',   '公共服务',   '邮局 · 通信 · 银行 · 警察'),
    ('lernen',   '教育学习',   '托幼 · 学校 · 语言学习'),
    ('arbeit',   '工作职业',   '工作岗位 · 休假'),
    ('freizeit', '休闲娱乐',   '兴趣 · 运动 · 广播电视 · 网络 · 读物报刊'),
]

# 官方 Themen 之外的两个桶
EXTRA = [
    ('funktion', '语法功能词', '冠词 · 代词 · 介词 · 连词 · 情态动词'),
    ('basis',    '通用词',     '不专属某个主题的高频动词与形容词'),
]

# 词条 → (主题, 中文释义)
WORDS = {
    'ab': ('funktion', '从…起（三格介词，多指时间）'),
    'aber': ('funktion', '但是'),
    'abfahren': ('reisen', '出发、开走（可分）'),
    'Abfahrt': ('reisen', '发车、出发'),
    'abgeben': ('basis', '交出、上交（可分）'),
    'abholen': ('basis', '去接、去取（可分）'),
    'Absender': ('dienst', '寄件人'),
    'Achtung': ('basis', '注意、当心'),
    'Adresse': ('person', '地址'),
    'all-': ('funktion', '全部的、所有的'),
    'allein': ('basis', '独自、单独'),
    'also': ('funktion', '那么、也就是说'),
    'alt': ('person', '年纪…的；旧的'),
    'Alter': ('person', '年龄'),
    'an': ('funktion', '靠着、在…边上（三四格介词）'),
    'anbieten': ('basis', '提供、招待（可分）'),
    'Angebot': ('kauf', '特价、优惠'),
    'ander-': ('funktion', '别的、另一个'),
    'anfangen': ('basis', '开始（可分）'),
    'Anfang': ('basis', '开头、起点'),
    'anklicken': ('freizeit', '点击（可分）'),
    'ankommen': ('reisen', '到达（可分）'),
    'Ankunft': ('reisen', '到达'),
    'ankreuzen': ('lernen', '打勾、画叉选择（可分，考试指令语）'),
    'anmachen': ('wohnen', '打开（灯、电器，可分）'),
    '(sich) anmelden': ('dienst', '报名、登记'),
    'Anmeldung': ('dienst', '报名；登记处'),
    'Anrede': ('lernen', '称呼语（书信开头的「Liebe…」）'),
    'anrufen': ('dienst', '打电话给（四格，可分）'),
    'Anruf': ('dienst', '来电'),
    'Anrufbeantworter': ('dienst', '电话答录机'),
    'Ansage': ('lernen', '广播通知（听力题的播报）'),
    'Anschluss': ('reisen', '接续班次、转乘'),
    'an sein': ('wohnen', '开着（灯、电器）'),
    'antworten': ('basis', '回答（三格：某人）'),
    'Antwort': ('basis', '回答'),
    'Anzeige': ('kauf', '广告、启事'),
    '(sich) anziehen': ('kauf', '穿上（可分）'),
    'Apartment': ('wohnen', '公寓'),
    'Apfel': ('essen', '苹果'),
    'Appetit': ('essen', '食欲（Guten Appetit! 用餐愉快）'),
    'arbeiten': ('arbeit', '工作'),
    'Arbeit': ('arbeit', '工作、活儿'),
    'arbeitslos': ('arbeit', '失业的'),
    'Arbeitsplatz': ('arbeit', '工作岗位、工位'),
    'Arm': ('person', '手臂'),
    'Arzt': ('person', '医生'),
    'auch': ('funktion', '也'),
    'auf': ('funktion', '在…上面（三四格介词）'),
    'Aufgabe': ('lernen', '任务、习题'),
    'aufhören': ('basis', '停止、结束（可分）'),
    'auf sein': ('wohnen', '开着（门、店）'),
    'aufstehen': ('basis', '起床、站起来（可分）'),
    'Aufzug': ('wohnen', '电梯'),
    'Auge': ('person', '眼睛'),
    'aus': ('funktion', '来自、从…出来（三格介词）'),
    'Ausflug': ('freizeit', '郊游、短途出游'),
    'ausfüllen': ('dienst', '填写（表格，可分）'),
    'Ausgang': ('reisen', '出口'),
    'Auskunft': ('dienst', '问讯、咨询处'),
    'Ausland': ('reisen', '国外'),
    'Ausländer': ('person', '外国人'),
    'ausländisch': ('person', '外国的'),
    'ausmachen': ('wohnen', '关掉（灯、电器，可分）'),
    'Aussage': ('lernen', '陈述、说法（判断对错题用）'),
    'aussehen': ('person', '看上去（可分）'),
    'aus sein': ('wohnen', '关着（灯、电器）'),
    'aussteigen': ('reisen', '下车（可分）'),
    'Ausweis': ('person', '证件'),
    '(sich) ausziehen': ('kauf', '脱下（可分）'),
    'Auto': ('reisen', '汽车'),
    'Autobahn': ('reisen', '高速公路'),
    'Automat': ('reisen', '自动售票机、自动售货机'),
    'automatisch': ('basis', '自动的'),
    'Baby': ('person', '婴儿'),
    'Bäckerei': ('kauf', '面包店'),
    'Bad': ('wohnen', '浴室'),
    'baden': ('person', '洗澡、泡澡'),
    'Bahn': ('reisen', '铁路、火车'),
    'Bahnhof': ('reisen', '火车站'),
    'Bahnsteig': ('reisen', '站台'),
    'bald': ('basis', '不久、快了'),
    'Balkon': ('wohnen', '阳台'),
    'Banane': ('essen', '香蕉'),
    'Bank': ('dienst', '银行'),
    'bar': ('kauf', '现金（bar zahlen 付现金）'),
    'Bauch': ('person', '肚子'),
    'Baum': ('umwelt', '树'),
    'Beamte': ('arbeit', '公职人员、窗口办事员'),
    'bedeuten': ('lernen', '意思是、意味着'),
    'beginnen': ('basis', '开始'),
    'bei': ('funktion', '在…附近、在…那里（三格介词）'),
    'beide': ('funktion', '两个都'),
    'Bein': ('person', '腿'),
    'Beispiel': ('lernen', '例子'),
    'zum Beispiel/z. B.': ('lernen', '例如'),
    'bekannt': ('basis', '有名的、为人所知的'),
    'Bekannte': ('person', '熟人（形容词变名词，随冠词变格）'),
    'bekommen': ('basis', '得到、收到'),
    'benutzen': ('basis', '使用'),
    'Beruf': ('arbeit', '职业'),
    'besetzt': ('dienst', '占线的；被占用的'),
    'besichtigen': ('freizeit', '参观'),
    'besser': ('basis', '更好（gut 的比较级）'),
    'best-': ('basis', '最好的（am besten 最好…）'),
    'bestellen': ('essen', '点菜；订购'),
    'besuchen': ('basis', '拜访、探望'),
    'Bett': ('wohnen', '床'),
    'bezahlen': ('kauf', '付款'),
    'Bier': ('essen', '啤酒'),
    'Bild': ('basis', '照片、图画'),
    'billig': ('kauf', '便宜的'),
    'Birne': ('essen', '梨'),
    'bis': ('funktion', '直到（四格介词）'),
    'bisschen': ('funktion', '一点儿（ein bisschen）'),
    'bitte': ('basis', '请；不客气'),
    'Bitte': ('basis', '请求'),
    'bitten': ('basis', '请求（um + 四格：某事）'),
    'bitter': ('essen', '苦的'),
    'bleiben': ('basis', '留下、停留'),
    'Bleistift': ('lernen', '铅笔'),
    'Blick': ('reisen', '视野、景观'),
    'Blume': ('umwelt', '花'),
    'Bogen': ('lernen', '纸张（Antwortbogen 答题纸）'),
    'böse': ('basis', '生气的（auf + 四格：对某人）'),
    'brauchen': ('basis', '需要'),
    'breit': ('basis', '宽的'),
    'Brief': ('dienst', '信'),
    'Briefmarke': ('dienst', '邮票'),
    'bringen': ('basis', '带来、送到'),
    'Brot': ('essen', '面包'),
    'Brötchen': ('essen', '小圆面包'),
    'Bruder': ('person', '兄弟'),
    'Buch': ('freizeit', '书'),
    'Buchstabe': ('lernen', '字母'),
    'buchstabieren': ('lernen', '拼读字母（口试第一部分的考点）'),
    'Bus': ('reisen', '公共汽车'),
    'Butter': ('essen', '黄油'),
    'Café': ('essen', '咖啡馆'),
    'CD': ('freizeit', '光盘'),
    'Chef': ('arbeit', '老板、主管'),
    'circa/ca.': ('basis', '大约'),
    'Computer': ('freizeit', '电脑'),
    'da': ('funktion', '那儿；在场'),
    'Dame': ('person', '女士'),
    'daneben': ('basis', '在…旁边'),
    'danken': ('basis', '感谢（三格：某人 / für + 四格：某事）'),
    'Dank': ('basis', '感谢（Vielen Dank! 多谢）'),
    'danke': ('basis', '谢谢'),
    'dann': ('funktion', '然后、接着'),
    'Datum': ('basis', '日期'),
    'dauern': ('basis', '持续、要花（时间）'),
    'dein-': ('funktion', '你的（物主冠词）'),
    'denn': ('funktion', '因为（并列连词，不改变语序）'),
    'der, die, das': ('funktion', '定冠词；也可作指示代词'),
    'dich': ('funktion', '你（du 的四格）'),
    'dies-': ('funktion', '这个'),
    'dir': ('funktion', '你（du 的三格）'),
    'Disco': ('freizeit', '迪厅'),
    'Doktor': ('person', '医生（口语）；博士'),
    'Doppelzimmer': ('reisen', '双人间'),
    'Dorf': ('wohnen', '村庄'),
    'dort, -her, -hin': ('funktion', '那里；dorther 从那里；dorthin 到那里'),
    'draußen': ('basis', '外面'),
    'drucken': ('lernen', '打印'),
    'Drucker': ('arbeit', '打印机'),
    'drücken': ('basis', '按、压'),
    'durch': ('funktion', '穿过（四格介词）'),
    'Durchsage': ('reisen', '广播通知'),
    'dürfen': ('funktion', '可以、被允许（情态动词）'),
    'Durst': ('essen', '口渴（Durst haben 渴）'),
    '(sich) duschen': ('person', '洗淋浴'),
    'Dusche': ('wohnen', '淋浴'),
    'Ecke': ('reisen', '拐角'),
    'Ehefrau': ('person', '妻子'),
    'Ehemann': ('person', '丈夫'),
    'Ei': ('essen', '鸡蛋'),
    'eilig': ('basis', '急的（es eilig haben 赶时间）'),
    'ein-': ('funktion', '不定冠词；eins 一个'),
    'einfach': ('basis', '简单的；（车票）单程的'),
    'Eingang': ('reisen', '入口'),
    'einkaufen': ('kauf', '采购、买东西（可分）'),
    'einladen': ('freizeit', '邀请（zu + 三格，可分）'),
    'Einladung': ('freizeit', '邀请'),
    'einmal': ('basis', '一次（noch einmal 再一次）'),
    'einsteigen': ('reisen', '上车（可分）'),
    'Eintritt': ('freizeit', '入场；门票（费）'),
    'Einzelzimmer': ('reisen', '单人间'),
    'Eltern': ('person', '父母（只用复数）'),
    'E-Mail': ('dienst', '电子邮件'),
    'Empfänger': ('dienst', '收件人'),
    'empfehlen': ('essen', '推荐'),
    'enden': ('basis', '结束、到头'),
    'Ende': ('basis', '结尾、尽头'),
    'entschuldigen': ('basis', '原谅（Entschuldigen Sie 对不起）'),
    'Entschuldigung': ('basis', '对不起；打扰一下'),
    'er': ('funktion', '他'),
    'Ergebnis': ('lernen', '结果、成绩'),
    'erklären': ('lernen', '解释'),
    'erlauben': ('basis', '允许'),
    'Erwachsene': ('person', '成年人（形容词变名词）'),
    'erzählen': ('basis', '讲述'),
    'es': ('funktion', '它；也作无人称主语（Es regnet.）'),
    'essen': ('essen', '吃'),
    'Essen': ('essen', '饭菜、饮食'),
    'euer': ('funktion', '你们的（物主冠词）'),
    'fahren': ('reisen', '乘车去、驾驶'),
    'Fahrer': ('reisen', '司机'),
    'Fahrkarte': ('reisen', '车票'),
    'Fahrrad': ('reisen', '自行车'),
    'falsch': ('lernen', '错的'),
    'Familie': ('person', '家庭'),
    'Familienname': ('person', '姓'),
    'Familienstand': ('person', '婚姻状况（表格栏目）'),
    'Farbe': ('kauf', '颜色'),
    'Fax': ('dienst', '传真'),
    'Feier-': ('freizeit', '「庆祝」类前缀：Feierabend 下班、Feiertag 节日'),
    'feiern': ('freizeit', '庆祝、过（节日、生日）'),
    'fehlen': ('basis', '缺少；缺席'),
    'Fehler': ('lernen', '错误'),
    'fernsehen': ('freizeit', '看电视（可分）'),
    'fertig': ('basis', '做完的、准备好的'),
    'Feuer': ('basis', '火（Haben Sie Feuer? 借个火）'),
    'Fieber': ('person', '发烧'),
    'Film': ('freizeit', '电影'),
    'finden': ('basis', '找到；觉得（Das finde ich gut.）'),
    'Firma': ('arbeit', '公司'),
    'Fisch': ('essen', '鱼'),
    'Flasche': ('essen', '瓶'),
    'Fleisch': ('essen', '肉'),
    'fliegen': ('reisen', '飞、坐飞机'),
    'abfliegen': ('reisen', '起飞（可分）'),
    'Abflug': ('reisen', '起飞、离港'),
    'Flughafen': ('reisen', '机场'),
    'Flugzeug': ('reisen', '飞机'),
    'Formular': ('dienst', '表格'),
    'Foto': ('freizeit', '照片'),
    'fragen': ('basis', '问（四格：某人）'),
    'Frage': ('basis', '问题'),
    'Frau': ('person', '女士；妻子'),
    'frei': ('basis', '空着的；自由的'),
    'Freizeit': ('freizeit', '业余时间'),
    'fremd': ('basis', '陌生的、外地的'),
    '(sich) freuen': ('basis', '高兴（auf + 四格 期待 / über + 四格 因…而高兴）'),
    'Freund': ('person', '朋友；男友'),
    'früher': ('basis', '从前、以前'),
    'frühstücken': ('essen', '吃早饭'),
    'Frühstück': ('essen', '早饭'),
    'Führung': ('freizeit', '导览、讲解参观'),
    'für': ('funktion', '为了、给（四格介词）'),
    'Fuß': ('person', '脚'),
    'Fußball': ('freizeit', '足球'),
    'Garten': ('wohnen', '花园'),
    'Gast': ('freizeit', '客人'),
    'geben': ('basis', '给（三格 + 四格）；es gibt 有'),
    'geboren': ('person', '出生的（geboren sein / werden）'),
    'Geburtsjahr': ('person', '出生年份'),
    'Geburtsort': ('person', '出生地'),
    'Geburtstag': ('person', '生日'),
    'gefallen': ('basis', '中意、讨人喜欢（三格：谁喜欢）'),
    'gegen': ('funktion', '朝向、撞上；反对（四格介词）'),
    'gehen': ('basis', '走、去；行得通（Wie geht das?）'),
    'gehören': ('basis', '属于（三格）'),
    'Geld': ('kauf', '钱'),
    'Gemüse': ('essen', '蔬菜'),
    'Gepäck': ('reisen', '行李（不可数）'),
    'gerade': ('basis', '正好、刚刚'),
    'geradeaus': ('reisen', '一直往前'),
    'gern(e)': ('basis', '乐意、喜欢（放在动词后）'),
    'Geschäft': ('kauf', '商店'),
    'Geschenk': ('kauf', '礼物'),
    'Geschwister': ('person', '兄弟姐妹（只用复数）'),
    'Gespräch': ('basis', '谈话'),
    'gestern': ('basis', '昨天'),
    'gestorben': ('person', '已故的（sterben 的第二分词）'),
    'Getränk': ('essen', '饮料'),
    'Gewicht': ('person', '体重、重量'),
    'gewinnen': ('freizeit', '赢'),
    'Glas': ('essen', '玻璃杯；玻璃'),
    'glauben': ('basis', '相信、认为'),
    'gleich': ('basis', '一样的；马上'),
    'Gleis': ('reisen', '轨道、几号站台'),
    'Glück': ('basis', '运气、幸福（Viel Glück! 祝好运）'),
    'glücklich': ('basis', '幸福的'),
    'Glückwunsch': ('basis', '祝贺（Herzlichen Glückwunsch!）'),
    'Grad (Celsius)': ('umwelt', '度（摄氏）'),
    'gratulieren': ('basis', '祝贺（三格：某人）'),
    'grillen': ('essen', '烧烤'),
    'groß': ('basis', '大的；（人）个子高的'),
    'Größe': ('kauf', '尺码、大小'),
    'Großeltern': ('person', '祖父母（只用复数）'),
    'Großmutter': ('person', '祖母、外祖母'),
    'Großvater': ('person', '祖父、外祖父'),
    'Gruppe': ('lernen', '小组'),
    'Gruß': ('basis', '问候（Viele Grüße 书信结尾）'),
    'gültig': ('reisen', '有效的'),
    'günstig': ('kauf', '划算的、价格合适的'),
    'gut': ('basis', '好的'),
    'Haar': ('person', '头发'),
    'haben': ('funktion', '有；构成完成时的助动词'),
    'Hähnchen': ('essen', '烤鸡、童子鸡'),
    'Halbpension': ('reisen', '半膳（含早餐与一顿正餐）'),
    'Halle': ('basis', '大厅、展馆'),
    'hallo': ('basis', '你好（非正式）'),
    'halten': ('reisen', '停、停靠'),
    'Haltestelle': ('reisen', '公交站、电车站'),
    'Hand': ('person', '手'),
    'Handy': ('dienst', '手机'),
    'Haus': ('wohnen', '房子'),
    'Hausaufgabe': ('lernen', '家庭作业'),
    'Hausfrau': ('arbeit', '家庭主妇'),
    'Hausmann': ('arbeit', '家庭主夫'),
    'Heimat': ('person', '故乡'),
    'heiraten': ('person', '结婚（四格：和某人）'),
    'heißen': ('person', '名叫'),
    'helfen': ('basis', '帮助（三格：某人）'),
    'hell': ('wohnen', '明亮的'),
    'Herd': ('wohnen', '炉灶'),
    'Herr': ('person', '先生'),
    'herzlich': ('basis', '衷心的'),
    'heute': ('basis', '今天'),
    'hier': ('basis', '这里'),
    'Hilfe': ('basis', '帮助'),
    'hinten': ('basis', '在后面'),
    'Hobby': ('freizeit', '爱好'),
    'hoch': ('basis', '高的'),
    'Hochzeit': ('person', '婚礼'),
    'holen': ('basis', '去取来、去叫来'),
    'hören': ('basis', '听、听见'),
    'Hotel': ('reisen', '旅馆'),
    'Hund': ('umwelt', '狗'),
    'Hunger': ('essen', '饥饿（Hunger haben 饿）'),
    'ich': ('funktion', '我'),
    'ihr/ihm/ihn': ('funktion', 'ihr 她（三格）· ihm 他（三格）· ihn 他（四格）'),
    'immer': ('basis', '总是'),
    'in': ('funktion', '在…里面（三四格介词）'),
    'Information': ('dienst', '信息；问讯处'),
    'international': ('basis', '国际的'),
    'Internet': ('freizeit', '互联网'),
    'ja': ('funktion', '是的'),
    'Jacke': ('kauf', '外套'),
    'jed-': ('funktion', '每一个'),
    'jetzt': ('basis', '现在'),
    'Job': ('arbeit', '工作、活儿（口语）'),
    'Jugendliche': ('person', '青少年（形容词变名词）'),
    'jung': ('person', '年轻的'),
    'Junge': ('person', '男孩'),
    'Kaffee': ('essen', '咖啡'),
    'kaputt': ('basis', '坏了的'),
    'Karte': ('basis', '卡片、明信片；票'),
    '(Kredit)-Karte, -n': ('kauf', '（信用）卡'),
    'Kartoffel': ('essen', '土豆'),
    'Kasse': ('kauf', '收银台'),
    'kaufen': ('kauf', '买'),
    'kein': ('funktion', '一个也不、没有（否定冠词）'),
    'kennen': ('basis', '认识、熟悉'),
    'kennenlernen': ('person', '结识、认识（可分）'),
    'Kind': ('person', '孩子'),
    'Kindergarten': ('lernen', '幼儿园'),
    'Kino': ('freizeit', '电影院'),
    'Kiosk': ('kauf', '报刊亭、小卖亭'),
    'klar': ('basis', '清楚的；当然（Klar!）'),
    'Klasse': ('lernen', '班级'),
    'Kleidung': ('kauf', '衣服（总称，不可数）'),
    'klein': ('basis', '小的'),
    'kochen': ('essen', '做饭、煮'),
    'Koffer': ('reisen', '行李箱'),
    'Kollege': ('arbeit', '同事'),
    'kommen': ('basis', '来'),
    'können': ('funktion', '能、会（情态动词）'),
    'Konto': ('dienst', '账户'),
    'Kopf': ('person', '头'),
    'kosten': ('kauf', '价钱为、值'),
    'krank': ('person', '生病的'),
    'kriegen': ('basis', '得到（口语，同 bekommen）'),
    'Küche': ('wohnen', '厨房'),
    'Kuchen': ('essen', '蛋糕'),
    'Kugelschreiber': ('lernen', '圆珠笔'),
    'Kühlschrank': ('wohnen', '冰箱'),
    'kulturell': ('freizeit', '文化方面的'),
    'sich kümmern': ('basis', '照料、操心（um + 四格）'),
    'Kunde': ('kauf', '顾客'),
    'Kurs': ('lernen', '课程班'),
    'kurz': ('basis', '短的'),
    'lachen': ('basis', '笑'),
    'Laden': ('kauf', '店铺'),
    'Land': ('person', '国家；乡下'),
    'lang': ('basis', '长的'),
    'lange': ('basis', '（时间）长久地'),
    'langsam': ('basis', '慢的'),
    'laufen': ('basis', '走路、跑'),
    'laut': ('basis', '大声的、吵的'),
    'leben': ('person', '生活、活着'),
    'Leben': ('person', '生活、一生'),
    'Lebensmittel': ('kauf', '食品'),
    'ledig': ('person', '未婚的（表格上的选项）'),
    'legen': ('wohnen', '（平着）放（四格 + 方位）'),
    'Lehrer': ('lernen', '老师'),
    'leicht': ('basis', '轻的；容易的'),
    'leider': ('basis', '可惜、很遗憾'),
    'leise': ('basis', '轻声的、安静的'),
    'lernen': ('lernen', '学习'),
    'lesen': ('freizeit', '读、阅读'),
    'letzt-': ('basis', '最后的、上一个的'),
    'Leute': ('person', '人们（只用复数）'),
    'Licht': ('wohnen', '灯、光'),
    'lieb-': ('basis', '亲爱的（Liebe Susanne 书信称呼）'),
    'lieben': ('person', '爱'),
    'lieber': ('basis', '更愿意（gern 的比较级）'),
    'Lieblings-': ('basis', '最喜欢的（前缀：Lieblingsfilm 最爱的电影）'),
    'Lied': ('freizeit', '歌曲'),
    'liegen': ('basis', '躺着；位于'),
    'links': ('reisen', '左边'),
    'Lkw': ('reisen', '卡车（Lastkraftwagen 的缩写）'),
    'Lokal': ('essen', '小饭馆、小酒馆'),
    'Lösung': ('lernen', '答案、解决办法'),
    'lustig': ('basis', '有趣的、爱说笑的'),
    'machen': ('basis', '做'),
    'Mädchen': ('person', '女孩（中性：das Mädchen）'),
    'man': ('funktion', '人们、泛指的「有人」（永远配单数）'),
    'Mann': ('person', '男人；丈夫'),
    'männlich': ('person', '男性的（表格上的选项）'),
    'Maschine': ('wohnen', '机器（Waschmaschine 洗衣机）'),
    'Meer': ('umwelt', '海'),
    'mehr': ('basis', '更多（viel 的比较级）'),
    'mein': ('funktion', '我的（物主冠词）'),
    'meist-': ('basis', '大多数的'),
    'Mensch': ('person', '人'),
    'mieten': ('wohnen', '租进、承租'),
    'Miete': ('wohnen', '房租'),
    'Milch': ('essen', '牛奶'),
    'mit': ('funktion', '和…一起；用（交通工具）（三格介词）'),
    'mitbringen': ('basis', '带来（可分）'),
    'mitkommen': ('basis', '一起来、一起去（可分）'),
    'mitmachen': ('freizeit', '参加、一起干（可分）'),
    'mitnehmen': ('basis', '带走、捎上（可分）'),
    'Mitte': ('basis', '中间'),
    'Möbel': ('wohnen', '家具（常用复数）'),
    'möchten': ('funktion', '想要（比 wollen 客气，当情态动词用）'),
    'mögen': ('funktion', '喜欢（情态动词）'),
    'möglich': ('basis', '可能的'),
    'Moment': ('basis', '片刻（Moment mal! 稍等）'),
    'morgen': ('basis', '明天'),
    'müde': ('basis', '累的、困的'),
    'Mund': ('person', '嘴'),
    'müssen': ('funktion', '必须（情态动词）'),
    'Mutter': ('person', '母亲'),
    'nach': ('funktion', '去（地名）；在…之后（三格介词）'),
    'nächst-': ('basis', '下一个的'),
    'Name': ('person', '名字'),
    'nehmen': ('basis', '拿、取；要（点单）；乘坐'),
    'nein': ('funktion', '不'),
    'neu': ('basis', '新的'),
    'nicht': ('funktion', '不（否定动词或句子）'),
    'nichts': ('funktion', '什么也没有'),
    'nie': ('basis', '从不'),
    'noch': ('basis', '还、仍然（noch ein 再来一个）'),
    'normal': ('basis', '正常的'),
    'Nummer': ('basis', '号码'),
    'nur': ('basis', '只、仅'),
    'oben': ('basis', '上面'),
    'Obst': ('essen', '水果（总称，不可数）'),
    'oder': ('funktion', '或者'),
    'öffnen': ('basis', '打开'),
    'geöffnet': ('kauf', '（店铺）营业中的'),
    'oft': ('basis', '经常'),
    'ohne': ('funktion', '没有、不带（四格介词）'),
    'Öl': ('essen', '油'),
    'Oma': ('person', '奶奶、外婆'),
    'Opa': ('person', '爷爷、外公'),
    'Ordnung': ('basis', '秩序（in Ordnung 没问题）'),
    'Ort': ('wohnen', '地点、小地方'),
    'Papier': ('lernen', '纸'),
    'Papiere': ('dienst', '证件（复数时是这个意思）'),
    'Partner': ('person', '伴侣、搭档'),
    'Partnerin': ('person', '女伴侣、女搭档'),
    'Party': ('freizeit', '聚会'),
    'Pass': ('reisen', '护照'),
    'Pause': ('lernen', '休息、课间'),
    'Plan': ('reisen', '计划；地图（Stadtplan 城市地图）'),
    'Platz': ('basis', '座位；广场；地方'),
    'Polizei': ('dienst', '警察（总称，用单数）'),
    'Pommes': ('essen', '薯条（Pommes frites，只用复数）'),
    'Post': ('dienst', '邮局；邮件'),
    'Postleitzahl': ('person', '邮政编码'),
    'Praktikum': ('arbeit', '实习'),
    'Praxis': ('person', '诊所'),
    'Preis': ('kauf', '价格'),
    'Problem': ('basis', '问题、难处'),
    'Prospekt': ('reisen', '宣传册'),
    'Prüfung': ('lernen', '考试'),
    'pünktlich': ('basis', '准时的'),
    'Rad fahren': ('freizeit', '骑自行车（分写，Rad 不与动词连写）'),
    'rauchen': ('basis', '抽烟'),
    'Raum': ('lernen', '房间、教室'),
    'Rechnung': ('kauf', '账单'),
    'rechts': ('reisen', '右边'),
    'regnen': ('umwelt', '下雨（只用 es 作主语）'),
    'Regen': ('umwelt', '雨'),
    'Reis': ('essen', '米、米饭'),
    'reisen': ('reisen', '旅行'),
    'Reise': ('reisen', '旅行'),
    'Reisebüro': ('reisen', '旅行社'),
    'Reiseführer': ('reisen', '旅游指南；导游'),
    'reparieren': ('basis', '修理'),
    'Reparatur': ('basis', '修理'),
    'Restaurant': ('essen', '餐厅'),
    'Rezeption': ('reisen', '（酒店）前台'),
    'richtig': ('lernen', '对的、正确的'),
    'riechen': ('essen', '闻起来；闻'),
    'ruhig': ('wohnen', '安静的'),
    'Saft': ('essen', '果汁'),
    'sagen': ('basis', '说'),
    'Salat': ('essen', '沙拉；生菜'),
    'Salz': ('essen', '盐'),
    'Satz': ('lernen', '句子'),
    'S-Bahn': ('reisen', '城铁'),
    'Schalter': ('dienst', '柜台、窗口'),
    'scheinen': ('umwelt', '（太阳）照耀；看起来'),
    'schicken': ('dienst', '寄、发送'),
    'Schild': ('reisen', '牌子、指示牌'),
    'Schinken': ('essen', '火腿'),
    'schlafen': ('basis', '睡觉'),
    'schlecht': ('basis', '差的；（人）不舒服（Mir ist schlecht.）'),
    'schließen': ('basis', '关上'),
    'geschlossen': ('kauf', '（店铺）关门的'),
    'Schluss': ('basis', '结束（Schluss machen 收尾）'),
    'Schlüssel': ('wohnen', '钥匙'),
    'schmecken': ('essen', '（食物）好吃、尝起来'),
    'schnell': ('basis', '快的'),
    'schon': ('basis', '已经'),
    'schön': ('basis', '美的、好的'),
    'Schrank': ('wohnen', '柜子'),
    'schreiben': ('basis', '写'),
    'Schuh': ('kauf', '鞋'),
    'Schule': ('lernen', '学校'),
    'Schüler': ('lernen', '（中小学、培训班的）学生'),
    'schwer': ('basis', '重的；难的'),
    'Schwester': ('person', '姐妹'),
    'schwimmen': ('freizeit', '游泳'),
    'Schwimmbad': ('freizeit', '游泳馆'),
    'See': ('umwelt', '湖（der See）'),
    'sehen': ('basis', '看见'),
    'Sehenswürdigkeit': ('reisen', '名胜、景点'),
    'sehr': ('basis', '很'),
    'sein': ('funktion', '是；也是完成时的助动词'),
    'weg sein': ('basis', '走了、不在了'),
    'zu sein': ('wohnen', '关着的'),
    'seit': ('funktion', '自从…以来（三格介词，配现在时）'),
    'selbstständig': ('arbeit', '自己开业的、自雇的'),
    'sich': ('funktion', '自己（反身代词，第三人称与 Sie）'),
    'sie': ('funktion', '她；他们'),
    'Sie': ('funktion', '您、您们（尊称，永远大写）'),
    'sitzen': ('basis', '坐着'),
    'so': ('basis', '这样；这么'),
    'Sofa': ('wohnen', '沙发'),
    'sofort': ('basis', '立刻'),
    'Sohn': ('person', '儿子'),
    'sollen': ('funktion', '应该、要不要（情态动词）'),
    'Sonne': ('umwelt', '太阳'),
    'spät': ('basis', '晚的'),
    'später': ('basis', '稍后、以后'),
    'Speisekarte': ('essen', '菜单'),
    'spielen': ('freizeit', '玩；打（球）；演奏'),
    'Sport': ('freizeit', '体育运动（Sport machen 做运动）'),
    'Sprache': ('lernen', '语言'),
    'sprechen': ('basis', '说、讲（mit 与某人 / über 谈某事）'),
    'Stadt': ('wohnen', '城市'),
    'stehen': ('basis', '站着；（文字）写着'),
    'Stelle': ('arbeit', '职位；位置'),
    'stellen': ('wohnen', '（竖着）放（四格 + 方位）'),
    'Stock': ('wohnen', '楼层（im ersten Stock 二楼）'),
    'Straße': ('wohnen', '街道'),
    'Straßenbahn': ('reisen', '有轨电车'),
    'studieren': ('lernen', '上大学、攻读'),
    'Studium': ('lernen', '大学学业'),
    'Student': ('lernen', '大学生'),
    'Stunde': ('basis', '小时；课时'),
    'suchen': ('basis', '找、寻找'),
    'tanzen': ('freizeit', '跳舞'),
    'Tasche': ('kauf', '包；口袋'),
    'Taxi': ('reisen', '出租车'),
    'Tee': ('essen', '茶'),
    'Teil': ('basis', '部分'),
    'telefonieren': ('dienst', '打电话（mit + 三格）'),
    'Telefon': ('dienst', '电话'),
    'Termin': ('person', '预约、约定的时间'),
    'Test': ('lernen', '测验'),
    'teuer': ('kauf', '贵的'),
    'Text': ('lernen', '文本、课文'),
    'Thema': ('lernen', '话题、主题'),
    'Ticket': ('reisen', '票'),
    'Tisch': ('wohnen', '桌子'),
    'Tochter': ('person', '女儿'),
    'Toilette': ('wohnen', '厕所'),
    'Tomate': ('essen', '西红柿'),
    'tot': ('person', '死了的'),
    '(sich) treffen': ('person', '遇见；见面（sich treffen 相约见面）'),
    'Treppe': ('wohnen', '楼梯'),
    'trinken': ('essen', '喝'),
    'tschüss': ('basis', '再见（非正式）'),
    'tun': ('basis', '做'),
    'über': ('funktion', '在…上方；关于（三四格介词）'),
    'übernachten': ('reisen', '过夜、住一宿'),
    'überweisen': ('dienst', '转账、汇款'),
    'Uhr': ('basis', '钟表；…点钟'),
    'um': ('funktion', '在…点钟；围绕（四格介词）'),
    'umziehen': ('wohnen', '搬家（可分）'),
    'und': ('funktion', '和、而且'),
    'unser-': ('funktion', '我们的（物主冠词）'),
    'unten': ('basis', '下面'),
    'unter': ('funktion', '在…下面（三四格介词）'),
    'Unterricht': ('lernen', '课、教学'),
    'unterschreiben': ('dienst', '签字'),
    'Unterschrift': ('dienst', '签名'),
    'Urlaub': ('arbeit', '休假（Urlaub nehmen 休假）'),
    'Vater': ('person', '父亲'),
    'verboten': ('basis', '禁止的'),
    'verdienen': ('arbeit', '挣（钱）'),
    'Verein': ('freizeit', '协会、俱乐部'),
    'verheiratet': ('person', '已婚的'),
    'verkaufen': ('kauf', '卖'),
    'Verkäufer': ('arbeit', '售货员'),
    'vermieten': ('wohnen', '出租、租出'),
    'Vermieter': ('wohnen', '房东'),
    'verstehen': ('basis', '听懂、理解'),
    'Verwandte': ('person', '亲戚（形容词变名词）'),
    'viel': ('basis', '多'),
    'vielleicht': ('basis', '也许'),
    'von': ('funktion', '从…；…的（三格介词，代替二格）'),
    'vor': ('funktion', '在…前面；…之前（三四格介词）'),
    'Vorname': ('person', '名（姓之外的那部分）'),
    'Vorsicht': ('basis', '小心（Vorsicht! 当心）'),
    '(sich) vorstellen': ('person', '介绍（sich vorstellen 自我介绍，可分）'),
    'Vorwahl': ('dienst', '区号'),
    'wandern': ('freizeit', '徒步、远足'),
    'wann': ('funktion', '什么时候'),
    'warten': ('basis', '等（auf + 四格：等某人某物）'),
    'warum': ('funktion', '为什么'),
    'was': ('funktion', '什么'),
    'was für ein': ('funktion', '什么样的'),
    '(sich) waschen': ('person', '洗（sich waschen 洗漱）'),
    'Wasser': ('essen', '水'),
    'weh tun': ('person', '疼（三格：谁疼）'),
    'weiblich': ('person', '女性的（表格上的选项）'),
    'Wein': ('essen', '葡萄酒'),
    'weit': ('basis', '远的'),
    'weiter': ('basis', '继续、再往前'),
    'welch-': ('funktion', '哪一个'),
    'Welt': ('umwelt', '世界'),
    'wenig': ('basis', '少'),
    'wer': ('funktion', '谁'),
    'werden': ('basis', '成为、变得；也是将来时与被动的助动词'),
    'Wetter': ('umwelt', '天气'),
    'wichtig': ('basis', '重要的'),
    'wie': ('funktion', '怎样、如何；像'),
    'wiederholen': ('lernen', '重复、复习（不可分）'),
    'Wiederhören': ('dienst', '再会（打电话：Auf Wiederhören）'),
    'Wiedersehen': ('basis', '再见（Auf Wiedersehen）'),
    'wie viel': ('funktion', '多少'),
    'willkommen': ('basis', '欢迎'),
    'Wind': ('umwelt', '风'),
    'wir': ('funktion', '我们'),
    'wissen': ('basis', '知道（变位不规则：ich weiß）'),
    'wo': ('funktion', '在哪里'),
    'woher': ('funktion', '从哪里来'),
    'wohin': ('funktion', '到哪里去'),
    'wohnen': ('wohnen', '居住'),
    'Wohnung': ('wohnen', '住房、公寓'),
    'wollen': ('funktion', '想要、打算（情态动词）'),
    'Wort': ('lernen', '单词'),
    'wunderbar': ('basis', '好极了、妙极了'),
    'zahlen': ('kauf', '付钱（Zahlen, bitte! 买单）'),
    'Zeit': ('basis', '时间'),
    'zurzeit': ('basis', '目前、眼下'),
    'Zeitung': ('freizeit', '报纸'),
    'Zigarette': ('kauf', '香烟'),
    'Zimmer': ('wohnen', '房间'),
    'Zoll': ('reisen', '海关'),
    'zu': ('funktion', '到…去（三格介词）；太…（副词）'),
    'zufrieden': ('basis', '满意的（mit + 三格）'),
    'Zug': ('reisen', '火车'),
    'zurück': ('basis', '回来、返回'),
    'zusammen': ('basis', '一起'),
    'zwischen': ('funktion', '在…之间（三四格介词）'),
}
