# -*- coding: utf-8 -*-
"""例句拆解（Zergliederung）。参考 FlashCard 的 trans.py，但按德语重做。

主轨是「顺读」：德→中逐块、每块标成分，按德语原序读下去。
德语特色：
  - Satzklammer 句框：情态动词 / 可分动词 / Perfekt 三种情形下，
    变位动词占第二位，动词第二部分被挤到句末——用 klammer 画出这个框。
  - 名词短语标注格（Nominativ / Akkusativ / Dativ），这是中文里没有的范畴。
  - 完整译文按成分着色，让读者看出每段中文来自哪个德语意群。

键 = 官方例句原文（与词表逐字一致，构建期校验）。
字段：
  zh      完整中文翻译
  pat     句型标签
  flow    [德块, 中文块, 成分] —— 按德语原序；拼接回原句由构建期校验
  klammer 可选 [框前, 框左动词, 框中成分, 框右动词第二部分, 类型]
          type ∈ modal(情态) | trennbar(可分) | perfekt(Perfekt)
  kasus   可选 [德语短语, 格]
  final   可选 [中文块, 成分] —— 完整译文；缺省用 zh
  tip     一句话点破

成分代号：s 主语 · v 变位动词 · v2 动词第二部分 · a 状语 · o 宾语 ·
          d 定语 · c 从句 · x 默认
"""
SATZ = {
# ============================================================
# 一、情态动词 Satzklammer（框左 = 情态动词，框右 = 不定式）
# ============================================================

"Ich muss immer um vier Uhr aufstehen.": {
    "zh": "我必须总是四点钟起床。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Ich", "我", "s"], ["muss", "必须", "v"], ["immer", "总是", "a"],
             ["um vier Uhr", "在四点钟", "a"], ["aufstehen", "起床", "v2"]],
    "klammer": ["Ich", "muss", "immer um vier Uhr", "aufstehen", "modal"],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["必须", "v"], ["总是", "a"], ["在四点钟", "a"], ["起床", "v2"], ["。", "x"]],
    "tip": "muss 占第二位，aufstehen 被挤到句末，中间夹住 immer um vier Uhr——这就是句框。",
},
"Ich muss meine Schlüssel abgeben.": {
    "zh": "我必须把钥匙交出去。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Ich", "我", "s"], ["muss", "必须", "v"], ["meine Schlüssel", "我的钥匙", "o"],
             ["abgeben", "交出去", "v2"]],
    "klammer": ["Ich", "muss", "meine Schlüssel", "abgeben", "modal"],
    "kasus": [["Ich", "Nominativ"], ["meine Schlüssel", "Akkusativ"]],
    "final": [["我", "s"], ["必须", "v"], ["把钥匙", "o"], ["交出去", "v2"], ["。", "x"]],
    "tip": "meine Schlüssel 是 Akkusativ（交什么）。abgeben 是可分动词，前缀 ab 随整体在句末。",
},
"Ich muss mich noch anziehen.": {
    "zh": "我还得穿好衣服。",
    "pat": "情态动词 · 反身",
    "flow": [["Ich", "我", "s"], ["muss", "得", "v"], ["mich", "自己", "o"],
             ["noch", "还", "a"], ["anziehen", "穿上衣服", "v2"]],
    "klammer": ["Ich", "muss", "mich noch", "anziehen", "modal"],
    "kasus": [["Ich", "Nominativ"], ["mich", "Akkusativ"]],
    "final": [["我", "s"], ["还得", "v"], ["穿好衣服", "v2"], ["。", "x"]],
    "tip": "sich anziehen 是反身动词，mich 随主语 Ich。anziehen 可分，前缀 an 在句末。",
},
"Ich muss noch für morgen einkaufen.": {
    "zh": "我还得为明天去买东西。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Ich", "我", "s"], ["muss", "得", "v"], ["noch", "还", "a"],
             ["für morgen", "为明天", "a"], ["einkaufen", "去买东西", "v2"]],
    "klammer": ["Ich", "muss", "noch für morgen", "einkaufen", "modal"],
    "final": [["我", "s"], ["还得", "v"], ["为明天", "a"], ["去买东西", "v2"], ["。", "x"]],
    "tip": "für morgen 是目的状语。einkaufen 可分，ein 在句末。",
},
"Ich muss jetzt das Essen machen.": {
    "zh": "我现在得做饭了。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Ich", "我", "s"], ["muss", "得", "v"], ["jetzt", "现在", "a"],
             ["das Essen", "饭", "o"], ["machen", "做", "v2"]],
    "klammer": ["Ich", "muss", "jetzt das Essen", "machen", "modal"],
    "kasus": [["Ich", "Nominativ"], ["das Essen", "Akkusativ"]],
    "final": [["我", "s"], ["现在", "a"], ["得", "v"], ["做饭", "v2"], ["了", "x"]],
    "tip": "das Essen machen = 做饭（das Essen 是 Akkusativ 宾语）。",
},
"Ich muss zum Arzt gehen.": {
    "zh": "我得去看医生。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Ich", "我", "s"], ["muss", "得", "v"], ["zum Arzt", "去看医生", "a"],
             ["gehen", "去", "v2"]],
    "klammer": ["Ich", "muss", "zum Arzt", "gehen", "modal"],
    "kasus": [["Ich", "Nominativ"], ["zum Arzt", "Dativ"]],
    "final": [["我", "s"], ["得", "v"], ["去看医生", "a"], ["。", "x"]],
    "tip": "zum = zu + dem，固定搭配 zum Arzt gehen（去看医生）。",
},
"Können Sie mir helfen?": {
    "zh": "您能帮我吗？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Können", "能", "v"], ["Sie", "您", "s"], ["mir", "我（帮我）", "o"],
             ["helfen", "帮助", "v2"]],
    "klammer": ["Sie", "Können", "mir", "helfen", "modal"],
    "kasus": [["Sie", "Nominativ"], ["mir", "Dativ"]],
    "final": [["您", "s"], ["能", "v"], ["帮我", "o"], ["吗？", "x"]],
    "tip": "疑问句里 Können 提到第一位，helfen 仍在句末。mir 是 Dativ（帮谁）。",
},
"Können Sie mir eine Auskunft geben?": {
    "zh": "您能给我一个答复吗？",
    "pat": "情态动词 · 双宾语",
    "flow": [["Können", "能", "v"], ["Sie", "您", "s"], ["mir", "我（给我）", "o"],
             ["eine Auskunft", "一个答复", "o"], ["geben", "给", "v2"]],
    "kasus": [["Sie", "Nominativ"], ["mir", "Dativ"], ["eine Auskunft", "Akkusativ"]],
    "final": [["您", "s"], ["能", "v"], ["给我", "o"], ["一个答复", "o"], ["吗？", "x"]],
    "tip": "双宾语：mir（Dativ，给谁）+ eine Auskunft（Akkusativ，给什么）。",
},
"Können Sie mir seine Adresse sagen?": {
    "zh": "您能把他的地址告诉我吗？",
    "pat": "情态动词 · 双宾语",
    "flow": [["Können", "能", "v"], ["Sie", "您", "s"], ["mir", "我（告诉我）", "o"],
             ["seine Adresse", "他的地址", "o"], ["sagen", "告诉", "v2"]],
    "kasus": [["Sie", "Nominativ"], ["mir", "Dativ"], ["seine Adresse", "Akkusativ"]],
    "final": [["您", "s"], ["能", "v"], ["把他的地址", "o"], ["告诉我", "o"], ["吗？", "x"]],
    "tip": "sagen + Dativ(给谁) + Akkusativ(内容)。mir 是 Dativ，seine Adresse 是 Akkusativ。",
},
"Können Sie das bitte wiederholen?": {
    "zh": "您能再说一遍吗？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Können", "能", "v"], ["Sie", "您", "s"], ["das", "这个", "o"],
             ["bitte", "请", "a"], ["wiederholen", "重复", "v2"]],
    "kasus": [["Sie", "Nominativ"], ["das", "Akkusativ"]],
    "final": [["您", "s"], ["能", "v"], ["再", "a"], ["说一遍", "v2"], ["吗？", "x"]],
    "tip": "没听清时的救场句：Können Sie das bitte wiederholen?",
},
"Ich möchte gern den Dom besichtigen.": {
    "zh": "我很想参观大教堂。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Ich", "我", "s"], ["möchte", "想", "v"], ["gern", "很乐意", "a"],
             ["den Dom", "大教堂", "o"], ["besichtigen", "参观", "v2"]],
    "klammer": ["Ich", "möchte", "gern den Dom", "besichtigen", "modal"],
    "kasus": [["Ich", "Nominativ"], ["den Dom", "Akkusativ"]],
    "final": [["我", "s"], ["很", "a"], ["想", "v"], ["参观", "v2"], ["大教堂", "o"], ["。", "x"]],
    "tip": "möchte 表委婉愿望。den Dom 是 Akkusativ（der → den）。",
},
"Ich möchte gern diesen Film sehen.": {
    "zh": "我很想看这部电影。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Ich", "我", "s"], ["möchte", "想", "v"], ["gern", "很乐意", "a"],
             ["diesen Film", "这部电影", "o"], ["sehen", "看", "v2"]],
    "klammer": ["Ich", "möchte", "gern diesen Film", "sehen", "modal"],
    "kasus": [["Ich", "Nominativ"], ["diesen Film", "Akkusativ"]],
    "final": [["我", "s"], ["很", "a"], ["想", "v"], ["看", "v2"], ["这部电影", "o"], ["。", "x"]],
    "tip": "diesen Film = dieser + Akkusativ（阳性名词宾语要变 den/diesen）。",
},
"Darf ich ein Foto machen?": {
    "zh": "我可以拍张照吗？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Darf", "可以", "v"], ["ich", "我", "s"], ["ein Foto", "一张照片", "o"],
             ["machen", "拍", "v2"]],
    "klammer": ["ich", "Darf", "ein Foto", "machen", "modal"],
    "kasus": [["ich", "Nominativ"], ["ein Foto", "Akkusativ"]],
    "final": [["我", "s"], ["可以", "v"], ["拍", "v2"], ["一张照片", "o"], ["吗？", "x"]],
    "tip": "ein Foto machen 固定搭配（拍照）。Darf ich…? = 我可以……吗？",
},
"Darf ich Sie zu einem Kaffee einladen?": {
    "zh": "我可以请您喝杯咖啡吗？",
    "pat": "情态动词 · 疑问句 + 可分",
    "flow": [["Darf", "可以", "v"], ["ich", "我", "s"], ["Sie", "您", "o"],
             ["zu einem Kaffee", "去喝杯咖啡", "a"], ["einladen", "邀请", "v2"]],
    "kasus": [["ich", "Nominativ"], ["Sie", "Akkusativ"]],
    "final": [["我", "s"], ["可以", "v"], ["请您", "o"], ["喝杯咖啡", "a"], ["吗？", "x"]],
    "tip": "einladen + Akkusativ(请谁) + zu(做什么)。einladen 可分，ein 在句末。",
},
"Ich kann nicht kommen, denn ich bin krank.": {
    "zh": "我不能来了，因为我病了。",
    "pat": "情态动词 + denn 原因",
    "flow": [["Ich", "我", "s"], ["kann", "能", "v"], ["nicht", "不", "a"],
             ["kommen", "来", "v2"], ["denn ich bin krank", "因为我病了", "c"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["不能", "v"], ["来", "v2"], ["了，", "x"], ["因为我病了", "c"], ["。", "x"]],
    "tip": "denn 连接原因分句，后面保持正常语序。kann nicht = 不能。",
},
"Wir möchten bestellen, bitte.": {
    "zh": "我们要点菜，麻烦您。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Wir", "我们", "s"], ["möchten", "想要", "v"], ["bestellen", "点菜", "v2"],
             ["bitte", "请", "a"]],
    "klammer": ["Wir", "möchten", "bitte", "bestellen", "modal"],
    "final": [["我们", "s"], ["要", "v"], ["点菜", "v2"], ["，", "x"], ["麻烦您", "x"], ["。", "x"]],
    "tip": "餐馆叫服务员：Wir möchten bestellen. = 我们要点菜。",
},
"Hier darf man nicht rauchen.": {
    "zh": "这里不许抽烟。",
    "pat": "情态动词 · 无人称",
    "flow": [["Hier", "这里", "a"], ["darf man", "人们可以", "v"], ["nicht", "不", "a"],
             ["rauchen", "抽烟", "v2"]],
    "kasus": [["man", "Nominativ"]],
    "final": [["这里", "a"], ["不许", "v"], ["抽烟", "v2"], ["。", "x"]],
    "tip": "man darf nicht = 禁止（无人称主语 man + 情态动词）。",
},
"Es darf nicht mehr als 15 Euro kosten.": {
    "zh": "它不能超过 15 欧元。",
    "pat": "情态动词 · 无人称",
    "flow": [["Es", "它", "s"], ["darf", "可以", "v"], ["nicht mehr als 15 Euro", "不超过 15 欧元", "o"],
             ["kosten", "花费", "v2"]],
    "kasus": [["Es", "Nominativ"]],
    "final": [["它", "s"], ["不能", "v"], ["超过", "v2"], ["15 欧元", "o"], ["。", "x"]],
    "tip": "nicht mehr als = 不超过。es 可指任何事物（价格）。",
},
"Wann kann ich Sie anrufen?": {
    "zh": "我什么时候能给您打电话？",
    "pat": "情态动词 · 疑问句 + 可分",
    "flow": [["Wann", "什么时候", "a"], ["kann", "能", "v"], ["ich", "我", "s"],
             ["Sie", "您", "o"], ["anrufen", "打电话", "v2"]],
    "kasus": [["ich", "Nominativ"], ["Sie", "Akkusativ"]],
    "final": [["我", "s"], ["什么时候", "a"], ["能", "v"], ["给您打电话", "v2"], ["？", "x"]],
    "tip": "anrufen = an + rufen（打电话），可分。疑问词 Wann 提前。",
},
"Was möchten Sie trinken?": {
    "zh": "您想喝点什么？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Was", "什么", "o"], ["möchten", "想", "v"], ["Sie", "您", "s"],
             ["trinken", "喝", "v2"]],
    "kasus": [["Sie", "Nominativ"], ["Was", "Akkusativ"]],
    "final": [["您", "s"], ["想", "v"], ["喝点什么", "v2"], ["？", "x"]],
    "tip": "Was + 情态动词 + 主语 + 不定式：您想喝点什么？",
},
"Was soll ich mitbringen?": {
    "zh": "我应该带点什么？",
    "pat": "情态动词 · 疑问句 + 可分",
    "flow": [["Was", "什么", "o"], ["soll", "应该", "v"], ["ich", "我", "s"],
             ["mitbringen", "带来", "v2"]],
    "kasus": [["ich", "Nominativ"], ["Was", "Akkusativ"]],
    "final": [["我", "s"], ["应该", "v"], ["带点什么", "v2"], ["？", "x"]],
    "tip": "mitbringen = mit + bringen（带来），可分。soll 表「应该」。",
},
"Sie können das Geld auch überweisen.": {
    "zh": "您也可以转账。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Sie", "您", "s"], ["können", "可以", "v"], ["das Geld", "钱", "o"],
             ["auch", "也", "a"], ["überweisen", "转账", "v2"]],
    "kasus": [["Sie", "Nominativ"], ["das Geld", "Akkusativ"]],
    "final": [["您", "s"], ["也", "a"], ["可以", "v"], ["转账", "v2"], ["。", "x"]],
    "tip": "überweisen = 转账（银行场景）。",
},
# ============================================================
# 二、可分动词（框右 = 前缀）
# ============================================================

"Der Unterricht fängt gleich an.": {
    "zh": "课马上就要开始了。",
    "pat": "可分动词 · 前缀在句末",
    "flow": [["Der Unterricht", "课", "s"], ["fängt", "开始", "v"], ["gleich", "马上", "a"],
             ["an", "（前缀）", "v2"]],
    "klammer": ["Der Unterricht", "fängt", "gleich", "an", "trennbar"],
    "kasus": [["Der Unterricht", "Nominativ"]],
    "final": [["课", "s"], ["马上", "a"], ["就要开始了", "v"], ["。", "x"]],
    "tip": "anfangen = an + fangen：变位部分 fängt 在二位，前缀 an 被挤到句末。",
},
"Der Kurs hört in einer Woche auf.": {
    "zh": "课程一周后结束。",
    "pat": "可分动词 · 前缀在句末",
    "flow": [["Der Kurs", "课程", "s"], ["hört", "结束", "v"], ["in einer Woche", "一周后", "a"],
             ["auf", "（前缀）", "v2"]],
    "klammer": ["Der Kurs", "hört", "in einer Woche", "auf", "trennbar"],
    "kasus": [["Der Kurs", "Nominativ"]],
    "final": [["课程", "s"], ["一周后", "a"], ["结束", "v"], ["。", "x"]],
    "tip": "aufhören = auf + hören：前缀 auf 句末。in einer Woche = 一周后。",
},
"Der Zug kommt in fünf Minuten.": {
    "zh": "火车五分钟后到。",
    "pat": "普通语序 · 时间",
    "flow": [["Der Zug", "火车", "s"], ["kommt", "到", "v"], ["in fünf Minuten", "五分钟后", "a"]],
    "kasus": [["Der Zug", "Nominativ"]],
    "final": [["火车", "s"], ["五分钟后", "a"], ["到", "v"], ["。", "x"]],
    "tip": "kommt 是 ankommen 的变位（这里省略了句末前缀 an 的完整框）。in + 时间 = 之后。",
},
"Die Hausfrau/der Hausmann wäscht, kocht und kauft ein.": {
    "zh": "家庭主妇/主夫洗衣服、做饭和买东西。",
    "pat": "并列谓词 + 可分",
    "flow": [["Die Hausfrau/der Hausmann", "家庭主妇/主夫", "s"],
             ["wäscht, kocht", "洗、做饭", "v"], ["und", "和", "x"], ["kauft", "买", "v"],
             ["ein", "（前缀）", "v2"]],
    "kasus": [["Die Hausfrau/der Hausmann", "Nominativ"]],
    "final": [["家庭主妇/主夫", "s"], ["洗衣服、做饭", "v"], ["和", "x"], ["买东西", "v"], ["。", "x"]],
    "tip": "三个并列谓语共用主语。einkaufen 的前缀 ein 只出现一次、在句末。",
},
"Das sieht schön aus.": {
    "zh": "那看起来很美。",
    "pat": "可分动词 · 前缀在句末",
    "flow": [["Das", "那", "s"], ["sieht", "看", "v"], ["schön", "美", "a"], ["aus", "（前缀）", "v2"]],
    "klammer": ["Das", "sieht", "schön", "aus", "trennbar"],
    "kasus": [["Das", "Nominativ"]],
    "final": [["那", "s"], ["看起来", "v"], ["很美", "a"], ["。", "x"]],
    "tip": "aussehen = aus + sehen（看起来）。系动词式用法。",
},
"Wo muss ich aussteigen?": {
    "zh": "我必须在哪儿下车？",
    "pat": "情态动词 · 疑问句 + 可分",
    "flow": [["Wo", "在哪里", "a"], ["muss", "必须", "v"], ["ich", "我", "s"],
             ["aussteigen", "下车", "v2"]],
    "kasus": [["ich", "Nominativ"]],
    "final": [["我", "s"], ["必须", "v"], ["在哪儿", "a"], ["下车", "v2"], ["？", "x"]],
    "tip": "aussteigen = aus + steigen（下车）。Wo muss ich aussteigen? 乘车问法。",
},
# ============================================================
# 三、Perfekt（框右 = 过去分词）
# ============================================================

"Ich habe Ihre E-Mail nicht bekommen.": {
    "zh": "我没有收到您的电子邮件。",
    "pat": "Perfekt · haben + Partizip",
    "flow": [["Ich", "我", "s"], ["habe", "（助动词）", "v"], ["Ihre E-Mail", "您的邮件", "o"],
             ["nicht", "没有", "a"], ["bekommen", "收到", "v2"]],
    "klammer": ["Ich", "habe", "Ihre E-Mail nicht", "bekommen", "perfekt"],
    "kasus": [["Ich", "Nominativ"], ["Ihre E-Mail", "Akkusativ"]],
    "final": [["我", "s"], ["没有", "a"], ["收到", "v2"], ["您的邮件", "o"], ["。", "x"]],
    "tip": "Perfekt 句框：habe 占第二位，Partizip bekommen 在句末。",
},
"Ich habe Ihre Anzeige in der Zeitung gelesen.": {
    "zh": "我在报纸上读了您的广告。",
    "pat": "Perfekt · haben + Partizip",
    "flow": [["Ich", "我", "s"], ["habe", "（助动词）", "v"], ["Ihre Anzeige", "您的广告", "o"],
             ["in der Zeitung", "在报纸上", "a"], ["gelesen", "读", "v2"]],
    "klammer": ["Ich", "habe", "Ihre Anzeige in der Zeitung", "gelesen", "perfekt"],
    "kasus": [["Ich", "Nominativ"], ["Ihre Anzeige", "Akkusativ"], ["der Zeitung", "Dativ"]],
    "final": [["我", "s"], ["在报纸上", "a"], ["读了", "v2"], ["您的广告", "o"], ["。", "x"]],
    "tip": "lesen → gelesen（强变化）。in der Zeitung：位置用 Dativ。",
},
"Ich habe die Durchsage nicht verstanden.": {
    "zh": "我没听懂广播。",
    "pat": "Perfekt · haben + Partizip",
    "flow": [["Ich", "我", "s"], ["habe", "（助动词）", "v"], ["die Durchsage", "广播", "o"],
             ["nicht", "没有", "a"], ["verstanden", "听懂", "v2"]],
    "klammer": ["Ich", "habe", "die Durchsage nicht", "verstanden", "perfekt"],
    "kasus": [["Ich", "Nominativ"], ["die Durchsage", "Akkusativ"]],
    "final": [["我", "s"], ["没有", "a"], ["听懂", "v2"], ["广播", "o"], ["。", "x"]],
    "tip": "verstehen → verstanden。nicht 在宾语后、Partizip 前。",
},
"Ich bin in Zagreb geboren.": {
    "zh": "我出生在萨格勒布。",
    "pat": "Perfekt · sein + Partizip",
    "flow": [["Ich", "我", "s"], ["bin", "（助动词）", "v"], ["in Zagreb", "在萨格勒布", "a"],
             ["geboren", "出生", "v2"]],
    "klammer": ["Ich", "bin", "in Zagreb", "geboren", "perfekt"],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["出生", "v2"], ["在萨格勒布", "a"], ["。", "x"]],
    "tip": "geboren 表状态，用 sein（不是 haben）。问出生地说 Wo sind Sie geboren?",
},
"Wann sind Sie geboren?": {
    "zh": "您是什么时候出生的？",
    "pat": "Perfekt · 疑问句",
    "flow": [["Wann", "什么时候", "a"], ["sind", "（助动词）", "v"], ["Sie", "您", "s"],
             ["geboren", "出生", "v2"]],
    "kasus": [["Sie", "Nominativ"]],
    "final": [["您", "s"], ["是", "v"], ["什么时候", "a"], ["出生的", "v2"], ["？", "x"]],
    "tip": "疑问词 Wann 提前，sind 第二位，主语 Sie 第三位。",
},
"Meine Frau ist gestern gestorben.": {
    "zh": "我妻子昨天去世了。",
    "pat": "Perfekt · sein + Partizip",
    "flow": [["Meine Frau", "我的妻子", "s"], ["ist", "（助动词）", "v"], ["gestern", "昨天", "a"],
             ["gestorben", "去世", "v2"]],
    "klammer": ["Meine Frau", "ist", "gestern", "gestorben", "perfekt"],
    "kasus": [["Meine Frau", "Nominativ"]],
    "final": [["我的妻子", "s"], ["昨天", "a"], ["去世了", "v2"], ["。", "x"]],
    "tip": "sterben → gestorben。状态变化类动词用 sein。",
},
"Wir haben ein Apartment gemietet.": {
    "zh": "我们租了一个公寓。",
    "pat": "Perfekt · haben + Partizip",
    "flow": [["Wir", "我们", "s"], ["haben", "（助动词）", "v"], ["ein Apartment", "一个公寓", "o"],
             ["gemietet", "租", "v2"]],
    "klammer": ["Wir", "haben", "ein Apartment", "gemietet", "perfekt"],
    "kasus": [["Wir", "Nominativ"], ["ein Apartment", "Akkusativ"]],
    "final": [["我们", "s"], ["租了", "v2"], ["一个公寓", "o"], ["。", "x"]],
    "tip": "mieten → gemietet（规则变化）。",
},
"Haben Sie meinen Brief bekommen?": {
    "zh": "您收到我的信了吗？",
    "pat": "Perfekt · 疑问句",
    "flow": [["Haben", "（助动词）", "v"], ["Sie", "您", "s"], ["meinen Brief", "我的信", "o"],
             ["bekommen", "收到", "v2"]],
    "kasus": [["Sie", "Nominativ"], ["meinen Brief", "Akkusativ"]],
    "final": [["您", "s"], ["收到", "v2"], ["我的信", "o"], ["了吗？", "x"]],
    "tip": "Perfekt 疑问句：助动词提到第一位。",
},
# ============================================================
# 四、Das ist 判断句（表语与主语同格）
# ============================================================

"Das ist Frau Becker.": {
    "zh": "这是贝克尔女士。",
    "pat": "判断句 · Das ist",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["Frau Becker", "贝克尔女士", "x"]],
    "final": [["这", "s"], ["是", "v"], ["贝克尔女士", "x"], ["。", "x"]],
    "tip": "介绍人：Das ist + 名字。Frau = 女士（Herr = 先生）。",
},
"Das ist meine Freundin.": {
    "zh": "这是我的女朋友。",
    "pat": "判断句 · Das ist",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["meine Freundin", "我的女朋友", "x"]],
    "kasus": [["meine Freundin", "Nominativ"]],
    "final": [["这", "s"], ["是", "v"], ["我的女朋友", "x"], ["。", "x"]],
    "tip": "表语与主语同格（Nominativ）。meine Freundin = 我的女朋友。",
},
"Das ist ein Freund von mir.": {
    "zh": "这是我的一个朋友。",
    "pat": "判断句 · 介词定语",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["ein Freund", "一个朋友", "x"],
             ["von mir", "我的", "d"]],
    "kasus": [["ein Freund", "Nominativ"], ["mir", "Dativ"]],
    "final": [["这", "s"], ["是", "v"], ["我的一个朋友", "x"], ["。", "x"]],
    "tip": "ein Freund von mir = 我的一个朋友（von + Dativ 表所属）。",
},
"Das ist alles.": {
    "zh": "这就是全部了。",
    "pat": "判断句 · Das ist",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["alles", "全部", "x"]],
    "final": [["这", "s"], ["就是全部", "x"], ["了", "x"], ["。", "x"]],
    "tip": "alles = 一切/全部。购物/收尾时说 Das ist alles = 就这些了。",
},
"Das ist für Sie.": {
    "zh": "这是给您的。",
    "pat": "判断句 · 介词短语",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["für Sie", "给您的", "x"]],
    "kasus": [["Sie", "Akkusativ"]],
    "final": [["这", "s"], ["是", "v"], ["给您的", "x"], ["。", "x"]],
    "tip": "für + Akkusativ（给谁）。",
},
"Das ist der Schlüssel für die Haustür.": {
    "zh": "这是大门的钥匙。",
    "pat": "判断句 · 介词定语",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["der Schlüssel", "钥匙", "x"],
             ["für die Haustür", "大门（的）", "d"]],
    "kasus": [["der Schlüssel", "Nominativ"], ["die Haustür", "Akkusativ"]],
    "final": [["这", "s"], ["是", "v"], ["大门", "d"], ["的钥匙", "x"], ["。", "x"]],
    "tip": "für 短语作后置定语（门用的钥匙），中文提到名词前。",
},
"Das ist mir zu teuer.": {
    "zh": "这对我来说太贵了。",
    "pat": "判断句 · zu 太",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["mir", "对我", "a"], ["zu teuer", "太贵", "x"]],
    "kasus": [["mir", "Dativ"]],
    "final": [["这", "s"], ["对我", "a"], ["来说太贵了", "x"], ["。", "x"]],
    "tip": "zu + 形容词 = 太……。mir 是 Dativ（对我来说），购物拒绝理由。",
},
"Das ist in Ordnung.": {
    "zh": "没关系/可以。",
    "pat": "判断句 · 固定搭配",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["in Ordnung", "可以的", "x"]],
    "final": [["这", "s"], ["可以", "x"], ["。", "x"]],
    "tip": "in Ordnung = 没问题/可以。回应请求或道歉。",
},
# ============================================================
# 五、系动词 ich bin / wir sind（表语形容词或名词）
# ============================================================

"Ich bin Studentin.": {
    "zh": "我是大学生。",
    "pat": "系动词 · 表语名词",
    "flow": [["Ich", "我", "s"], ["bin", "是", "v"], ["Studentin", "女大学生", "x"]],
    "kasus": [["Ich", "Nominativ"], ["Studentin", "Nominativ"]],
    "final": [["我", "s"], ["是", "v"], ["大学生", "x"], ["。", "x"]],
    "tip": "表职业/身份的名词通常不加冠词。Student 的阴性是 Studentin。",
},
"Ich bin verheiratet und habe drei Kinder.": {
    "zh": "我结婚了，有三个孩子。",
    "pat": "并列句 · 系动词 + haben",
    "flow": [["Ich", "我", "s"], ["bin", "是", "v"], ["verheiratet", "已婚", "x"],
             ["und habe drei Kinder", "并且有三个孩子", "c"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["结婚了", "v"], ["，", "x"], ["有三个孩子", "c"], ["。", "x"]],
    "tip": "und 连接两个分句，第二个保留主谓宾语序。verheiratet 表状态。",
},
"Ich bin zu Hause.": {
    "zh": "我在家。",
    "pat": "系动词 · 处所",
    "flow": [["Ich", "我", "s"], ["bin", "在", "v"], ["zu Hause", "在家", "a"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["在家", "v"], ["。", "x"]],
    "tip": "zu Hause = 在家（固定搭配，注意 H 大写）。",
},
"Ich bin in einer Stunde zurück.": {
    "zh": "我一小时后回来。",
    "pat": "系动词 · 时间",
    "flow": [["Ich", "我", "s"], ["bin", "（回）", "v"], ["in einer Stunde", "一小时后", "a"],
             ["zurück", "回来", "a"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["一小时后", "a"], ["回来", "v"], ["。", "x"]],
    "tip": "in + 时间 = 之后（一小时后）。zurück = 回来。",
},
"Meine Frau ist so groß wie ich.": {
    "zh": "我妻子和我一样高。",
    "pat": "系动词 · 同级比较",
    "flow": [["Meine Frau", "我的妻子", "s"], ["ist", "是", "v"], ["so groß", "一样高", "x"],
             ["wie ich", "和我", "a"]],
    "kasus": [["Meine Frau", "Nominativ"]],
    "final": [["我的妻子", "s"], ["和我", "a"], ["一样高", "x"], ["。", "x"]],
    "tip": "so … wie = 和……一样（同级比较）。",
},
"Ich bin in Zagreb geboren.": {
    "zh": "我出生在萨格勒布。",
    "pat": "系动词 · 状态",
    "flow": [["Ich", "我", "s"], ["bin", "（状态）", "v"], ["in Zagreb", "在萨格勒布", "a"],
             ["geboren", "出生", "x"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["出生", "v"], ["在萨格勒布", "a"], ["。", "x"]],
    "tip": "geboren（born）作表语状态。问：Wo sind Sie geboren?",
},
# ============================================================
# 六、haben + Akkusativ（最基础句式）
# ============================================================

"Ich habe eine Frage.": {
    "zh": "我有一个问题。",
    "pat": "haben + Akkusativ",
    "flow": [["Ich", "我", "s"], ["habe", "有", "v"], ["eine Frage", "一个问题", "o"]],
    "kasus": [["Ich", "Nominativ"], ["eine Frage", "Akkusativ"]],
    "final": [["我", "s"], ["有", "v"], ["一个问题", "o"], ["。", "x"]],
    "tip": "Ich habe eine Frage = 我想问个问题（课堂/会话开场）。",
},
"Hast du einen Bleistift?": {
    "zh": "你有一支铅笔吗？",
    "pat": "haben · 疑问句",
    "flow": [["Hast", "有", "v"], ["du", "你", "s"], ["einen Bleistift", "一支铅笔", "o"]],
    "kasus": [["du", "Nominativ"], ["einen Bleistift", "Akkusativ"]],
    "final": [["你", "s"], ["有", "v"], ["一支铅笔", "o"], ["吗？", "x"]],
    "tip": "ein → einen：阳性名词的 Akkusativ，A1 必考变化。",
},
"Hast du es eilig?": {
    "zh": "你赶时间吗？",
    "pat": "haben + 固定搭配",
    "flow": [["Hast", "有", "v"], ["du", "你", "s"], ["es eilig", "赶时间", "x"]],
    "kasus": [["du", "Nominativ"]],
    "final": [["你", "s"], ["赶时间", "v"], ["吗？", "x"]],
    "tip": "es eilig haben = 赶时间（固定搭配，es 是形式宾语）。",
},
"Ich habe heute keine Zeit.": {
    "zh": "我今天没有时间。",
    "pat": "haben + kein",
    "flow": [["Ich", "我", "s"], ["habe", "有", "v"], ["heute", "今天", "a"],
             ["keine Zeit", "没有时间", "o"]],
    "kasus": [["Ich", "Nominativ"], ["keine Zeit", "Akkusativ"]],
    "final": [["我", "s"], ["今天", "a"], ["没有", "v"], ["时间", "o"], ["。", "x"]],
    "tip": "keine Zeit = 没有时间。nicht 否定动词、kein 否定名词。",
},
"Hast du schon eine Fahrkarte?": {
    "zh": "你已经买票了吗？",
    "pat": "haben · 疑问句",
    "flow": [["Hast", "有", "v"], ["du", "你", "s"], ["schon", "已经", "a"],
             ["eine Fahrkarte", "一张车票", "o"]],
    "kasus": [["du", "Nominativ"], ["eine Fahrkarte", "Akkusativ"]],
    "final": [["你", "s"], ["已经", "a"], ["买票", "o"], ["了吗？", "x"]],
    "tip": "schon = 已经。乘车场景。",
},
# ============================================================
# 七、疑问句（疑问词 / 动词提前）
# ============================================================

"Wie heißt das auf Deutsch?": {
    "zh": "这个用德语怎么说？",
    "pat": "疑问词 · 怎么",
    "flow": [["Wie", "怎么", "a"], ["heißt", "说", "v"], ["das", "这个", "s"],
             ["auf Deutsch", "用德语", "a"]],
    "kasus": [["das", "Nominativ"]],
    "final": [["这个", "s"], ["用德语", "a"], ["怎么说", "v"], ["？", "x"]],
    "tip": "疑问词 Wie 占一位，动词第二位，主语第三位。auf Deutsch = 用德语。",
},
"Wie heißen Sie, bitte?": {
    "zh": "请问您贵姓？",
    "pat": "疑问词 · 怎么",
    "flow": [["Wie", "怎么", "a"], ["heißen", "叫", "v"], ["Sie", "您", "s"], ["bitte", "请", "a"]],
    "kasus": [["Sie", "Nominativ"]],
    "final": [["您", "s"], ["贵姓", "v"], ["？", "x"]],
    "tip": "heißen = 被叫作。回答：Ich heiße …。",
},
"Wie alt sind Sie?": {
    "zh": "您多大年纪？",
    "pat": "疑问词 · 年龄",
    "flow": [["Wie alt", "多大", "a"], ["sind", "是", "v"], ["Sie", "您", "s"]],
    "kasus": [["Sie", "Nominativ"]],
    "final": [["您", "s"], ["多大", "a"], ["年纪", "x"], ["？", "x"]],
    "tip": "Wie alt bist du? = 你几岁？回答：Ich bin 20 Jahre alt. 或 Ich bin dreiundzwanzig.",
},
"Woher kommen Sie? – Aus Frankreich.": {
    "zh": "您从哪里来？——来自法国。",
    "pat": "疑问词 · 来源",
    "flow": [["Woher", "从哪里", "a"], ["kommen", "来", "v"], ["Sie", "您", "s"],
             ["Aus Frankreich", "来自法国", "a"]],
    "kasus": [["Sie", "Nominativ"]],
    "final": [["您", "s"], ["从哪里", "a"], ["来", "v"], ["？", "x"], ["来自法国", "x"]],
    "tip": "Woher kommen Sie? = 您来自哪里？回答：Ich komme aus …（aus + 国名）。",
},
"Was ist das?": {
    "zh": "那是什么？",
    "pat": "疑问词 · 什么",
    "flow": [["Was", "什么", "s"], ["ist", "是", "v"], ["das", "那", "s"]],
    "final": [["那", "s"], ["是", "v"], ["什么", "s"], ["？", "x"]],
    "tip": "A1 第一课就会学到的问法。",
},
"Was ist Ihr Beruf?": {
    "zh": "您的职业是什么？",
    "pat": "疑问词 · 什么",
    "flow": [["Was", "什么", "s"], ["ist", "是", "v"], ["Ihr Beruf", "您的职业", "s"]],
    "kasus": [["Ihr Beruf", "Nominativ"]],
    "final": [["您的职业", "s"], ["是什么", "v"], ["？", "x"]],
    "tip": "询问职业。回答：Ich bin Lehrer. / Ich bin von Beruf …",
},
"Wie viel kostet das? – 10 Euro.": {
    "zh": "这个多少钱？——10 欧元。",
    "pat": "疑问词 · 价格",
    "flow": [["Wie viel", "多少", "a"], ["kostet", "花费", "v"], ["das", "这个", "s"],
             ["10 Euro", "10 欧元", "x"]],
    "kasus": [["das", "Nominativ"]],
    "final": [["这个", "s"], ["多少钱", "v"], ["？", "x"], ["10 欧元", "x"]],
    "tip": "kosten = 花费。Wie viel kostet …? 购物必问句。",
},
"Wo ist der Ausgang?": {
    "zh": "出口在哪里？",
    "pat": "疑问词 · 哪里",
    "flow": [["Wo", "在哪里", "a"], ["ist", "是", "v"], ["der Ausgang", "出口", "s"]],
    "kasus": [["der Ausgang", "Nominativ"]],
    "final": [["出口", "s"], ["在哪里", "a"], ["？", "x"]],
    "tip": "Wo ist …? 找地方的基本问法。",
},
"Wohin fährt dieser Bus?": {
    "zh": "这辆公交车开往哪里？",
    "pat": "疑问词 · 方向",
    "flow": [["Wohin", "往哪里", "a"], ["fährt", "开", "v"], ["dieser Bus", "这辆公交车", "s"]],
    "kasus": [["dieser Bus", "Nominativ"]],
    "final": [["这辆公交车", "s"], ["开往", "v"], ["哪里", "a"], ["？", "x"]],
    "tip": "Wohin 问方向（去向），Wo 问位置（静止）。",
},
"Wann kommst du zurück?": {
    "zh": "你什么时候回来？",
    "pat": "疑问词 · 时间",
    "flow": [["Wann", "什么时候", "a"], ["kommst", "来", "v"], ["du", "你", "s"],
             ["zurück", "回来", "v2"]],
    "kasus": [["du", "Nominativ"]],
    "final": [["你", "s"], ["什么时候", "a"], ["回来", "v"], ["？", "x"]],
    "tip": "zurückkommen 可分，zurück 在句末。kommst 是 du 的变位。",
},
# ============================================================
# 八、祈使句
# ============================================================

"Bitte schreiben Sie Ihren Geburtsort auf das Formular.": {
    "zh": "请把您的出生地写在表格上。",
    "pat": "祈使句 · 可分",
    "flow": [["Bitte", "请", "a"], ["schreiben Sie", "您写", "v"], ["Ihren Geburtsort", "您的出生地", "o"],
             ["auf das Formular", "在表格上", "a"]],
    "kasus": [["Sie", "Nominativ"], ["Ihren Geburtsort", "Akkusativ"]],
    "final": [["请", "a"], ["把您的出生地", "o"], ["写在表格上", "v"], ["。", "x"]],
    "tip": "aufschreiben 可分，这里 auf 在句末作介词短语的一部分。填表场景。",
},
"Gehen Sie immer geradeaus!": {
    "zh": "您一直往前走！",
    "pat": "祈使句",
    "flow": [["Gehen Sie", "您走", "v"], ["immer", "一直", "a"], ["geradeaus", "直", "a"]],
    "kasus": [["Sie", "Nominativ"]],
    "final": [["您", "s"], ["一直", "a"], ["往前走", "v"], ["！", "x"]],
    "tip": "指路用语：geradeaus = 直行。",
},
"Bitte nehmen Sie Platz!": {
    "zh": "请坐！",
    "pat": "祈使句",
    "flow": [["Bitte", "请", "a"], ["nehmen Sie", "您请", "v"], ["Platz", "座位", "o"]],
    "kasus": [["Sie", "Nominativ"], ["Platz", "Akkusativ"]],
    "final": [["请", "a"], ["坐", "v"], ["！", "x"]],
    "tip": "Platz nehmen = 就座（固定搭配）。",
},
"Bitte, schließen Sie die Tür.": {
    "zh": "请关门。",
    "pat": "祈使句",
    "flow": [["Bitte", "请", "a"], ["schließen Sie", "您关", "v"], ["die Tür", "门", "o"]],
    "kasus": [["Sie", "Nominativ"], ["die Tür", "Akkusativ"]],
    "final": [["请", "a"], ["关", "v"], ["门", "o"], ["。", "x"]],
    "tip": "schließen + Akkusativ（关……）。反义 aufmachen（打开）。",
},
# ============================================================
# 九、普通语序（主 + 谓 + 宾/状）
# ============================================================

"Wir haben eine neue Wohnung.": {
    "zh": "我们有一套新房子。",
    "pat": "普通语序 · haben",
    "flow": [["Wir", "我们", "s"], ["haben", "有", "v"], ["eine neue Wohnung", "一套新房子", "o"]],
    "kasus": [["Wir", "Nominativ"], ["eine neue Wohnung", "Akkusativ"]],
    "final": [["我们", "s"], ["有", "v"], ["一套新房子", "o"], ["。", "x"]],
    "tip": "eine neue Wohnung：形容词按阴性变化（neue）。",
},
"Die Wohnung hat drei Zimmer.": {
    "zh": "这套房子有三个房间。",
    "pat": "普通语序 · haben",
    "flow": [["Die Wohnung", "房子", "s"], ["hat", "有", "v"], ["drei Zimmer", "三个房间", "o"]],
    "kasus": [["Die Wohnung", "Nominativ"], ["drei Zimmer", "Akkusativ"]],
    "final": [["房子", "s"], ["有", "v"], ["三个房间", "o"], ["。", "x"]],
    "tip": "das Zimmer 单复同形。",
},
"Meine Familie lebt in Spanien.": {
    "zh": "我的家人住在西班牙。",
    "pat": "普通语序 · 处所",
    "flow": [["Meine Familie", "我的家人", "s"], ["lebt", "住", "v"], ["in Spanien", "在西班牙", "a"]],
    "kasus": [["Meine Familie", "Nominativ"]],
    "final": [["我的家人", "s"], ["住在", "v"], ["西班牙", "a"], ["。", "x"]],
    "tip": "in + 国名（不带冠词）= 在……。",
},
"Mein Bruder sucht Arbeit.": {
    "zh": "我哥哥在找工作。",
    "pat": "普通语序 · 宾语",
    "flow": [["Mein Bruder", "我哥哥", "s"], ["sucht", "找", "v"], ["Arbeit", "工作", "o"]],
    "kasus": [["Mein Bruder", "Nominativ"], ["Arbeit", "Akkusativ"]],
    "final": [["我哥哥", "s"], ["在找工作", "v"], ["。", "x"]],
    "tip": "Arbeit suchen = 找工作（求职场景）。",
},
"Die Kinder spielen draußen.": {
    "zh": "孩子们在外面玩。",
    "pat": "普通语序 · 处所",
    "flow": [["Die Kinder", "孩子们", "s"], ["spielen", "玩", "v"], ["draußen", "外面", "a"]],
    "kasus": [["Die Kinder", "Nominativ"]],
    "final": [["孩子们", "s"], ["在外面", "a"], ["玩", "v"], ["。", "x"]],
    "tip": "draußen = 在外面（反义 drinnen 在里面）。",
},
"Die Sonne scheint.": {
    "zh": "阳光明媚。",
    "pat": "普通语序",
    "flow": [["Die Sonne", "太阳", "s"], ["scheint", "照耀", "v"]],
    "kasus": [["Die Sonne", "Nominativ"]],
    "final": [["阳光", "s"], ["明媚", "v"], ["。", "x"]],
    "tip": "scheinen = 照耀。天气表达。",
},
"Das Essen schmeckt wunderbar.": {
    "zh": "饭菜味道好极了。",
    "pat": "感官系动词",
    "flow": [["Das Essen", "饭菜", "s"], ["schmeckt", "尝起来", "v"], ["wunderbar", "好极了", "x"]],
    "kasus": [["Das Essen", "Nominativ"]],
    "final": [["饭菜", "s"], ["味道好极了", "v"], ["。", "x"]],
    "tip": "schmecken + 形容词 = 尝起来……。wunderbar = 妙极了。",
},
"Der Kaffee schmeckt bitter.": {
    "zh": "咖啡尝起来苦。",
    "pat": "感官系动词",
    "flow": [["Der Kaffee", "咖啡", "s"], ["schmeckt", "尝起来", "v"], ["bitter", "苦", "x"]],
    "kasus": [["Der Kaffee", "Nominativ"]],
    "final": [["咖啡", "s"], ["尝起来", "v"], ["苦", "x"], ["。", "x"]],
    "tip": "schmecken + 形容词。bitter = 苦。",
},
"Die Farbe gefällt mir gut.": {
    "zh": "我很喜欢这个颜色。",
    "pat": "gefallen + Dativ",
    "flow": [["Die Farbe", "颜色", "s"], ["gefällt", "使喜欢", "v"], ["mir", "我", "o"], ["gut", "很", "a"]],
    "kasus": [["Die Farbe", "Nominativ"], ["mir", "Dativ"]],
    "final": [["我很喜欢", "v"], ["这个颜色", "s"], ["。", "x"]],
    "tip": "gefallen + Dativ：使（人）喜欢。主语是颜色，mir 是 Dativ。",
},
"Der Bus fährt zum Bahnhof.": {
    "zh": "这辆公交车开往火车站。",
    "pat": "普通语序 · 方向",
    "flow": [["Der Bus", "公交车", "s"], ["fährt", "开", "v"], ["zum Bahnhof", "去火车站", "a"]],
    "kasus": [["Der Bus", "Nominativ"]],
    "final": [["公交车", "s"], ["开往", "v"], ["火车站", "a"], ["。", "x"]],
    "tip": "zum = zu + dem（方向）。",
},
"Ich habe eine neue Stelle.": {
    "zh": "我有一份新工作。",
    "pat": "普通语序 · haben",
    "flow": [["Ich", "我", "s"], ["habe", "有", "v"], ["eine neue Stelle", "一份新工作", "o"]],
    "kasus": [["Ich", "Nominativ"], ["eine neue Stelle", "Akkusativ"]],
    "final": [["我", "s"], ["有", "v"], ["一份新工作", "o"], ["。", "x"]],
    "tip": "die Stelle = 职位/工作。求职场景。",
},
# ============================================================
# 十、Das ist 判断句（补）+ Es gibt + Ich bin + Hast du / Haben Sie
# ============================================================

"Das ist Hans, mein Sohn.": {
    "zh": "这是汉斯，我的儿子。",
    "pat": "判断句 · 同位语",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["Hans", "汉斯", "x"], ["mein Sohn", "我的儿子", "x"]],
    "final": [["这", "s"], ["是", "v"], ["汉斯", "x"], ["，", "x"], ["我的儿子", "x"], ["。", "x"]],
    "tip": "mein Sohn 是 Hans 的同位语，指同一人。",
},
"Das ist das Brot für morgen.": {
    "zh": "这是明天的面包。",
    "pat": "判断句 · 介词定语",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["das Brot", "面包", "x"], ["für morgen", "明天的", "d"]],
    "kasus": [["das Brot", "Nominativ"]],
    "final": [["这", "s"], ["是", "v"], ["明天", "d"], ["的面包", "x"], ["。", "x"]],
    "tip": "für morgen = 为明天准备（后置定语），中文提前到名词前。",
},
"Das ist der gleiche Preis.": {
    "zh": "这是同样的价格。",
    "pat": "判断句 · Das ist",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["der gleiche Preis", "同样的价格", "x"]],
    "kasus": [["der gleiche Preis", "Nominativ"]],
    "final": [["这", "s"], ["是", "v"], ["同样的价格", "x"], ["。", "x"]],
    "tip": "der gleiche Preis = 同样的价格（gleiche 形容词按 der 变格）。",
},
"Das ist doch schön, nicht?": {
    "zh": "这很好看，不是吗？",
    "pat": "判断句 · 反诘",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["doch schön", "确实很美", "x"], ["nicht", "不是吗", "x"]],
    "final": [["这", "s"], ["确实很美", "v"], ["，", "x"], ["不是吗", "x"], ["？", "x"]],
    "tip": "doch 加强语气（确实）。nicht? 反问表征求同意。",
},
"Das ist eine schwere Arbeit.": {
    "zh": "这是繁重的工作。",
    "pat": "判断句 · Das ist",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["eine schwere Arbeit", "一份繁重的工作", "x"]],
    "kasus": [["eine schwere Arbeit", "Nominativ"]],
    "final": [["这", "s"], ["是", "v"], ["一份繁重的工作", "x"], ["。", "x"]],
    "tip": "eine schwere Arbeit：形容词按阴性变格。schwer = 繁重/难。",
},
"Das ist eine schwere Aufgabe.": {
    "zh": "这是一个难题。",
    "pat": "判断句 · Das ist",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["eine schwere Aufgabe", "一个困难的作业", "x"]],
    "kasus": [["eine schwere Aufgabe", "Nominativ"]],
    "final": [["这", "s"], ["是", "v"], ["一个难题", "x"], ["。", "x"]],
    "tip": "eine schwere Aufgabe = 一个难题。",
},
"Das ist falsch.": {
    "zh": "这是错的。",
    "pat": "判断句 · Das ist",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["falsch", "错的", "x"]],
    "final": [["这", "s"], ["是", "v"], ["错的", "x"], ["。", "x"]],
    "tip": "falsch = 错误（反义 richtig）。",
},
"Das ist mein (Ehe-) Mann/meine (Ehe-) Frau.": {
    "zh": "这是我的丈夫/妻子。",
    "pat": "判断句 · Das ist",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["mein (Ehe-) Mann", "我的丈夫", "x"],
             ["meine (Ehe-) Frau", "我的妻子", "x"]],
    "kasus": [["mein (Ehe-) Mann", "Nominativ"], ["meine (Ehe-) Frau", "Nominativ"]],
    "final": [["这", "s"], ["是", "v"], ["我的丈夫/妻子", "x"], ["。", "x"]],
    "tip": "(Ehe-) Mann 强调「丈夫」而非普通男人。斜杠表示男/女说法。",
},
"Das ist meine Tochter Katharina.": {
    "zh": "这是我的女儿卡特琳娜。",
    "pat": "判断句 · 同位语",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["meine Tochter", "我的女儿", "x"],
             ["Katharina", "卡特琳娜", "x"]],
    "kasus": [["meine Tochter", "Nominativ"]],
    "final": [["这", "s"], ["是", "v"], ["我的女儿卡特琳娜", "x"], ["。", "x"]],
    "tip": "介绍家人：Das ist meine Tochter + 名字。",
},
"Das ist mir gleich.": {
    "zh": "这对我来说无所谓。",
    "pat": "判断句 · 双格",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["mir", "对我", "a"], ["gleich", "一样", "x"]],
    "kasus": [["mir", "Dativ"]],
    "final": [["这", "s"], ["对我", "a"], ["无所谓", "x"], ["。", "x"]],
    "tip": "Das ist mir gleich = 我无所谓。mir 是 Dativ。",
},
"Das ist richtig.": {
    "zh": "这是对的。",
    "pat": "判断句 · Das ist",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["richtig", "对的", "x"]],
    "final": [["这", "s"], ["是", "v"], ["对的", "x"], ["。", "x"]],
    "tip": "richtig = 正确（反义 falsch）。",
},
"Das ist sehr schwer.": {
    "zh": "这很难。",
    "pat": "判断句 · Das ist",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["sehr schwer", "很难", "x"]],
    "final": [["这", "s"], ["很难", "x"], ["。", "x"]],
    "tip": "schwer = 难/重。sehr 加强。",
},
"Das ist sehr schön.": {
    "zh": "这很美。",
    "pat": "判断句 · Das ist",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["sehr schön", "很美", "x"]],
    "final": [["这", "s"], ["很美", "x"], ["。", "x"]],
    "tip": "schön = 美。",
},
"Das ist unsere Lehrerin.": {
    "zh": "这是我们的老师。",
    "pat": "判断句 · Das ist",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["unsere Lehrerin", "我们的老师", "x"]],
    "kasus": [["unsere Lehrerin", "Nominativ"]],
    "final": [["这", "s"], ["是", "v"], ["我们的老师", "x"], ["。", "x"]],
    "tip": "unsere Lehrerin：阴性物主冠词。der Lehrer → die Lehrerin。",
},
"Es gibt bei uns viele Leute, die schon lange arbeitslos sind.": {
    "zh": "我们这里有很多失业很久的人。",
    "pat": "Es gibt + 关系从句",
    "flow": [["Es gibt", "有", "v"], ["bei uns", "我们这里", "a"], ["viele Leute", "很多人", "o"],
             ["die schon lange arbeitslos sind", "失业很久的", "c"]],
    "kasus": [["viele Leute", "Akkusativ"]],
    "final": [["我们这里", "a"], ["有", "v"], ["很多", "a"], ["失业很久的", "c"], ["人", "o"], ["。", "x"]],
    "tip": "Es gibt + Akkusativ = 有……。die 引导关系从句，动词放句末。",
},
"Es gibt einen neuen Sportverein in der Stadt.": {
    "zh": "城里有一个新的体育协会。",
    "pat": "Es gibt + Akkusativ",
    "flow": [["Es gibt", "有", "v"], ["einen neuen Sportverein", "一个新的体育协会", "o"],
             ["in der Stadt", "在城里", "a"]],
    "kasus": [["einen neuen Sportverein", "Akkusativ"], ["der Stadt", "Dativ"]],
    "final": [["城里", "a"], ["有", "v"], ["一个新的体育协会", "o"], ["。", "x"]],
    "tip": "einen neuen Sportverein：阳性 Akkusativ + 形容词变格。",
},
"Es gibt heute keinen Bus mehr. Er fährt mit dem Taxi.": {
    "zh": "今天没有公交车了。他坐出租车。",
    "pat": "Es gibt + 并列句",
    "flow": [["Es gibt", "有", "v"], ["heute", "今天", "a"], ["keinen Bus mehr", "不再有公交", "o"],
             ["Er fährt mit dem Taxi", "他坐出租车", "c"]],
    "kasus": [["keinen Bus", "Akkusativ"]],
    "final": [["今天", "a"], ["没有公交了", "v"], ["。", "x"], ["他坐出租车", "c"], ["。", "x"]],
    "tip": "keinen … mehr = 不再有。句号后是独立分句。",
},
"Es gibt keine Eintrittskarten mehr.": {
    "zh": "没有门票了。",
    "pat": "Es gibt + Akkusativ",
    "flow": [["Es gibt", "有", "v"], ["keine Eintrittskarten", "没有门票", "o"], ["mehr", "再", "a"]],
    "kasus": [["keine Eintrittskarten", "Akkusativ"]],
    "final": [["没有", "v"], ["门票", "o"], ["了", "x"], ["。", "x"]],
    "tip": "keine … mehr = 再也没有。die Eintrittskarte = 门票。",
},
"Es gibt keine Karten mehr.": {
    "zh": "没有票了。",
    "pat": "Es gibt + Akkusativ",
    "flow": [["Es gibt", "有", "v"], ["keine Karten", "没有票", "o"], ["mehr", "再", "a"]],
    "kasus": [["keine Karten", "Akkusativ"]],
    "final": [["没有", "v"], ["票", "o"], ["了", "x"], ["。", "x"]],
    "tip": "Es gibt + Akkusativ，keine … mehr = 售罄。",
},
"Es gibt viele Probleme auf der Welt.": {
    "zh": "世界上有很多问题。",
    "pat": "Es gibt + Akkusativ",
    "flow": [["Es gibt", "有", "v"], ["viele Probleme", "很多问题", "o"], ["auf der Welt", "在世界上", "a"]],
    "kasus": [["viele Probleme", "Akkusativ"], ["der Welt", "Dativ"]],
    "final": [["世界上", "a"], ["有", "v"], ["很多问题", "o"], ["。", "x"]],
    "tip": "auf der Welt = 在世界上。",
},
"Ich bin auch Spanier.": {
    "zh": "我也是西班牙人。",
    "pat": "系动词 · 表语名词",
    "flow": [["Ich", "我", "s"], ["bin", "是", "v"], ["auch", "也", "a"], ["Spanier", "西班牙人", "x"]],
    "final": [["我", "s"], ["也", "a"], ["是", "v"], ["西班牙人", "x"], ["。", "x"]],
    "tip": "表国籍/职业名词不加冠词。",
},
"Ich bin der neue Kollege.": {
    "zh": "我是新来的同事。",
    "pat": "系动词 · 表语名词",
    "flow": [["Ich", "我", "s"], ["bin", "是", "v"], ["der neue Kollege", "新同事", "x"]],
    "kasus": [["der neue Kollege", "Nominativ"]],
    "final": [["我", "s"], ["是", "v"], ["新同事", "x"], ["。", "x"]],
    "tip": "der neue Kollege：定冠词 + 形容词按阳性变格。",
},
"Ich bin dreiundzwanzig.": {
    "zh": "我二十三岁。",
    "pat": "系动词 · 年龄",
    "flow": [["Ich", "我", "s"], ["bin", "是", "v"], ["dreiundzwanzig", "23 岁", "x"]],
    "final": [["我", "s"], ["23 岁", "x"], ["。", "x"]],
    "tip": "报年龄直接说数字：Ich bin dreiundzwanzig = 我 23 岁。",
},
"Ich bin gegen diese Lösung.": {
    "zh": "我反对这个方案。",
    "pat": "系动词 · 介词宾语",
    "flow": [["Ich", "我", "s"], ["bin", "是", "v"], ["gegen diese Lösung", "反对这个方案", "a"]],
    "kasus": [["diese Lösung", "Akkusativ"]],
    "final": [["我", "s"], ["反对", "v"], ["这个方案", "a"], ["。", "x"]],
    "tip": "gegen + Akkusativ（反对……）。",
},
"Ich bin kulturell interessiert. Ich gehe oft ins Museum.": {
    "zh": "我对文化感兴趣，经常去博物馆。",
    "pat": "并列句 · 状态",
    "flow": [["Ich", "我", "s"], ["bin", "是", "v"], ["kulturell interessiert", "对文化感兴趣", "x"],
             ["Ich gehe oft ins Museum", "我经常去博物馆", "c"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我对文化感兴趣", "v"], ["，", "x"], ["经常去博物馆", "c"], ["。", "x"]],
    "tip": "interessiert sein an = 对……感兴趣。ins Museum = in + das。",
},
"Ich bin mit der Wohnung zufrieden.": {
    "zh": "我对这套房子很满意。",
    "pat": "系动词 · 固定搭配",
    "flow": [["Ich", "我", "s"], ["bin", "是", "v"], ["mit der Wohnung", "对这套房子", "a"],
             ["zufrieden", "满意", "x"]],
    "kasus": [["der Wohnung", "Dativ"]],
    "final": [["我对这套房子", "a"], ["很满意", "v"], ["。", "x"]],
    "tip": "zufrieden sein mit + Dativ = 对……满意。",
},
"Ich bin müde. Ich gehe schlafen.": {
    "zh": "我累了，我去睡觉。",
    "pat": "并列句",
    "flow": [["Ich", "我", "s"], ["bin", "是", "v"], ["müde", "累", "x"],
             ["Ich gehe schlafen", "我去睡觉", "c"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["累了", "v"], ["，", "x"], ["我去睡觉", "c"], ["。", "x"]],
    "tip": "schlafen gehen = 去睡觉（动词连用）。",
},
"Ich bin oft im Büro, aber nur für wenige Stunden.": {
    "zh": "我经常在办公室，但只待几个小时。",
    "pat": "系动词 + aber 转折",
    "flow": [["Ich", "我", "s"], ["bin", "在", "v"], ["oft", "经常", "a"], ["im Büro", "在办公室", "a"],
             ["aber nur für wenige Stunden", "但只待几个小时", "a"]],
    "kasus": [["im Büro", "Dativ"]],
    "final": [["我", "s"], ["经常", "a"], ["在办公室", "a"], ["，", "x"], ["但", "x"], ["只待几个小时", "a"], ["。", "x"]],
    "tip": "aber 连接转折。im Büro = in + dem（位置 Dativ）。",
},
"Hast du alles?": {
    "zh": "你都拿全了吗？",
    "pat": "haben · 疑问句",
    "flow": [["Hast", "有", "v"], ["du", "你", "s"], ["alles", "一切", "o"]],
    "kasus": [["du", "Nominativ"], ["alles", "Akkusativ"]],
    "final": [["你", "s"], ["都拿全了", "o"], ["吗？", "x"]],
    "tip": "alles 是不定代词，作 Akkusativ。",
},
"Hast du ein Bild von deinem Sohn?": {
    "zh": "你有一张你儿子的照片吗？",
    "pat": "haben · 介词定语",
    "flow": [["Hast", "有", "v"], ["du", "你", "s"], ["ein Bild", "一张照片", "o"],
             ["von deinem Sohn", "你儿子的", "d"]],
    "kasus": [["du", "Nominativ"], ["ein Bild", "Akkusativ"], ["deinem Sohn", "Dativ"]],
    "final": [["你", "s"], ["有", "v"], ["一张", "a"], ["你儿子的", "d"], ["照片", "o"], ["吗？", "x"]],
    "tip": "von + Dativ 作后置定语（照片是谁的）。中文提到照片前。",
},
"Hast du einen Kugelschreiber für mich?": {
    "zh": "你有笔可以借我吗？",
    "pat": "haben · 介词短语",
    "flow": [["Hast", "有", "v"], ["du", "你", "s"], ["einen Kugelschreiber", "一支圆珠笔", "o"],
             ["für mich", "给我", "a"]],
    "kasus": [["du", "Nominativ"], ["einen Kugelschreiber", "Akkusativ"]],
    "final": [["你", "s"], ["有", "v"], ["笔", "o"], ["可以借我吗", "a"], ["？", "x"]],
    "tip": "einen Kugelschreiber：阳性 Akkusativ。der Kugelschreiber = 圆珠笔。",
},
"Hast du etwas zu trinken? Ich habe großen Durst.": {
    "zh": "你有什么喝的吗？我很渴。",
    "pat": "haben + 并列句",
    "flow": [["Hast", "有", "v"], ["du", "你", "s"], ["etwas zu trinken", "喝的东西", "o"],
             ["Ich habe großen Durst", "我很渴", "c"]],
    "kasus": [["du", "Nominativ"], ["großen Durst", "Akkusativ"]],
    "final": [["你", "s"], ["有", "v"], ["什么喝的吗", "o"], ["？", "x"], ["我很渴", "c"], ["。", "x"]],
    "tip": "etwas zu trinken = 喝的东西。großen Durst haben = 非常渴。",
},
"Hast du noch Geld?": {
    "zh": "你还有钱吗？",
    "pat": "haben · 疑问句",
    "flow": [["Hast", "有", "v"], ["du", "你", "s"], ["noch", "还", "a"], ["Geld", "钱", "o"]],
    "kasus": [["du", "Nominativ"], ["Geld", "Akkusativ"]],
    "final": [["你", "s"], ["还有", "v"], ["钱", "o"], ["吗？", "x"]],
    "tip": "Hast du noch …? = 你还有……吗？",
},
"Haben Sie Feuer?": {
    "zh": "您有火吗？",
    "pat": "haben · 疑问句",
    "flow": [["Haben", "有", "v"], ["Sie", "您", "s"], ["Feuer", "火", "o"]],
    "kasus": [["Sie", "Nominativ"], ["Feuer", "Akkusativ"]],
    "final": [["您", "s"], ["有", "v"], ["火", "o"], ["吗？", "x"]],
    "tip": "借火用语。Feuer = 火。",
},
"Haben Sie Telefon?": {
    "zh": "您有电话吗？",
    "pat": "haben · 疑问句",
    "flow": [["Haben", "有", "v"], ["Sie", "您", "s"], ["Telefon", "电话", "o"]],
    "kasus": [["Sie", "Nominativ"], ["Telefon", "Akkusativ"]],
    "final": [["您", "s"], ["有", "v"], ["电话", "o"], ["吗？", "x"]],
    "tip": "询问对方是否有电话。",
},
"Haben Sie auch Weißbrot?": {
    "zh": "您也有白面包吗？",
    "pat": "haben · 疑问句",
    "flow": [["Haben", "有", "v"], ["Sie", "您", "s"], ["auch", "也", "a"], ["Weißbrot", "白面包", "o"]],
    "kasus": [["Sie", "Nominativ"], ["Weißbrot", "Akkusativ"]],
    "final": [["您", "s"], ["也", "a"], ["有", "v"], ["白面包", "o"], ["吗？", "x"]],
    "tip": "das Weißbrot = 白面包（面包店场景）。",
},
"Haben Sie das auch in Größe 40?": {
    "zh": "这个也有 40 码的吗？",
    "pat": "haben · 介词短语",
    "flow": [["Haben", "有", "v"], ["Sie", "您", "s"], ["das", "这个", "o"],
             ["auch in Größe 40", "也有 40 码", "a"]],
    "kasus": [["Sie", "Nominativ"], ["das", "Akkusativ"]],
    "final": [["这个", "o"], ["也有", "v"], ["40 码", "a"], ["的吗？", "x"]],
    "tip": "购物问尺码：in Größe 40 = 40 码。",
},
"Haben Sie einen Brief für mich?": {
    "zh": "您有我的一封信吗？",
    "pat": "haben · 介词短语",
    "flow": [["Haben", "有", "v"], ["Sie", "您", "s"], ["einen Brief", "一封信", "o"], ["für mich", "给我的", "d"]],
    "kasus": [["Sie", "Nominativ"], ["einen Brief", "Akkusativ"]],
    "final": [["您", "s"], ["有", "v"], ["一封", "a"], ["给我的", "d"], ["信", "o"], ["吗？", "x"]],
    "tip": "für + Akkusativ 作定语（给我的信）。",
},
"Haben Sie nicht das Schild gesehen?": {
    "zh": "您没看到那个牌子吗？",
    "pat": "Perfekt · 疑问句",
    "flow": [["Haben", "（助动词）", "v"], ["Sie", "您", "s"], ["nicht", "没有", "a"],
             ["das Schild", "那个牌子", "o"], ["gesehen", "看到", "v2"]],
    "kasus": [["Sie", "Nominativ"], ["das Schild", "Akkusativ"]],
    "final": [["您", "s"], ["没", "a"], ["看到", "v2"], ["那个牌子", "o"], ["吗？", "x"]],
    "tip": "Perfekt 疑问句：haben 提前。sehen → gesehen。",
},
"Haben Sie noch ein Einzelzimmer?": {
    "zh": "您还有单人间吗？",
    "pat": "haben · 疑问句",
    "flow": [["Haben", "有", "v"], ["Sie", "您", "s"], ["noch", "还", "a"],
             ["ein Einzelzimmer", "一个单人间", "o"]],
    "kasus": [["Sie", "Nominativ"], ["ein Einzelzimmer", "Akkusativ"]],
    "final": [["您", "s"], ["还有", "v"], ["单人间", "o"], ["吗？", "x"]],
    "tip": "das Einzelzimmer = 单人间（旅馆）。反义 Doppelzimmer。",
},
# ============================================================
# 十一、Ich nehme / Ich möchte / Ich wohne / Wir müssen / Er kommt / Ich muss
# ============================================================

"Ich nehme das da.": {
    "zh": "我拿那边那个。",
    "pat": "普通语序 · 宾语",
    "flow": [["Ich", "我", "s"], ["nehme", "拿", "v"], ["das da", "那边那个", "o"]],
    "kasus": [["Ich", "Nominativ"], ["das da", "Akkusativ"]],
    "final": [["我", "s"], ["拿", "v"], ["那边那个", "o"], ["。", "x"]],
    "tip": "das da = 那边的那个（指示）。购物选择时用。",
},
"Ich nehme den Bus.": {
    "zh": "我坐公交车。",
    "pat": "普通语序 · 宾语",
    "flow": [["Ich", "我", "s"], ["nehme", "乘", "v"], ["den Bus", "公交车", "o"]],
    "kasus": [["Ich", "Nominativ"], ["den Bus", "Akkusativ"]],
    "final": [["我", "s"], ["乘", "v"], ["公交车", "o"], ["。", "x"]],
    "tip": "nehmen + Akkusativ = 乘坐。der Bus → den Bus。",
},
"Ich nehme die nächste Bahn.": {
    "zh": "我乘下一班火车。",
    "pat": "普通语序 · 宾语",
    "flow": [["Ich", "我", "s"], ["nehme", "乘", "v"], ["die nächste Bahn", "下一班火车", "o"]],
    "kasus": [["Ich", "Nominativ"], ["die nächste Bahn", "Akkusativ"]],
    "final": [["我", "s"], ["乘", "v"], ["下一班火车", "o"], ["。", "x"]],
    "tip": "nehmen + Akkusativ = 乘坐。nächste = 下一个。",
},
"Ich nehme ein Bier. Willst du auch eins?": {
    "zh": "我要一杯啤酒。你也来一杯吗？",
    "pat": "并列句 · 情态疑问",
    "flow": [["Ich", "我", "s"], ["nehme", "要", "v"], ["ein Bier", "一杯啤酒", "o"],
             ["Willst du auch eins", "你也来一杯吗", "c"]],
    "kasus": [["Ich", "Nominativ"], ["ein Bier", "Akkusativ"]],
    "final": [["我", "s"], ["要", "v"], ["一杯啤酒", "o"], ["。", "x"], ["你也来一杯吗", "c"], ["？", "x"]],
    "tip": "ein Bier 中性。eins 指代 ein Bier（避免重复）。",
},
"Ich nehme ein Stück Kuchen.": {
    "zh": "我要一块蛋糕。",
    "pat": "普通语序 · 量词",
    "flow": [["Ich", "我", "s"], ["nehme", "要", "v"], ["ein Stück Kuchen", "一块蛋糕", "o"]],
    "kasus": [["Ich", "Nominativ"], ["ein Stück Kuchen", "Akkusativ"]],
    "final": [["我", "s"], ["要", "v"], ["一块蛋糕", "o"], ["。", "x"]],
    "tip": "ein Stück + 名词 = 一块……（量词）。",
},
"Ich nehme im September Urlaub.": {
    "zh": "我九月休假。",
    "pat": "普通语序 · 时间",
    "flow": [["Ich", "我", "s"], ["nehme", "请", "v"], ["im September", "在九月", "a"], ["Urlaub", "假", "o"]],
    "kasus": [["Ich", "Nominativ"], ["Urlaub", "Akkusativ"]],
    "final": [["我", "s"], ["九月", "a"], ["休假", "v"], ["。", "x"]],
    "tip": "Urlaub nehmen = 休假/请假。月份用 im。",
},
"Ich nehme lieber die S-Bahn.": {
    "zh": "我宁愿坐城市快铁。",
    "pat": "普通语序 · lieber",
    "flow": [["Ich", "我", "s"], ["nehme", "坐", "v"], ["lieber", "宁愿", "a"], ["die S-Bahn", "城市快铁", "o"]],
    "kasus": [["Ich", "Nominativ"], ["die S-Bahn", "Akkusativ"]],
    "final": [["我", "s"], ["宁愿", "a"], ["坐", "v"], ["城市快铁", "o"], ["。", "x"]],
    "tip": "lieber = 宁愿（gern 的比较级）。die S-Bahn = 城市快铁。",
},
"Ich nehme lieber diesen Kuchen.": {
    "zh": "我宁愿要这块蛋糕。",
    "pat": "普通语序 · lieber",
    "flow": [["Ich", "我", "s"], ["nehme", "要", "v"], ["lieber", "宁愿", "a"],
             ["diesen Kuchen", "这块蛋糕", "o"]],
    "kasus": [["Ich", "Nominativ"], ["diesen Kuchen", "Akkusativ"]],
    "final": [["我", "s"], ["宁愿", "a"], ["要", "v"], ["这块蛋糕", "o"], ["。", "x"]],
    "tip": "diesen Kuchen：阳性 Akkusativ。",
},
"Ich möchte auch etwas essen. Bringen Sie mir die Karte, bitte.": {
    "zh": "我还想再吃点东西。请把菜单拿给我。",
    "pat": "情态动词 + 祈使句",
    "flow": [["Ich", "我", "s"], ["möchte", "想", "v"], ["auch", "还", "a"], ["etwas essen", "吃点东西", "v2"],
             ["Bringen Sie mir die Karte, bitte", "请把菜单给我", "c"]],
    "kasus": [["Ich", "Nominativ"], ["mir", "Dativ"], ["die Karte", "Akkusativ"]],
    "final": [["我", "s"], ["还想", "v"], ["再吃点东西", "v2"], ["。", "x"], ["请把菜单拿给我", "c"], ["。", "x"]],
    "tip": "die Karte 此处 = 菜单。bringen + Dativ(给谁) + Akkusativ(东西)。",
},
"Ich möchte ein Auto mieten.": {
    "zh": "我想租一辆车。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Ich", "我", "s"], ["möchte", "想", "v"], ["ein Auto", "一辆车", "o"], ["mieten", "租", "v2"]],
    "klammer": ["Ich", "möchte", "ein Auto", "mieten", "modal"],
    "kasus": [["Ich", "Nominativ"], ["ein Auto", "Akkusativ"]],
    "final": [["我", "s"], ["想", "v"], ["租", "v2"], ["一辆车", "o"], ["。", "x"]],
    "tip": "mieten = 租（租房/租车）。",
},
"Ich möchte ein ruhiges Zimmer.": {
    "zh": "我想要一间安静的房间。",
    "pat": "情态动词 · 省略动词",
    "flow": [["Ich", "我", "s"], ["möchte", "想要", "v"], ["ein ruhiges Zimmer", "一间安静的房间", "o"]],
    "kasus": [["Ich", "Nominativ"], ["ein ruhiges Zimmer", "Akkusativ"]],
    "final": [["我", "s"], ["想要", "v"], ["一间安静的房间", "o"], ["。", "x"]],
    "tip": "旅馆用语：möchte + 名词 = 想要……。ruhig = 安静。",
},
"Ich möchte gern ein Schinkenbrot.": {
    "zh": "我想要一个火腿面包。",
    "pat": "情态动词 · 省略动词",
    "flow": [["Ich", "我", "s"], ["möchte gern", "很想要", "v"], ["ein Schinkenbrot", "一个火腿面包", "o"]],
    "kasus": [["Ich", "Nominativ"], ["ein Schinkenbrot", "Akkusativ"]],
    "final": [["我", "s"], ["很想要", "v"], ["一个火腿面包", "o"], ["。", "x"]],
    "tip": "das Schinkenbrot = 火腿面包（点餐）。",
},
"Ich möchte nicht Auto fahren, ich möchte laufen.": {
    "zh": "我不想开车，我想走路。",
    "pat": "情态动词 · 并列",
    "flow": [["Ich", "我", "s"], ["möchte", "想", "v"], ["nicht", "不", "a"], ["Auto fahren", "开车", "v2"],
             ["ich möchte laufen", "我想走路", "c"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["不想", "v"], ["开车", "v2"], ["，", "x"], ["我想走路", "c"], ["。", "x"]],
    "tip": "Auto fahren = 开车（固定搭配）。nicht 放动词第二部分前。",
},
"Ich möchte nur ein Glas Wasser.": {
    "zh": "我只想要一杯水。",
    "pat": "情态动词 · 省略动词",
    "flow": [["Ich", "我", "s"], ["möchte", "想要", "v"], ["nur", "只", "a"], ["ein Glas Wasser", "一杯水", "o"]],
    "kasus": [["Ich", "Nominativ"], ["ein Glas Wasser", "Akkusativ"]],
    "final": [["我", "s"], ["只", "a"], ["想要", "v"], ["一杯水", "o"], ["。", "x"]],
    "tip": "ein Glas + 名词 = 一杯……（量词）。",
},
"Ich wohne Messeplatz 5.": {
    "zh": "我住在会展广场 5 号。",
    "pat": "普通语序 · 地址",
    "flow": [["Ich", "我", "s"], ["wohne", "住", "v"], ["Messeplatz 5", "会展广场 5 号", "a"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["住在", "v"], ["会展广场 5 号", "a"], ["。", "x"]],
    "tip": "报地址省略介词：wohne + 街道门牌。",
},
"Ich wohne bei meinen Eltern.": {
    "zh": "我住在父母那里。",
    "pat": "普通语序 · 处所",
    "flow": [["Ich", "我", "s"], ["wohne", "住", "v"], ["bei meinen Eltern", "在父母那里", "a"]],
    "kasus": [["meinen Eltern", "Dativ"]],
    "final": [["我", "s"], ["住在父母那里", "v"], ["。", "x"]],
    "tip": "bei + Dativ = 在……那里（人）。meinen Eltern 复数 Dativ。",
},
"Ich wohne in München.": {
    "zh": "我住在慕尼黑。",
    "pat": "普通语序 · 处所",
    "flow": [["Ich", "我", "s"], ["wohne", "住", "v"], ["in München", "在慕尼黑", "a"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["住在", "v"], ["慕尼黑", "a"], ["。", "x"]],
    "tip": "in + 城市名。",
},
"Ich wohne in Wiesbaden.": {
    "zh": "我住在威斯巴登。",
    "pat": "普通语序 · 处所",
    "flow": [["Ich", "我", "s"], ["wohne", "住", "v"], ["in Wiesbaden", "在威斯巴登", "a"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["住在", "v"], ["威斯巴登", "a"], ["。", "x"]],
    "tip": "in + 城市名。",
},
"Ich wohne oben.": {
    "zh": "我住在楼上。",
    "pat": "普通语序 · 处所",
    "flow": [["Ich", "我", "s"], ["wohne", "住", "v"], ["oben", "楼上", "a"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["住在楼上", "v"], ["。", "x"]],
    "tip": "oben = 楼上（反义 unten 楼下）。",
},
"Ich wohne seit drei Jahren in Köln.": {
    "zh": "我在科隆住了三年了。",
    "pat": "普通语序 · seit",
    "flow": [["Ich", "我", "s"], ["wohne", "住", "v"], ["seit drei Jahren", "三年以来", "a"],
             ["in Köln", "在科隆", "a"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["在科隆", "a"], ["住了", "v"], ["三年了", "a"], ["。", "x"]],
    "tip": "seit + Dativ（从……起持续至今）。drei Jahren 复数 Dativ。",
},
"Wir müssen den Schlüssel finden.": {
    "zh": "我们必须找到钥匙。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Wir", "我们", "s"], ["müssen", "必须", "v"], ["den Schlüssel", "钥匙", "o"],
             ["finden", "找到", "v2"]],
    "klammer": ["Wir", "müssen", "den Schlüssel", "finden", "modal"],
    "kasus": [["Wir", "Nominativ"], ["den Schlüssel", "Akkusativ"]],
    "final": [["我们", "s"], ["必须", "v"], ["找到", "v2"], ["钥匙", "o"], ["。", "x"]],
    "tip": "müssen + 不定式。den Schlüssel（der → den）。",
},
"Wir müssen euch etwas erzählen!": {
    "zh": "我们必须告诉你们一些事！",
    "pat": "情态动词 · 双宾语",
    "flow": [["Wir", "我们", "s"], ["müssen", "必须", "v"], ["euch", "你们", "o"], ["etwas", "一些事", "o"],
             ["erzählen", "告诉", "v2"]],
    "klammer": ["Wir", "müssen", "euch etwas", "erzählen", "modal"],
    "kasus": [["Wir", "Nominativ"], ["euch", "Dativ"], ["etwas", "Akkusativ"]],
    "final": [["我们", "s"], ["必须", "v"], ["告诉你们", "o"], ["一些事", "o"], ["！", "x"]],
    "tip": "erzählen + Dativ(告诉谁) + Akkusativ(内容)。",
},
"Wir müssen ihn zum Arzt bringen.": {
    "zh": "我们必须带他去看医生。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Wir", "我们", "s"], ["müssen", "必须", "v"], ["ihn", "他", "o"], ["zum Arzt", "去看医生", "a"],
             ["bringen", "带", "v2"]],
    "klammer": ["Wir", "müssen", "ihn zum Arzt", "bringen", "modal"],
    "kasus": [["Wir", "Nominativ"], ["ihn", "Akkusativ"]],
    "final": [["我们", "s"], ["必须", "v"], ["带他", "o"], ["去看医生", "a"], ["。", "x"]],
    "tip": "bringen + Akkusativ(带谁) + zu(去哪里)。ihn = er 的 Akkusativ。",
},
"Wir müssen jetzt Schluss machen.": {
    "zh": "我们现在必须结束了。",
    "pat": "情态动词 · 固定搭配",
    "flow": [["Wir", "我们", "s"], ["müssen", "必须", "v"], ["jetzt", "现在", "a"],
             ["Schluss machen", "结束", "v2"]],
    "klammer": ["Wir", "müssen", "jetzt", "Schluss machen", "modal"],
    "kasus": [["Wir", "Nominativ"]],
    "final": [["我们", "s"], ["现在", "a"], ["必须", "v"], ["结束了", "v2"], ["。", "x"]],
    "tip": "Schluss machen = 结束（固定搭配）。",
},
"Wir müssen noch durch den Zoll.": {
    "zh": "我们还得过海关。",
    "pat": "情态动词 · 省略动词",
    "flow": [["Wir", "我们", "s"], ["müssen", "必须", "v"], ["noch", "还", "a"],
             ["durch den Zoll", "过海关", "a"]],
    "kasus": [["den Zoll", "Akkusativ"]],
    "final": [["我们", "s"], ["还得", "v"], ["过海关", "a"], ["。", "x"]],
    "tip": "müssen + 介词短语（省略 gehen）。der Zoll = 海关。",
},
"Wir müssen noch meinen Bruder abholen.": {
    "zh": "我们还必须去接我弟弟。",
    "pat": "情态动词 · 可分",
    "flow": [["Wir", "我们", "s"], ["müssen", "必须", "v"], ["noch", "还", "a"],
             ["meinen Bruder", "我弟弟", "o"], ["abholen", "去接", "v2"]],
    "klammer": ["Wir", "müssen", "noch meinen Bruder", "abholen", "modal"],
    "kasus": [["Wir", "Nominativ"], ["meinen Bruder", "Akkusativ"]],
    "final": [["我们", "s"], ["还必须", "v"], ["去接我弟弟", "v2"], ["。", "x"]],
    "tip": "abholen 可分（去接人）。meinen Bruder：阳性 Akkusativ。",
},
"Er kommt allein.": {
    "zh": "他独自来。",
    "pat": "普通语序 · 方式",
    "flow": [["Er", "他", "s"], ["kommt", "来", "v"], ["allein", "独自", "a"]],
    "kasus": [["Er", "Nominativ"]],
    "final": [["他", "s"], ["独自", "a"], ["来", "v"], ["。", "x"]],
    "tip": "allein = 独自。",
},
"Er kommt aus Brasilien.": {
    "zh": "他来自巴西。",
    "pat": "普通语序 · 来源",
    "flow": [["Er", "他", "s"], ["kommt", "来", "v"], ["aus Brasilien", "来自巴西", "a"]],
    "kasus": [["Er", "Nominativ"]],
    "final": [["他", "s"], ["来自", "v"], ["巴西", "a"], ["。", "x"]],
    "tip": "aus + 国名 = 来自（来源）。",
},
"Er kommt gerade von Köln/von zu Hause.": {
    "zh": "他刚从科隆/从家里来。",
    "pat": "普通语序 · 来源",
    "flow": [["Er", "他", "s"], ["kommt", "来", "v"], ["gerade", "刚刚", "a"],
             ["von Köln/von zu Hause", "从科隆/从家", "a"]],
    "kasus": [["Er", "Nominativ"]],
    "final": [["他", "s"], ["刚刚", "a"], ["从科隆/从家来", "v"], ["。", "x"]],
    "tip": "von + 地点 = 从……来。gerade = 刚刚。",
},
"Er kommt mit dem Auto.": {
    "zh": "他开车来。",
    "pat": "普通语序 · 方式",
    "flow": [["Er", "他", "s"], ["kommt", "来", "v"], ["mit dem Auto", "开车", "a"]],
    "kasus": [["dem Auto", "Dativ"]],
    "final": [["他", "s"], ["开车", "a"], ["来", "v"], ["。", "x"]],
    "tip": "mit + Dativ = 乘坐/使用工具。",
},
"Er kommt nie pünktlich.": {
    "zh": "他从不准时来。",
    "pat": "普通语序 · 方式",
    "flow": [["Er", "他", "s"], ["kommt", "来", "v"], ["nie", "从不", "a"], ["pünktlich", "准时", "a"]],
    "kasus": [["Er", "Nominativ"]],
    "final": [["他", "s"], ["从", "a"], ["不准时来", "v"], ["。", "x"]],
    "tip": "nie = 从不（否定频率）。pünktlich = 准时。",
},
"Er kommt um sieben Uhr.": {
    "zh": "他七点来。",
    "pat": "普通语序 · 时间",
    "flow": [["Er", "他", "s"], ["kommt", "来", "v"], ["um sieben Uhr", "在七点", "a"]],
    "kasus": [["Er", "Nominativ"]],
    "final": [["他", "s"], ["七点", "a"], ["来", "v"], ["。", "x"]],
    "tip": "时间点用 um。",
},
"Ich muss jeden Tag von 8 Uhr bis 18 Uhr arbeiten.": {
    "zh": "我必须每天从 8 点工作到 18 点。",
    "pat": "情态动词 · 时间范围",
    "flow": [["Ich", "我", "s"], ["muss", "必须", "v"], ["jeden Tag", "每天", "a"],
             ["von 8 Uhr bis 18 Uhr", "从 8 点到 18 点", "a"], ["arbeiten", "工作", "v2"]],
    "klammer": ["Ich", "muss", "jeden Tag von 8 Uhr bis 18 Uhr", "arbeiten", "modal"],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["必须", "v"], ["每天", "a"], ["从 8 点工作到 18 点", "a"], ["。", "x"]],
    "tip": "von … bis … = 从……到……（时间段）。",
},
"Ich muss jetzt Schluss machen.": {
    "zh": "我现在必须结束了。",
    "pat": "情态动词 · 固定搭配",
    "flow": [["Ich", "我", "s"], ["muss", "必须", "v"], ["jetzt", "现在", "a"],
             ["Schluss machen", "结束", "v2"]],
    "klammer": ["Ich", "muss", "jetzt", "Schluss machen", "modal"],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["现在", "a"], ["必须", "v"], ["结束了", "v2"], ["。", "x"]],
    "tip": "Schluss machen = 结束。",
},
"Ich muss morgen waschen.": {
    "zh": "我明天得洗衣服。",
    "pat": "情态动词 · 省略宾语",
    "flow": [["Ich", "我", "s"], ["muss", "得", "v"], ["morgen", "明天", "a"], ["waschen", "洗衣服", "v2"]],
    "klammer": ["Ich", "muss", "morgen", "waschen", "modal"],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["明天", "a"], ["得", "v"], ["洗衣服", "v2"], ["。", "x"]],
    "tip": "waschen（洗衣）省略宾语 Wäsche。",
},
"Ich muss noch schnell zur Post, dann komme ich.": {
    "zh": "我还得赶快去趟邮局，然后我就来。",
    "pat": "情态动词 + 并列句",
    "flow": [["Ich", "我", "s"], ["muss", "得", "v"], ["noch schnell", "还赶快", "a"],
             ["zur Post", "去邮局", "a"], ["dann komme ich", "然后我就来", "c"]],
    "kasus": [["zur Post", "Dativ"]],
    "final": [["我", "s"], ["还得", "v"], ["赶快", "a"], ["去趟邮局", "a"], ["，", "x"],
              ["然后", "a"], ["我就来", "c"], ["。", "x"]],
    "tip": "逗号后 dann komme ich 是第二分句，动词照旧第二位。zur Post = zu + der。",
},
"Ich muss zum Arzt. Mein Bein tut weh.": {
    "zh": "我得去看医生。我的腿疼。",
    "pat": "情态动词 + 并列句",
    "flow": [["Ich", "我", "s"], ["muss", "得", "v"], ["zum Arzt", "去看医生", "a"],
             ["Mein Bein tut weh", "我的腿疼", "c"]],
    "kasus": [["Mein Bein", "Nominativ"]],
    "final": [["我", "s"], ["得", "v"], ["去看医生", "a"], ["。", "x"], ["我的腿疼", "c"], ["。", "x"]],
    "tip": "muss + 方向（省略 gehen）。weh tun = 疼。",
},
# ============================================================
# 十二、Ich habe / Wir haben / Ist das / Kannst du / Ich gehe / Ich komme
# ============================================================

"Ich habe Hunger! Wann ist das Essen fertig?": {
    "zh": "我饿了！饭什么时候好？",
    "pat": "haben + 疑问句",
    "flow": [["Ich", "我", "s"], ["habe", "有", "v"], ["Hunger", "饿", "o"],
             ["Wann ist das Essen fertig", "饭什么时候好", "c"]],
    "kasus": [["Ich", "Nominativ"], ["Hunger", "Akkusativ"]],
    "final": [["我", "s"], ["饿了", "v"], ["！", "x"], ["饭什么时候好", "c"], ["？", "x"]],
    "tip": "Hunger haben = 饿了（字面「有饿」）。",
},
"Ich habe das Lied schon mal gehört.": {
    "zh": "这首歌我以前听过。",
    "pat": "Perfekt · haben + Partizip",
    "flow": [["Ich", "我", "s"], ["habe", "（助动词）", "v"], ["das Lied", "这首歌", "o"],
             ["schon mal", "已经…过", "a"], ["gehört", "听", "v2"]],
    "klammer": ["Ich", "habe", "das Lied schon mal", "gehört", "perfekt"],
    "kasus": [["Ich", "Nominativ"], ["das Lied", "Akkusativ"]],
    "final": [["我", "s"], ["以前", "a"], ["听过", "v2"], ["这首歌", "o"], ["。", "x"]],
    "tip": "schon mal = 曾经（已经一次）。hören → gehört。",
},
"Ich habe die Schlüssel in der Tasche.": {
    "zh": "钥匙在我口袋里。",
    "pat": "普通语序 · 处所",
    "flow": [["Ich", "我", "s"], ["habe", "有", "v"], ["die Schlüssel", "钥匙", "o"],
             ["in der Tasche", "在口袋里", "a"]],
    "kasus": [["Ich", "Nominativ"], ["die Schlüssel", "Akkusativ"], ["der Tasche", "Dativ"]],
    "final": [["钥匙", "s"], ["在我口袋里", "v"], ["。", "x"]],
    "tip": "in + Dativ（位置）。中文把宾语提前作主语更自然。",
},
"Ich habe diesen Jungen schon einmal gesehen.": {
    "zh": "这个男孩我以前见过一次。",
    "pat": "Perfekt · haben + Partizip",
    "flow": [["Ich", "我", "s"], ["habe", "（助动词）", "v"], ["diesen Jungen", "这个男孩", "o"],
             ["schon einmal", "已经一次", "a"], ["gesehen", "见过", "v2"]],
    "klammer": ["Ich", "habe", "diesen Jungen schon einmal", "gesehen", "perfekt"],
    "kasus": [["Ich", "Nominativ"], ["diesen Jungen", "Akkusativ"]],
    "final": [["我", "s"], ["以前", "a"], ["见过", "v2"], ["这个男孩", "o"], ["一次", "a"], ["。", "x"]],
    "tip": "sehen → gesehen。der Junge 弱变化，Akkusativ 仍是 diesen Jungen。",
},
"Ich habe ein Zimmer bestellt.": {
    "zh": "我订了一个房间。",
    "pat": "Perfekt · haben + Partizip",
    "flow": [["Ich", "我", "s"], ["habe", "（助动词）", "v"], ["ein Zimmer", "一个房间", "o"],
             ["bestellt", "订", "v2"]],
    "klammer": ["Ich", "habe", "ein Zimmer", "bestellt", "perfekt"],
    "kasus": [["Ich", "Nominativ"], ["ein Zimmer", "Akkusativ"]],
    "final": [["我", "s"], ["订了", "v2"], ["一个房间", "o"], ["。", "x"]],
    "tip": "bestellen = 预订。旅馆场景。",
},
"Ich habe ein neues Auto.": {
    "zh": "我有一辆新车。",
    "pat": "普通语序 · haben",
    "flow": [["Ich", "我", "s"], ["habe", "有", "v"], ["ein neues Auto", "一辆新车", "o"]],
    "kasus": [["Ich", "Nominativ"], ["ein neues Auto", "Akkusativ"]],
    "final": [["我", "s"], ["有", "v"], ["一辆新车", "o"], ["。", "x"]],
    "tip": "ein neues Auto：中性 Akkusativ + 形容词变格。",
},
"Ich habe leider nur wenig verstanden.": {
    "zh": "可惜我懂的很少。",
    "pat": "Perfekt · haben + Partizip",
    "flow": [["Ich", "我", "s"], ["habe", "（助动词）", "v"], ["leider", "可惜", "a"],
             ["nur wenig", "只很少", "a"], ["verstanden", "听懂", "v2"]],
    "klammer": ["Ich", "habe", "leider nur wenig", "verstanden", "perfekt"],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["可惜", "a"], ["我", "s"], ["只", "a"], ["听懂很少", "v2"], ["。", "x"]],
    "tip": "verstehen → verstanden。nur wenig = 只很少。",
},
"Ich habe noch 20 Euro.": {
    "zh": "我还有 20 欧元。",
    "pat": "普通语序 · haben",
    "flow": [["Ich", "我", "s"], ["habe", "有", "v"], ["noch", "还", "a"], ["20 Euro", "20 欧元", "o"]],
    "kasus": [["Ich", "Nominativ"], ["20 Euro", "Akkusativ"]],
    "final": [["我", "s"], ["还有", "v"], ["20 欧元", "o"], ["。", "x"]],
    "tip": "数字 + Euro。",
},
"Ich habe noch eine Bitte.": {
    "zh": "我还有一个请求。",
    "pat": "普通语序 · haben",
    "flow": [["Ich", "我", "s"], ["habe", "有", "v"], ["noch", "还", "a"], ["eine Bitte", "一个请求", "o"]],
    "kasus": [["Ich", "Nominativ"], ["eine Bitte", "Akkusativ"]],
    "final": [["我", "s"], ["还有", "v"], ["一个请求", "o"], ["。", "x"]],
    "tip": "eine Bitte haben = 有个请求，礼貌提要求。",
},
"Ich habe noch etwas zu tun.": {
    "zh": "我还有事要做。",
    "pat": "普通语序 · zu 不定式",
    "flow": [["Ich", "我", "s"], ["habe", "有", "v"], ["noch etwas", "还有一些事", "o"],
             ["zu tun", "要做", "d"]],
    "kasus": [["Ich", "Nominativ"], ["etwas", "Akkusativ"]],
    "final": [["我", "s"], ["还有", "v"], ["一些事", "o"], ["要做", "d"], ["。", "x"]],
    "tip": "etwas zu tun = 要做的事（zu 不定式作定语）。",
},
"Ich habe zwei Kinder. Einen Jungen und ein Mädchen.": {
    "zh": "我有两个孩子：一个男孩和一个女孩。",
    "pat": "haben + 补充说明",
    "flow": [["Ich", "我", "s"], ["habe", "有", "v"], ["zwei Kinder", "两个孩子", "o"],
             ["Einen Jungen und ein Mädchen", "一个男孩和一个女孩", "o"]],
    "kasus": [["Ich", "Nominativ"], ["zwei Kinder", "Akkusativ"]],
    "final": [["我", "s"], ["有", "v"], ["两个孩子", "o"], ["：", "x"], ["一个男孩和一个女孩", "o"], ["。", "x"]],
    "tip": "Einen Jungen：阳性 Akkusativ。补充说明家庭成员。",
},
"Wir haben Unterricht von 8.00 bis 12.00 Uhr.": {
    "zh": "我们 8 点到 12 点有课。",
    "pat": "普通语序 · 时间范围",
    "flow": [["Wir", "我们", "s"], ["haben", "有", "v"], ["Unterricht", "课", "o"],
             ["von 8.00 bis 12.00 Uhr", "从 8 点到 12 点", "a"]],
    "kasus": [["Wir", "Nominativ"], ["Unterricht", "Akkusativ"]],
    "final": [["我们", "s"], ["8 点到 12 点", "a"], ["有课", "v"], ["。", "x"]],
    "tip": "Unterricht haben = 上课。von … bis = 从……到。",
},
"Wir haben eine neue Chefin.": {
    "zh": "我们有一位新女上司。",
    "pat": "普通语序 · haben",
    "flow": [["Wir", "我们", "s"], ["haben", "有", "v"], ["eine neue Chefin", "一位新女上司", "o"]],
    "kasus": [["Wir", "Nominativ"], ["eine neue Chefin", "Akkusativ"]],
    "final": [["我们", "s"], ["有", "v"], ["一位新女上司", "o"], ["。", "x"]],
    "tip": "der Chef → die Chefin（上司/女上司）。",
},
"Wir haben hier wichtige Informationen für Sie.": {
    "zh": "我们这里有一些重要的信息要给您。",
    "pat": "普通语序 · 双状语",
    "flow": [["Wir", "我们", "s"], ["haben", "有", "v"], ["hier", "这里", "a"],
             ["wichtige Informationen", "重要的信息", "o"], ["für Sie", "给您的", "d"]],
    "kasus": [["Wir", "Nominativ"], ["wichtige Informationen", "Akkusativ"]],
    "final": [["我们这里", "a"], ["有", "v"], ["一些", "a"], ["给您的", "d"], ["重要信息", "o"], ["。", "x"]],
    "tip": "für Sie 作定语（给您的信息）。",
},
"Wir haben kein großes Bad.": {
    "zh": "我们没有大的浴室。",
    "pat": "普通语序 · kein",
    "flow": [["Wir", "我们", "s"], ["haben", "有", "v"], ["kein großes Bad", "没有大浴室", "o"]],
    "kasus": [["Wir", "Nominativ"], ["kein großes Bad", "Akkusativ"]],
    "final": [["我们", "s"], ["没有", "v"], ["大浴室", "o"], ["。", "x"]],
    "tip": "kein großes Bad：中性 Akkusativ + 形容词变格。das Bad = 浴室。",
},
"Wir haben leider keinen Garten.": {
    "zh": "可惜我们没有花园。",
    "pat": "普通语序 · kein",
    "flow": [["Wir", "我们", "s"], ["haben", "有", "v"], ["leider", "可惜", "a"],
             ["keinen Garten", "没有花园", "o"]],
    "kasus": [["Wir", "Nominativ"], ["keinen Garten", "Akkusativ"]],
    "final": [["可惜", "a"], ["我们", "s"], ["没有", "v"], ["花园", "o"], ["。", "x"]],
    "tip": "keinen Garten：阳性 Akkusativ 的 kein。",
},
"Wir haben schlechtes Wetter.": {
    "zh": "天气不好。",
    "pat": "普通语序 · haben",
    "flow": [["Wir", "我们", "s"], ["haben", "有", "v"], ["schlechtes Wetter", "坏天气", "o"]],
    "kasus": [["Wir", "Nominativ"], ["schlechtes Wetter", "Akkusativ"]],
    "final": [["天气", "s"], ["不好", "v"], ["。", "x"]],
    "tip": "schlechtes Wetter haben = 天气不好（字面「有坏天气」）。",
},
"Ist das Essen schon fertig?": {
    "zh": "饭做好了吗？",
    "pat": "疑问句 · 状态",
    "flow": [["Ist", "是", "v"], ["das Essen", "饭", "s"], ["schon", "已经", "a"], ["fertig", "好", "x"]],
    "kasus": [["das Essen", "Nominativ"]],
    "final": [["饭", "s"], ["已经", "a"], ["做好", "v"], ["了吗？", "x"]],
    "tip": "fertig = 完成/做好。Ist … schon …? = ……已经……了吗？",
},
"Ist das Ihr Koffer?": {
    "zh": "这是您的行李箱吗？",
    "pat": "疑问句 · 判断",
    "flow": [["Ist", "是", "v"], ["das", "这", "s"], ["Ihr Koffer", "您的行李箱", "x"]],
    "kasus": [["Ihr Koffer", "Nominativ"]],
    "final": [["这", "s"], ["是", "v"], ["您的行李箱", "x"], ["吗？", "x"]],
    "tip": "der Koffer = 行李箱。Ist das …? 确认归属。",
},
"Ist das dein Auto?": {
    "zh": "这是你的车吗？",
    "pat": "疑问句 · 判断",
    "flow": [["Ist", "是", "v"], ["das", "这", "s"], ["dein Auto", "你的车", "x"]],
    "kasus": [["dein Auto", "Nominativ"]],
    "final": [["这", "s"], ["是", "v"], ["你的车", "x"], ["吗？", "x"]],
    "tip": "dein Auto：中性物主冠词。",
},
"Ist das deins?": {
    "zh": "这是你的吗？",
    "pat": "疑问句 · 物主代词",
    "flow": [["Ist", "是", "v"], ["das", "这", "s"], ["deins", "你的", "x"]],
    "final": [["这", "s"], ["是", "v"], ["你的", "x"], ["吗？", "x"]],
    "tip": "deins = 你的（物主代词独立形式，指代中性名词）。",
},
"Ist das die Anmeldung für einen Telefonanschluss?": {
    "zh": "这是电话安装的申请表吗？",
    "pat": "疑问句 · 介词定语",
    "flow": [["Ist", "是", "v"], ["das", "这", "s"], ["die Anmeldung", "申请表", "x"],
             ["für einen Telefonanschluss", "电话安装的", "d"]],
    "kasus": [["die Anmeldung", "Nominativ"], ["einen Telefonanschluss", "Akkusativ"]],
    "final": [["这", "s"], ["是", "v"], ["电话安装", "d"], ["的申请表", "x"], ["吗？", "x"]],
    "tip": "für 短语作定语。die Anmeldung = 登记/申请表。",
},
"Kannst du mich zum Flughafen bringen?": {
    "zh": "你能送我去机场吗？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Kannst", "能", "v"], ["du", "你", "s"], ["mich", "我", "o"], ["zum Flughafen", "去机场", "a"],
             ["bringen", "送", "v2"]],
    "klammer": ["du", "Kannst", "mich zum Flughafen", "bringen", "modal"],
    "kasus": [["du", "Nominativ"], ["mich", "Akkusativ"]],
    "final": [["你", "s"], ["能", "v"], ["送我去机场", "v2"], ["吗？", "x"]],
    "tip": "bringen + Akkusativ(送谁) + zu(去何处)。",
},
"Kannst du mir bei den Hausaufgaben helfen?": {
    "zh": "你能帮我做作业吗？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Kannst", "能", "v"], ["du", "你", "s"], ["mir", "我", "o"], ["bei den Hausaufgaben", "做作业", "a"],
             ["helfen", "帮", "v2"]],
    "klammer": ["du", "Kannst", "mir bei den Hausaufgaben", "helfen", "modal"],
    "kasus": [["du", "Nominativ"], ["mir", "Dativ"]],
    "final": [["你", "s"], ["能", "v"], ["帮我做作业", "v2"], ["吗？", "x"]],
    "tip": "helfen bei + Dativ = 在某事上帮忙。mir 是 Dativ。",
},
"Kannst du mir bitte deinen Kugelschreiber geben?": {
    "zh": "你能把你的圆珠笔借给我吗？",
    "pat": "情态动词 · 双宾语",
    "flow": [["Kannst", "能", "v"], ["du", "你", "s"], ["mir", "给我", "o"], ["bitte", "请", "a"],
             ["deinen Kugelschreiber", "你的圆珠笔", "o"], ["geben", "借给", "v2"]],
    "klammer": ["du", "Kannst", "mir bitte deinen Kugelschreiber", "geben", "modal"],
    "kasus": [["du", "Nominativ"], ["mir", "Dativ"], ["deinen Kugelschreiber", "Akkusativ"]],
    "final": [["你", "s"], ["能", "v"], ["把圆珠笔", "o"], ["借给我", "o"], ["吗？", "x"]],
    "tip": "mir（Dativ 借给谁）+ deinen Kugelschreiber（Akkusativ 借什么）。",
},
"Kannst du mir das erklären?": {
    "zh": "你能给我解释一下吗？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Kannst", "能", "v"], ["du", "你", "s"], ["mir", "给我", "o"], ["das", "这个", "o"],
             ["erklären", "解释", "v2"]],
    "klammer": ["du", "Kannst", "mir das", "erklären", "modal"],
    "kasus": [["du", "Nominativ"], ["mir", "Dativ"], ["das", "Akkusativ"]],
    "final": [["你", "s"], ["能", "v"], ["给我解释一下", "v2"], ["吗？", "x"]],
    "tip": "erklären + Dativ(给谁) + Akkusativ(什么)。",
},
"Kannst du mir ein Beispiel sagen?": {
    "zh": "你能给我举个例子吗？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Kannst", "能", "v"], ["du", "你", "s"], ["mir", "给我", "o"], ["ein Beispiel", "一个例子", "o"],
             ["sagen", "说", "v2"]],
    "klammer": ["du", "Kannst", "mir ein Beispiel", "sagen", "modal"],
    "kasus": [["du", "Nominativ"], ["mir", "Dativ"], ["ein Beispiel", "Akkusativ"]],
    "final": [["你", "s"], ["能", "v"], ["给我举个例子", "v2"], ["吗？", "x"]],
    "tip": "ein Beispiel sagen = 举个例子。",
},
"Ich gehe einkaufen. Soll ich dir was mitbringen?": {
    "zh": "我去买东西。要我带点什么给你吗？",
    "pat": "并列句 · 情态疑问",
    "flow": [["Ich", "我", "s"], ["gehe", "去", "v"], ["einkaufen", "买东西", "v2"],
             ["Soll ich dir was mitbringen", "要我带点什么给你吗", "c"]],
    "kasus": [["Ich", "Nominativ"], ["dir", "Dativ"]],
    "final": [["我", "s"], ["去", "v"], ["买东西", "v2"], ["。", "x"], ["要我带点什么给你吗", "c"], ["？", "x"]],
    "tip": "einkaufen gehen = 去购物。mitbringen + Dativ(带给谁) + Akkusativ。",
},
"Ich gehe gerne einkaufen.": {
    "zh": "我喜欢去购物。",
    "pat": "普通语序 · gehen + 不定式",
    "flow": [["Ich", "我", "s"], ["gehe", "去", "v"], ["gerne", "喜欢", "a"], ["einkaufen", "购物", "v2"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["喜欢", "a"], ["去购物", "v"], ["。", "x"]],
    "tip": "gehen + 不定式（einkaufen gehen = 去购物）。",
},
"Ich gehe ins Kino. Kommst du mit?": {
    "zh": "我去电影院。你一起来吗？",
    "pat": "并列句 · 可分动词疑问",
    "flow": [["Ich", "我", "s"], ["gehe", "去", "v"], ["ins Kino", "去电影院", "a"],
             ["Kommst du mit", "你一起来吗", "c"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["去电影院", "v"], ["。", "x"], ["你一起来吗", "c"], ["？", "x"]],
    "tip": "ins = in + das。mitkommen 可分，mit 在句末。",
},
"Ich gehe jetzt nach Hause.": {
    "zh": "我现在回家。",
    "pat": "普通语序 · 方向",
    "flow": [["Ich", "我", "s"], ["gehe", "去", "v"], ["jetzt", "现在", "a"], ["nach Hause", "回家", "a"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["现在", "a"], ["回家", "v"], ["。", "x"]],
    "tip": "nach Hause = 回家（方向）。zu Hause = 在家（位置）。",
},
"Ich gehe zu Fuß.": {
    "zh": "我步行去。",
    "pat": "普通语序 · 方式",
    "flow": [["Ich", "我", "s"], ["gehe", "去", "v"], ["zu Fuß", "步行", "a"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["步行去", "v"], ["。", "x"]],
    "tip": "zu Fuß = 步行（固定搭配）。",
},
"Ich komme aus der Schweiz. Das ist meine Heimat.": {
    "zh": "我来自瑞士，那是我的家乡。",
    "pat": "并列句 · 来源",
    "flow": [["Ich", "我", "s"], ["komme", "来", "v"], ["aus der Schweiz", "来自瑞士", "a"],
             ["Das ist meine Heimat", "那是我的家乡", "c"]],
    "kasus": [["Ich", "Nominativ"], ["der Schweiz", "Dativ"]],
    "final": [["我", "s"], ["来自瑞士", "v"], ["，", "x"], ["那是我的家乡", "c"], ["。", "x"]],
    "tip": "aus + 国名（die Schweiz 带冠词 → 用 Dativ）。",
},
"Ich komme bald.": {
    "zh": "我很快就来。",
    "pat": "普通语序 · 时间",
    "flow": [["Ich", "我", "s"], ["komme", "来", "v"], ["bald", "很快", "a"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["很快就来", "v"], ["。", "x"]],
    "tip": "bald = 很快/不久。",
},
"Ich komme gleich.": {
    "zh": "我马上来。",
    "pat": "普通语序 · 时间",
    "flow": [["Ich", "我", "s"], ["komme", "来", "v"], ["gleich", "马上", "a"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["马上来", "v"], ["。", "x"]],
    "tip": "gleich = 马上/一会儿。",
},
"Ich komme um 13 Uhr. – Gut!": {
    "zh": "我 13 点到。——好的！",
    "pat": "普通语序 · 时间",
    "flow": [["Ich", "我", "s"], ["komme", "到", "v"], ["um 13 Uhr", "在 13 点", "a"], ["Gut", "好的", "x"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["13 点", "a"], ["到", "v"], ["。", "x"], ["好的", "x"], ["！", "x"]],
    "tip": "um + 具体时间。Gut! 表示同意。",
},
"Ich komme vielleicht mit dem Bus.": {
    "zh": "我可能坐公交车来。",
    "pat": "普通语序 · 方式",
    "flow": [["Ich", "我", "s"], ["komme", "来", "v"], ["vielleicht", "可能", "a"],
             ["mit dem Bus", "坐公交", "a"]],
    "kasus": [["dem Bus", "Dativ"]],
    "final": [["我", "s"], ["可能", "a"], ["坐公交", "a"], ["来", "v"], ["。", "x"]],
    "tip": "vielleicht = 可能。mit + Dativ（工具）。",
},
# ============================================================
# 十三、Ich kann / Können Sie / Möchtest du / Wie lange / Hier ist / Das macht
# ============================================================

"Ich kann Deutsch und Russisch.": {
    "zh": "我会说德语和俄语。",
    "pat": "情态动词 · 省略动词",
    "flow": [["Ich", "我", "s"], ["kann", "会", "v"], ["Deutsch und Russisch", "德语和俄语", "o"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["会", "v"], ["德语和俄语", "o"], ["。", "x"]],
    "tip": "kann + 语言 = 会说某种语言（省略 sprechen）。",
},
"Ich kann dich nicht sehen.": {
    "zh": "我看不见你。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Ich", "我", "s"], ["kann", "能", "v"], ["dich", "你", "o"], ["nicht", "不", "a"],
             ["sehen", "看见", "v2"]],
    "klammer": ["Ich", "kann", "dich nicht", "sehen", "modal"],
    "kasus": [["Ich", "Nominativ"], ["dich", "Akkusativ"]],
    "final": [["我", "s"], ["看不见", "v"], ["你", "o"], ["。", "x"]],
    "tip": "nicht 放在动词第二部分前。dich = du 的 Akkusativ。",
},
"Ich kann heute nicht zur Arbeit kommen, ich bin krank und liege im Bett.": {
    "zh": "我今天不能来上班了，我生病躺在床上。",
    "pat": "情态动词 + 并列句",
    "flow": [["Ich", "我", "s"], ["kann", "能", "v"], ["heute", "今天", "a"], ["nicht", "不", "a"],
             ["zur Arbeit", "去上班", "a"], ["kommen", "来", "v2"],
             ["ich bin krank und liege im Bett", "我生病躺在床上", "c"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我今天", "a"], ["不能", "v"], ["来上班", "v2"], ["了，", "x"], ["我生病躺在床上", "c"], ["。", "x"]],
    "tip": "nicht 放 kommen 之前。逗号后是并列分句。",
},
"Können Sie ein paar Minuten warten?": {
    "zh": "您能等几分钟吗？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Können", "能", "v"], ["Sie", "您", "s"], ["ein paar Minuten", "几分钟", "a"],
             ["warten", "等", "v2"]],
    "klammer": ["Sie", "Können", "ein paar Minuten", "warten", "modal"],
    "kasus": [["Sie", "Nominativ"]],
    "final": [["您", "s"], ["能", "v"], ["等", "v2"], ["几分钟", "a"], ["吗？", "x"]],
    "tip": "ein paar = 几个。礼貌请求等待。",
},
"Können Sie mich verstehen?": {
    "zh": "您能听懂我吗？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Können", "能", "v"], ["Sie", "您", "s"], ["mich", "我", "o"], ["verstehen", "听懂", "v2"]],
    "klammer": ["Sie", "Können", "mich", "verstehen", "modal"],
    "kasus": [["Sie", "Nominativ"], ["mich", "Akkusativ"]],
    "final": [["您", "s"], ["能", "v"], ["听懂我", "v2"], ["吗？", "x"]],
    "tip": "verstehen + Akkusativ（听懂谁）。",
},
"Können Sie mir Ihre Nummer geben?": {
    "zh": "您能把您的号码给我吗？",
    "pat": "情态动词 · 双宾语",
    "flow": [["Können", "能", "v"], ["Sie", "您", "s"], ["mir", "给我", "o"], ["Ihre Nummer", "您的号码", "o"],
             ["geben", "给", "v2"]],
    "klammer": ["Sie", "Können", "mir Ihre Nummer", "geben", "modal"],
    "kasus": [["Sie", "Nominativ"], ["mir", "Dativ"], ["Ihre Nummer", "Akkusativ"]],
    "final": [["您", "s"], ["能", "v"], ["把号码", "o"], ["给我", "o"], ["吗？", "x"]],
    "tip": "mir（Dativ 给谁）+ Ihre Nummer（Akkusativ 给什么）。",
},
"Können Sie mir helfen, bitte?": {
    "zh": "您能帮我一下吗？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Können", "能", "v"], ["Sie", "您", "s"], ["mir", "我", "o"], ["helfen", "帮", "v2"],
             ["bitte", "请", "a"]],
    "klammer": ["Sie", "Können", "mir bitte", "helfen", "modal"],
    "kasus": [["Sie", "Nominativ"], ["mir", "Dativ"]],
    "final": [["您", "s"], ["能", "v"], ["帮我", "o"], ["一下", "a"], ["吗？", "x"]],
    "tip": "helfen + Dativ。mir 是 Dativ（帮谁）。",
},
"Möchtest du Brötchen zum Frühstück?": {
    "zh": "你早餐要小面包吗？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Möchtest", "想要", "v"], ["du", "你", "s"], ["Brötchen", "小面包", "o"],
             ["zum Frühstück", "作为早餐", "a"]],
    "kasus": [["du", "Nominativ"], ["Brötchen", "Akkusativ"]],
    "final": [["你", "s"], ["早餐", "a"], ["要", "v"], ["小面包", "o"], ["吗？", "x"]],
    "tip": "zum Frühstück = 作为早餐。das Brötchen 复数。",
},
"Möchtest du ein Ei zum Frühstück?": {
    "zh": "你早餐要一个鸡蛋吗？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Möchtest", "想要", "v"], ["du", "你", "s"], ["ein Ei", "一个鸡蛋", "o"],
             ["zum Frühstück", "作为早餐", "a"]],
    "kasus": [["du", "Nominativ"], ["ein Ei", "Akkusativ"]],
    "final": [["你", "s"], ["早餐", "a"], ["要", "v"], ["一个鸡蛋", "o"], ["吗？", "x"]],
    "tip": "das Ei = 鸡蛋。",
},
"Möchtest du einen Apfelsaft?": {
    "zh": "你要一杯苹果汁吗？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Möchtest", "想要", "v"], ["du", "你", "s"], ["einen Apfelsaft", "一杯苹果汁", "o"]],
    "kasus": [["du", "Nominativ"], ["einen Apfelsaft", "Akkusativ"]],
    "final": [["你", "s"], ["要", "v"], ["一杯苹果汁", "o"], ["吗？", "x"]],
    "tip": "einen Apfelsaft：阳性 Akkusativ。der Apfelsaft = 苹果汁。",
},
"Möchtest du etwas trinken?": {
    "zh": "你想喝点什么吗？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Möchtest", "想", "v"], ["du", "你", "s"], ["etwas", "点什么", "o"], ["trinken", "喝", "v2"]],
    "klammer": ["du", "Möchtest", "etwas", "trinken", "modal"],
    "kasus": [["du", "Nominativ"], ["etwas", "Akkusativ"]],
    "final": [["你", "s"], ["想", "v"], ["喝点什么", "v2"], ["吗？", "x"]],
    "tip": "möchtest 是 du 的形式。招待用语。",
},
"Wie lange bist du schon hier?": {
    "zh": "你在这里多久了？",
    "pat": "疑问词 · 时长",
    "flow": [["Wie lange", "多久", "a"], ["bist", "是", "v"], ["du", "你", "s"], ["schon", "已经", "a"],
             ["hier", "这里", "a"]],
    "kasus": [["du", "Nominativ"]],
    "final": [["你", "s"], ["在这里", "a"], ["多久", "a"], ["了？", "x"]],
    "tip": "Wie lange … schon? = ……多久了？（延续至今）。",
},
"Wie lange dauert der Film?": {
    "zh": "这部电影多长？",
    "pat": "疑问词 · 时长",
    "flow": [["Wie lange", "多久", "a"], ["dauert", "持续", "v"], ["der Film", "这部电影", "s"]],
    "kasus": [["der Film", "Nominativ"]],
    "final": [["这部电影", "s"], ["持续", "v"], ["多久", "a"], ["？", "x"]],
    "tip": "dauern = 持续（时长）。",
},
"Wie lange fährt der Zug von Hamburg nach Berlin?": {
    "zh": "火车从汉堡到柏林要多久？",
    "pat": "疑问词 · 时长",
    "flow": [["Wie lange", "多久", "a"], ["fährt", "行驶", "v"], ["der Zug", "火车", "s"],
             ["von Hamburg nach Berlin", "从汉堡到柏林", "a"]],
    "kasus": [["der Zug", "Nominativ"]],
    "final": [["火车", "s"], ["从汉堡到柏林", "a"], ["要", "v"], ["多久", "a"], ["？", "x"]],
    "tip": "von … nach … = 从……到……。",
},
"Wie lange lernen Sie schon Deutsch?": {
    "zh": "您学德语多久了？",
    "pat": "疑问词 · 时长",
    "flow": [["Wie lange", "多久", "a"], ["lernen", "学", "v"], ["Sie", "您", "s"], ["schon", "已经", "a"],
             ["Deutsch", "德语", "o"]],
    "kasus": [["Sie", "Nominativ"], ["Deutsch", "Akkusativ"]],
    "final": [["您", "s"], ["学德语", "v"], ["多久", "a"], ["了？", "x"]],
    "tip": "Wie lange lernen Sie schon Deutsch? = 您学德语多久了？",
},
"Hier ist 06131-553221, Pamela Linke.": {
    "zh": "这里是 06131-553221，我是帕梅拉·林克。",
    "pat": "电话用语 · Hier ist",
    "flow": [["Hier ist", "这里是", "v"], ["06131-553221", "06131-553221", "x"],
             ["Pamela Linke", "帕梅拉·林克", "x"]],
    "final": [["这里是", "v"], ["06131-553221", "x"], ["，", "x"], ["我是", "v"], ["帕梅拉·林克", "x"], ["。", "x"]],
    "tip": "接电话自报：Hier ist + 号码/姓名。",
},
"Hier ist Rauchen verboten.": {
    "zh": "这里禁止吸烟。",
    "pat": "地点前置 · 状态",
    "flow": [["Hier", "这里", "a"], ["ist", "是", "v"], ["Rauchen", "吸烟", "s"], ["verboten", "禁止", "x"]],
    "kasus": [["Rauchen", "Nominativ"]],
    "final": [["这里", "a"], ["禁止", "v"], ["吸烟", "x"], ["。", "x"]],
    "tip": "verboten = 禁止（公告语）。Rauchen 动名词作主语。",
},
"Hier ist der Brief, den du suchst.": {
    "zh": "这是你找的那封信。",
    "pat": "地点前置 · 关系从句",
    "flow": [["Hier", "这里", "a"], ["ist", "是", "v"], ["der Brief", "那封信", "s"],
             ["den du suchst", "你找的", "c"]],
    "kasus": [["der Brief", "Nominativ"], ["den", "Akkusativ"]],
    "final": [["这", "s"], ["是", "v"], ["你找的", "c"], ["那封信", "s"], ["。", "x"]],
    "tip": "den 引导关系从句（指 der Brief，Akkusativ），从句动词在句末。",
},
"Hier ist mein Ausweis.": {
    "zh": "这是我的证件。",
    "pat": "地点前置",
    "flow": [["Hier", "这里", "a"], ["ist", "是", "v"], ["mein Ausweis", "我的证件", "s"]],
    "kasus": [["mein Ausweis", "Nominativ"]],
    "final": [["这", "s"], ["是", "v"], ["我的证件", "x"], ["。", "x"]],
    "tip": "der Ausweis = 证件（护照/身份证）。",
},
"Das macht 5 Euro 95.": {
    "zh": "一共是 5 欧元 95 分。",
    "pat": "普通语序 · 价格",
    "flow": [["Das", "这", "s"], ["macht", "一共是", "v"], ["5 Euro 95", "5 欧元 95 分", "o"]],
    "kasus": [["Das", "Nominativ"]],
    "final": [["一共", "a"], ["是", "v"], ["5 欧元 95 分", "o"], ["。", "x"]],
    "tip": "收银用语：Das macht … = 一共是……。",
},
"Das macht nichts.": {
    "zh": "没关系。",
    "pat": "普通语序 · machen",
    "flow": [["Das", "这", "s"], ["macht", "造成", "v"], ["nichts", "没什么", "o"]],
    "kasus": [["Das", "Nominativ"], ["nichts", "Akkusativ"]],
    "final": [["没", "v"], ["关系", "x"], ["。", "x"]],
    "tip": "Das macht nichts = 没关系（回应道歉）。",
},
"Das macht zusammen 2 Euro 80.": {
    "zh": "一共 2 欧元 80 分。",
    "pat": "普通语序 · 价格",
    "flow": [["Das", "这", "s"], ["macht", "一共是", "v"], ["zusammen", "总共", "a"],
             ["2 Euro 80", "2 欧元 80 分", "o"]],
    "kasus": [["Das", "Nominativ"]],
    "final": [["一共", "a"], ["是", "v"], ["2 欧元 80 分", "o"], ["。", "x"]],
    "tip": "zusammen = 总共。收银常用。",
},
}
