# -*- coding: utf-8 -*-
"""例句拆解（Zergliederung）。参考 FlashCard 的 trans.py，但按德语重做。

主轨是「顺读」：德→中逐块、每块标成分，按德语原序读下去。
德语特色：
  - Satzklammer 句框：情态动词 / 可分动词 / Perfekt 三种情形下，
    变位动词占第二位，动词第二部分被挤到句末——用 klammer 画出这个框。
  - 名词短语标注格（Nominativ / Akkusativ / Dativ），这是中文里没有的范畴。
  - 完整译文按成分着色，让读者看出每段中文来自哪个德语意群。

键 = 官方例句原文（与词表逐字一致，构建期校验）。
字段：
  zh      完整中文翻译
  pat     句型标签
  flow    [德块, 中文块, 成分] —— 按德语原序；拼接回原句由构建期校验
  klammer 可选 [框前, 框左动词, 框中成分, 框右动词第二部分, 类型]
          type ∈ modal(情态) | trennbar(可分) | perfekt(Perfekt)
  kasus   可选 [德语短语, 格]
  final   可选 [中文块, 成分] —— 完整译文；缺省用 zh
  tip     一句话点破

成分代号：s 主语 · v 变位动词 · v2 动词第二部分 · a 状语 · o 宾语 ·
          d 定语 · c 从句 · x 默认
"""
SATZ = {
# ============================================================
# 一、情态动词 Satzklammer（框左 = 情态动词，框右 = 不定式）
# ============================================================

"Ich muss immer um vier Uhr aufstehen.": {
    "zh": "我必须总是四点钟起床。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Ich", "我", "s"], ["muss", "必须", "v"], ["immer", "总是", "a"],
             ["um vier Uhr", "在四点钟", "a"], ["aufstehen", "起床", "v2"]],
    "klammer": ["Ich", "muss", "immer um vier Uhr", "aufstehen", "modal"],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["必须", "v"], ["总是", "a"], ["在四点钟", "a"], ["起床", "v2"], ["。", "x"]],
    "tip": "muss 占第二位，aufstehen 被挤到句末，中间夹住 immer um vier Uhr——这就是句框。",
},
"Ich muss meine Schlüssel abgeben.": {
    "zh": "我必须把钥匙交出去。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Ich", "我", "s"], ["muss", "必须", "v"], ["meine Schlüssel", "我的钥匙", "o"],
             ["abgeben", "交出去", "v2"]],
    "klammer": ["Ich", "muss", "meine Schlüssel", "abgeben", "modal"],
    "kasus": [["Ich", "Nominativ"], ["meine Schlüssel", "Akkusativ"]],
    "final": [["我", "s"], ["必须", "v"], ["把钥匙", "o"], ["交出去", "v2"], ["。", "x"]],
    "tip": "meine Schlüssel 是 Akkusativ（交什么）。abgeben 是可分动词，前缀 ab 随整体在句末。",
},
"Ich muss mich noch anziehen.": {
    "zh": "我还得穿好衣服。",
    "pat": "情态动词 · 反身",
    "flow": [["Ich", "我", "s"], ["muss", "得", "v"], ["mich", "自己", "o"],
             ["noch", "还", "a"], ["anziehen", "穿上衣服", "v2"]],
    "klammer": ["Ich", "muss", "mich noch", "anziehen", "modal"],
    "kasus": [["Ich", "Nominativ"], ["mich", "Akkusativ"]],
    "final": [["我", "s"], ["还得", "v"], ["穿好衣服", "v2"], ["。", "x"]],
    "tip": "sich anziehen 是反身动词，mich 随主语 Ich。anziehen 可分，前缀 an 在句末。",
},
"Ich muss noch für morgen einkaufen.": {
    "zh": "我还得为明天去买东西。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Ich", "我", "s"], ["muss", "得", "v"], ["noch", "还", "a"],
             ["für morgen", "为明天", "a"], ["einkaufen", "去买东西", "v2"]],
    "klammer": ["Ich", "muss", "noch für morgen", "einkaufen", "modal"],
    "final": [["我", "s"], ["还得", "v"], ["为明天", "a"], ["去买东西", "v2"], ["。", "x"]],
    "tip": "für morgen 是目的状语。einkaufen 可分，ein 在句末。",
},
"Ich muss jetzt das Essen machen.": {
    "zh": "我现在得做饭了。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Ich", "我", "s"], ["muss", "得", "v"], ["jetzt", "现在", "a"],
             ["das Essen", "饭", "o"], ["machen", "做", "v2"]],
    "klammer": ["Ich", "muss", "jetzt das Essen", "machen", "modal"],
    "kasus": [["Ich", "Nominativ"], ["das Essen", "Akkusativ"]],
    "final": [["我", "s"], ["现在", "a"], ["得", "v"], ["做饭", "v2"], ["了", "x"]],
    "tip": "das Essen machen = 做饭（das Essen 是 Akkusativ 宾语）。",
},
"Ich muss zum Arzt gehen.": {
    "zh": "我得去看医生。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Ich", "我", "s"], ["muss", "得", "v"], ["zum Arzt", "去看医生", "a"],
             ["gehen", "去", "v2"]],
    "klammer": ["Ich", "muss", "zum Arzt", "gehen", "modal"],
    "kasus": [["Ich", "Nominativ"], ["zum Arzt", "Dativ"]],
    "final": [["我", "s"], ["得", "v"], ["去看医生", "a"], ["。", "x"]],
    "tip": "zum = zu + dem，固定搭配 zum Arzt gehen（去看医生）。",
},
"Können Sie mir helfen?": {
    "zh": "您能帮我吗？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Können", "能", "v"], ["Sie", "您", "s"], ["mir", "我（帮我）", "o"],
             ["helfen", "帮助", "v2"]],
    "klammer": ["Sie", "Können", "mir", "helfen", "modal"],
    "kasus": [["Sie", "Nominativ"], ["mir", "Dativ"]],
    "final": [["您", "s"], ["能", "v"], ["帮我", "o"], ["吗？", "x"]],
    "tip": "疑问句里 Können 提到第一位，helfen 仍在句末。mir 是 Dativ（帮谁）。",
},
"Können Sie mir eine Auskunft geben?": {
    "zh": "您能给我一个答复吗？",
    "pat": "情态动词 · 双宾语",
    "flow": [["Können", "能", "v"], ["Sie", "您", "s"], ["mir", "我（给我）", "o"],
             ["eine Auskunft", "一个答复", "o"], ["geben", "给", "v2"]],
    "kasus": [["Sie", "Nominativ"], ["mir", "Dativ"], ["eine Auskunft", "Akkusativ"]],
    "final": [["您", "s"], ["能", "v"], ["给我", "o"], ["一个答复", "o"], ["吗？", "x"]],
    "tip": "双宾语：mir（Dativ，给谁）+ eine Auskunft（Akkusativ，给什么）。",
},
"Können Sie mir seine Adresse sagen?": {
    "zh": "您能把他的地址告诉我吗？",
    "pat": "情态动词 · 双宾语",
    "flow": [["Können", "能", "v"], ["Sie", "您", "s"], ["mir", "我（告诉我）", "o"],
             ["seine Adresse", "他的地址", "o"], ["sagen", "告诉", "v2"]],
    "kasus": [["Sie", "Nominativ"], ["mir", "Dativ"], ["seine Adresse", "Akkusativ"]],
    "final": [["您", "s"], ["能", "v"], ["把他的地址", "o"], ["告诉我", "o"], ["吗？", "x"]],
    "tip": "sagen + Dativ(给谁) + Akkusativ(内容)。mir 是 Dativ，seine Adresse 是 Akkusativ。",
},
"Können Sie das bitte wiederholen?": {
    "zh": "您能再说一遍吗？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Können", "能", "v"], ["Sie", "您", "s"], ["das", "这个", "o"],
             ["bitte", "请", "a"], ["wiederholen", "重复", "v2"]],
    "kasus": [["Sie", "Nominativ"], ["das", "Akkusativ"]],
    "final": [["您", "s"], ["能", "v"], ["再", "a"], ["说一遍", "v2"], ["吗？", "x"]],
    "tip": "没听清时的救场句：Können Sie das bitte wiederholen?",
},
"Ich möchte gern den Dom besichtigen.": {
    "zh": "我很想参观大教堂。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Ich", "我", "s"], ["möchte", "想", "v"], ["gern", "很乐意", "a"],
             ["den Dom", "大教堂", "o"], ["besichtigen", "参观", "v2"]],
    "klammer": ["Ich", "möchte", "gern den Dom", "besichtigen", "modal"],
    "kasus": [["Ich", "Nominativ"], ["den Dom", "Akkusativ"]],
    "final": [["我", "s"], ["很", "a"], ["想", "v"], ["参观", "v2"], ["大教堂", "o"], ["。", "x"]],
    "tip": "möchte 表委婉愿望。den Dom 是 Akkusativ（der → den）。",
},
"Ich möchte gern diesen Film sehen.": {
    "zh": "我很想看这部电影。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Ich", "我", "s"], ["möchte", "想", "v"], ["gern", "很乐意", "a"],
             ["diesen Film", "这部电影", "o"], ["sehen", "看", "v2"]],
    "klammer": ["Ich", "möchte", "gern diesen Film", "sehen", "modal"],
    "kasus": [["Ich", "Nominativ"], ["diesen Film", "Akkusativ"]],
    "final": [["我", "s"], ["很", "a"], ["想", "v"], ["看", "v2"], ["这部电影", "o"], ["。", "x"]],
    "tip": "diesen Film = dieser + Akkusativ（阳性名词宾语要变 den/diesen）。",
},
"Darf ich ein Foto machen?": {
    "zh": "我可以拍张照吗？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Darf", "可以", "v"], ["ich", "我", "s"], ["ein Foto", "一张照片", "o"],
             ["machen", "拍", "v2"]],
    "klammer": ["ich", "Darf", "ein Foto", "machen", "modal"],
    "kasus": [["ich", "Nominativ"], ["ein Foto", "Akkusativ"]],
    "final": [["我", "s"], ["可以", "v"], ["拍", "v2"], ["一张照片", "o"], ["吗？", "x"]],
    "tip": "ein Foto machen 固定搭配（拍照）。Darf ich…? = 我可以……吗？",
},
"Darf ich Sie zu einem Kaffee einladen?": {
    "zh": "我可以请您喝杯咖啡吗？",
    "pat": "情态动词 · 疑问句 + 可分",
    "flow": [["Darf", "可以", "v"], ["ich", "我", "s"], ["Sie", "您", "o"],
             ["zu einem Kaffee", "去喝杯咖啡", "a"], ["einladen", "邀请", "v2"]],
    "kasus": [["ich", "Nominativ"], ["Sie", "Akkusativ"]],
    "final": [["我", "s"], ["可以", "v"], ["请您", "o"], ["喝杯咖啡", "a"], ["吗？", "x"]],
    "tip": "einladen + Akkusativ(请谁) + zu(做什么)。einladen 可分，ein 在句末。",
},
"Ich kann nicht kommen, denn ich bin krank.": {
    "zh": "我不能来了，因为我病了。",
    "pat": "情态动词 + denn 原因",
    "flow": [["Ich", "我", "s"], ["kann", "能", "v"], ["nicht", "不", "a"],
             ["kommen", "来", "v2"], ["denn ich bin krank", "因为我病了", "c"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["不能", "v"], ["来", "v2"], ["了，", "x"], ["因为我病了", "c"], ["。", "x"]],
    "tip": "denn 连接原因分句，后面保持正常语序。kann nicht = 不能。",
},
"Wir möchten bestellen, bitte.": {
    "zh": "我们要点菜，麻烦您。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Wir", "我们", "s"], ["möchten", "想要", "v"], ["bestellen", "点菜", "v2"],
             ["bitte", "请", "a"]],
    "klammer": ["Wir", "möchten", "bitte", "bestellen", "modal"],
    "final": [["我们", "s"], ["要", "v"], ["点菜", "v2"], ["，", "x"], ["麻烦您", "x"], ["。", "x"]],
    "tip": "餐馆叫服务员：Wir möchten bestellen. = 我们要点菜。",
},
"Hier darf man nicht rauchen.": {
    "zh": "这里不许抽烟。",
    "pat": "情态动词 · 无人称",
    "flow": [["Hier", "这里", "a"], ["darf man", "人们可以", "v"], ["nicht", "不", "a"],
             ["rauchen", "抽烟", "v2"]],
    "kasus": [["man", "Nominativ"]],
    "final": [["这里", "a"], ["不许", "v"], ["抽烟", "v2"], ["。", "x"]],
    "tip": "man darf nicht = 禁止（无人称主语 man + 情态动词）。",
},
"Es darf nicht mehr als 15 Euro kosten.": {
    "zh": "它不能超过 15 欧元。",
    "pat": "情态动词 · 无人称",
    "flow": [["Es", "它", "s"], ["darf", "可以", "v"], ["nicht mehr als 15 Euro", "不超过 15 欧元", "o"],
             ["kosten", "花费", "v2"]],
    "kasus": [["Es", "Nominativ"]],
    "final": [["它", "s"], ["不能", "v"], ["超过", "v2"], ["15 欧元", "o"], ["。", "x"]],
    "tip": "nicht mehr als = 不超过。es 可指任何事物（价格）。",
},
"Wann kann ich Sie anrufen?": {
    "zh": "我什么时候能给您打电话？",
    "pat": "情态动词 · 疑问句 + 可分",
    "flow": [["Wann", "什么时候", "a"], ["kann", "能", "v"], ["ich", "我", "s"],
             ["Sie", "您", "o"], ["anrufen", "打电话", "v2"]],
    "kasus": [["ich", "Nominativ"], ["Sie", "Akkusativ"]],
    "final": [["我", "s"], ["什么时候", "a"], ["能", "v"], ["给您打电话", "v2"], ["？", "x"]],
    "tip": "anrufen = an + rufen（打电话），可分。疑问词 Wann 提前。",
},
"Was möchten Sie trinken?": {
    "zh": "您想喝点什么？",
    "pat": "情态动词 · 疑问句",
    "flow": [["Was", "什么", "o"], ["möchten", "想", "v"], ["Sie", "您", "s"],
             ["trinken", "喝", "v2"]],
    "kasus": [["Sie", "Nominativ"], ["Was", "Akkusativ"]],
    "final": [["您", "s"], ["想", "v"], ["喝点什么", "v2"], ["？", "x"]],
    "tip": "Was + 情态动词 + 主语 + 不定式：您想喝点什么？",
},
"Was soll ich mitbringen?": {
    "zh": "我应该带点什么？",
    "pat": "情态动词 · 疑问句 + 可分",
    "flow": [["Was", "什么", "o"], ["soll", "应该", "v"], ["ich", "我", "s"],
             ["mitbringen", "带来", "v2"]],
    "kasus": [["ich", "Nominativ"], ["Was", "Akkusativ"]],
    "final": [["我", "s"], ["应该", "v"], ["带点什么", "v2"], ["？", "x"]],
    "tip": "mitbringen = mit + bringen（带来），可分。soll 表「应该」。",
},
"Sie können das Geld auch überweisen.": {
    "zh": "您也可以转账。",
    "pat": "情态动词 · Satzklammer",
    "flow": [["Sie", "您", "s"], ["können", "可以", "v"], ["das Geld", "钱", "o"],
             ["auch", "也", "a"], ["überweisen", "转账", "v2"]],
    "kasus": [["Sie", "Nominativ"], ["das Geld", "Akkusativ"]],
    "final": [["您", "s"], ["也", "a"], ["可以", "v"], ["转账", "v2"], ["。", "x"]],
    "tip": "überweisen = 转账（银行场景）。",
},
# ============================================================
# 二、可分动词（框右 = 前缀）
# ============================================================

"Der Unterricht fängt gleich an.": {
    "zh": "课马上就要开始了。",
    "pat": "可分动词 · 前缀在句末",
    "flow": [["Der Unterricht", "课", "s"], ["fängt", "开始", "v"], ["gleich", "马上", "a"],
             ["an", "（前缀）", "v2"]],
    "klammer": ["Der Unterricht", "fängt", "gleich", "an", "trennbar"],
    "kasus": [["Der Unterricht", "Nominativ"]],
    "final": [["课", "s"], ["马上", "a"], ["就要开始了", "v"], ["。", "x"]],
    "tip": "anfangen = an + fangen：变位部分 fängt 在二位，前缀 an 被挤到句末。",
},
"Der Kurs hört in einer Woche auf.": {
    "zh": "课程一周后结束。",
    "pat": "可分动词 · 前缀在句末",
    "flow": [["Der Kurs", "课程", "s"], ["hört", "结束", "v"], ["in einer Woche", "一周后", "a"],
             ["auf", "（前缀）", "v2"]],
    "klammer": ["Der Kurs", "hört", "in einer Woche", "auf", "trennbar"],
    "kasus": [["Der Kurs", "Nominativ"]],
    "final": [["课程", "s"], ["一周后", "a"], ["结束", "v"], ["。", "x"]],
    "tip": "aufhören = auf + hören：前缀 auf 句末。in einer Woche = 一周后。",
},
"Der Zug kommt in fünf Minuten.": {
    "zh": "火车五分钟后到。",
    "pat": "普通语序 · 时间",
    "flow": [["Der Zug", "火车", "s"], ["kommt", "到", "v"], ["in fünf Minuten", "五分钟后", "a"]],
    "kasus": [["Der Zug", "Nominativ"]],
    "final": [["火车", "s"], ["五分钟后", "a"], ["到", "v"], ["。", "x"]],
    "tip": "kommt 是 ankommen 的变位（这里省略了句末前缀 an 的完整框）。in + 时间 = 之后。",
},
"Die Hausfrau/der Hausmann wäscht, kocht und kauft ein.": {
    "zh": "家庭主妇/主夫洗衣服、做饭和买东西。",
    "pat": "并列谓词 + 可分",
    "flow": [["Die Hausfrau/der Hausmann", "家庭主妇/主夫", "s"],
             ["wäscht, kocht", "洗、做饭", "v"], ["und", "和", "x"], ["kauft", "买", "v"],
             ["ein", "（前缀）", "v2"]],
    "kasus": [["Die Hausfrau/der Hausmann", "Nominativ"]],
    "final": [["家庭主妇/主夫", "s"], ["洗衣服、做饭", "v"], ["和", "x"], ["买东西", "v"], ["。", "x"]],
    "tip": "三个并列谓语共用主语。einkaufen 的前缀 ein 只出现一次、在句末。",
},
"Das sieht schön aus.": {
    "zh": "那看起来很美。",
    "pat": "可分动词 · 前缀在句末",
    "flow": [["Das", "那", "s"], ["sieht", "看", "v"], ["schön", "美", "a"], ["aus", "（前缀）", "v2"]],
    "klammer": ["Das", "sieht", "schön", "aus", "trennbar"],
    "kasus": [["Das", "Nominativ"]],
    "final": [["那", "s"], ["看起来", "v"], ["很美", "a"], ["。", "x"]],
    "tip": "aussehen = aus + sehen（看起来）。系动词式用法。",
},
"Wo muss ich aussteigen?": {
    "zh": "我必须在哪儿下车？",
    "pat": "情态动词 · 疑问句 + 可分",
    "flow": [["Wo", "在哪里", "a"], ["muss", "必须", "v"], ["ich", "我", "s"],
             ["aussteigen", "下车", "v2"]],
    "kasus": [["ich", "Nominativ"]],
    "final": [["我", "s"], ["必须", "v"], ["在哪儿", "a"], ["下车", "v2"], ["？", "x"]],
    "tip": "aussteigen = aus + steigen（下车）。Wo muss ich aussteigen? 乘车问法。",
},
# ============================================================
# 三、Perfekt（框右 = 过去分词）
# ============================================================

"Ich habe Ihre E-Mail nicht bekommen.": {
    "zh": "我没有收到您的电子邮件。",
    "pat": "Perfekt · haben + Partizip",
    "flow": [["Ich", "我", "s"], ["habe", "（助动词）", "v"], ["Ihre E-Mail", "您的邮件", "o"],
             ["nicht", "没有", "a"], ["bekommen", "收到", "v2"]],
    "klammer": ["Ich", "habe", "Ihre E-Mail nicht", "bekommen", "perfekt"],
    "kasus": [["Ich", "Nominativ"], ["Ihre E-Mail", "Akkusativ"]],
    "final": [["我", "s"], ["没有", "a"], ["收到", "v2"], ["您的邮件", "o"], ["。", "x"]],
    "tip": "Perfekt 句框：habe 占第二位，Partizip bekommen 在句末。",
},
"Ich habe Ihre Anzeige in der Zeitung gelesen.": {
    "zh": "我在报纸上读了您的广告。",
    "pat": "Perfekt · haben + Partizip",
    "flow": [["Ich", "我", "s"], ["habe", "（助动词）", "v"], ["Ihre Anzeige", "您的广告", "o"],
             ["in der Zeitung", "在报纸上", "a"], ["gelesen", "读", "v2"]],
    "klammer": ["Ich", "habe", "Ihre Anzeige in der Zeitung", "gelesen", "perfekt"],
    "kasus": [["Ich", "Nominativ"], ["Ihre Anzeige", "Akkusativ"], ["der Zeitung", "Dativ"]],
    "final": [["我", "s"], ["在报纸上", "a"], ["读了", "v2"], ["您的广告", "o"], ["。", "x"]],
    "tip": "lesen → gelesen（强变化）。in der Zeitung：位置用 Dativ。",
},
"Ich habe die Durchsage nicht verstanden.": {
    "zh": "我没听懂广播。",
    "pat": "Perfekt · haben + Partizip",
    "flow": [["Ich", "我", "s"], ["habe", "（助动词）", "v"], ["die Durchsage", "广播", "o"],
             ["nicht", "没有", "a"], ["verstanden", "听懂", "v2"]],
    "klammer": ["Ich", "habe", "die Durchsage nicht", "verstanden", "perfekt"],
    "kasus": [["Ich", "Nominativ"], ["die Durchsage", "Akkusativ"]],
    "final": [["我", "s"], ["没有", "a"], ["听懂", "v2"], ["广播", "o"], ["。", "x"]],
    "tip": "verstehen → verstanden。nicht 在宾语后、Partizip 前。",
},
"Ich bin in Zagreb geboren.": {
    "zh": "我出生在萨格勒布。",
    "pat": "Perfekt · sein + Partizip",
    "flow": [["Ich", "我", "s"], ["bin", "（助动词）", "v"], ["in Zagreb", "在萨格勒布", "a"],
             ["geboren", "出生", "v2"]],
    "klammer": ["Ich", "bin", "in Zagreb", "geboren", "perfekt"],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["出生", "v2"], ["在萨格勒布", "a"], ["。", "x"]],
    "tip": "geboren 表状态，用 sein（不是 haben）。问出生地说 Wo sind Sie geboren?",
},
"Wann sind Sie geboren?": {
    "zh": "您是什么时候出生的？",
    "pat": "Perfekt · 疑问句",
    "flow": [["Wann", "什么时候", "a"], ["sind", "（助动词）", "v"], ["Sie", "您", "s"],
             ["geboren", "出生", "v2"]],
    "kasus": [["Sie", "Nominativ"]],
    "final": [["您", "s"], ["是", "v"], ["什么时候", "a"], ["出生的", "v2"], ["？", "x"]],
    "tip": "疑问词 Wann 提前，sind 第二位，主语 Sie 第三位。",
},
"Meine Frau ist gestern gestorben.": {
    "zh": "我妻子昨天去世了。",
    "pat": "Perfekt · sein + Partizip",
    "flow": [["Meine Frau", "我的妻子", "s"], ["ist", "（助动词）", "v"], ["gestern", "昨天", "a"],
             ["gestorben", "去世", "v2"]],
    "klammer": ["Meine Frau", "ist", "gestern", "gestorben", "perfekt"],
    "kasus": [["Meine Frau", "Nominativ"]],
    "final": [["我的妻子", "s"], ["昨天", "a"], ["去世了", "v2"], ["。", "x"]],
    "tip": "sterben → gestorben。状态变化类动词用 sein。",
},
"Wir haben ein Apartment gemietet.": {
    "zh": "我们租了一个公寓。",
    "pat": "Perfekt · haben + Partizip",
    "flow": [["Wir", "我们", "s"], ["haben", "（助动词）", "v"], ["ein Apartment", "一个公寓", "o"],
             ["gemietet", "租", "v2"]],
    "klammer": ["Wir", "haben", "ein Apartment", "gemietet", "perfekt"],
    "kasus": [["Wir", "Nominativ"], ["ein Apartment", "Akkusativ"]],
    "final": [["我们", "s"], ["租了", "v2"], ["一个公寓", "o"], ["。", "x"]],
    "tip": "mieten → gemietet（规则变化）。",
},
"Haben Sie meinen Brief bekommen?": {
    "zh": "您收到我的信了吗？",
    "pat": "Perfekt · 疑问句",
    "flow": [["Haben", "（助动词）", "v"], ["Sie", "您", "s"], ["meinen Brief", "我的信", "o"],
             ["bekommen", "收到", "v2"]],
    "kasus": [["Sie", "Nominativ"], ["meinen Brief", "Akkusativ"]],
    "final": [["您", "s"], ["收到", "v2"], ["我的信", "o"], ["了吗？", "x"]],
    "tip": "Perfekt 疑问句：助动词提到第一位。",
},
# ============================================================
# 四、Das ist 判断句（表语与主语同格）
# ============================================================

"Das ist Frau Becker.": {
    "zh": "这是贝克尔女士。",
    "pat": "判断句 · Das ist",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["Frau Becker", "贝克尔女士", "x"]],
    "final": [["这", "s"], ["是", "v"], ["贝克尔女士", "x"], ["。", "x"]],
    "tip": "介绍人：Das ist + 名字。Frau = 女士（Herr = 先生）。",
},
"Das ist meine Freundin.": {
    "zh": "这是我的女朋友。",
    "pat": "判断句 · Das ist",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["meine Freundin", "我的女朋友", "x"]],
    "kasus": [["meine Freundin", "Nominativ"]],
    "final": [["这", "s"], ["是", "v"], ["我的女朋友", "x"], ["。", "x"]],
    "tip": "表语与主语同格（Nominativ）。meine Freundin = 我的女朋友。",
},
"Das ist ein Freund von mir.": {
    "zh": "这是我的一个朋友。",
    "pat": "判断句 · 介词定语",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["ein Freund", "一个朋友", "x"],
             ["von mir", "我的", "d"]],
    "kasus": [["ein Freund", "Nominativ"], ["mir", "Dativ"]],
    "final": [["这", "s"], ["是", "v"], ["我的一个朋友", "x"], ["。", "x"]],
    "tip": "ein Freund von mir = 我的一个朋友（von + Dativ 表所属）。",
},
"Das ist alles.": {
    "zh": "这就是全部了。",
    "pat": "判断句 · Das ist",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["alles", "全部", "x"]],
    "final": [["这", "s"], ["就是全部", "x"], ["了", "x"], ["。", "x"]],
    "tip": "alles = 一切/全部。购物/收尾时说 Das ist alles = 就这些了。",
},
"Das ist für Sie.": {
    "zh": "这是给您的。",
    "pat": "判断句 · 介词短语",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["für Sie", "给您的", "x"]],
    "kasus": [["Sie", "Akkusativ"]],
    "final": [["这", "s"], ["是", "v"], ["给您的", "x"], ["。", "x"]],
    "tip": "für + Akkusativ（给谁）。",
},
"Das ist der Schlüssel für die Haustür.": {
    "zh": "这是大门的钥匙。",
    "pat": "判断句 · 介词定语",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["der Schlüssel", "钥匙", "x"],
             ["für die Haustür", "大门（的）", "d"]],
    "kasus": [["der Schlüssel", "Nominativ"], ["die Haustür", "Akkusativ"]],
    "final": [["这", "s"], ["是", "v"], ["大门", "d"], ["的钥匙", "x"], ["。", "x"]],
    "tip": "für 短语作后置定语（门用的钥匙），中文提到名词前。",
},
"Das ist mir zu teuer.": {
    "zh": "这对我来说太贵了。",
    "pat": "判断句 · zu 太",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["mir", "对我", "a"], ["zu teuer", "太贵", "x"]],
    "kasus": [["mir", "Dativ"]],
    "final": [["这", "s"], ["对我", "a"], ["来说太贵了", "x"], ["。", "x"]],
    "tip": "zu + 形容词 = 太……。mir 是 Dativ（对我来说），购物拒绝理由。",
},
"Das ist in Ordnung.": {
    "zh": "没关系/可以。",
    "pat": "判断句 · 固定搭配",
    "flow": [["Das", "这", "s"], ["ist", "是", "v"], ["in Ordnung", "可以的", "x"]],
    "final": [["这", "s"], ["可以", "x"], ["。", "x"]],
    "tip": "in Ordnung = 没问题/可以。回应请求或道歉。",
},
# ============================================================
# 五、系动词 ich bin / wir sind（表语形容词或名词）
# ============================================================

"Ich bin Studentin.": {
    "zh": "我是大学生。",
    "pat": "系动词 · 表语名词",
    "flow": [["Ich", "我", "s"], ["bin", "是", "v"], ["Studentin", "女大学生", "x"]],
    "kasus": [["Ich", "Nominativ"], ["Studentin", "Nominativ"]],
    "final": [["我", "s"], ["是", "v"], ["大学生", "x"], ["。", "x"]],
    "tip": "表职业/身份的名词通常不加冠词。Student 的阴性是 Studentin。",
},
"Ich bin verheiratet und habe drei Kinder.": {
    "zh": "我结婚了，有三个孩子。",
    "pat": "并列句 · 系动词 + haben",
    "flow": [["Ich", "我", "s"], ["bin", "是", "v"], ["verheiratet", "已婚", "x"],
             ["und habe drei Kinder", "并且有三个孩子", "c"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["结婚了", "v"], ["，", "x"], ["有三个孩子", "c"], ["。", "x"]],
    "tip": "und 连接两个分句，第二个保留主谓宾语序。verheiratet 表状态。",
},
"Ich bin zu Hause.": {
    "zh": "我在家。",
    "pat": "系动词 · 处所",
    "flow": [["Ich", "我", "s"], ["bin", "在", "v"], ["zu Hause", "在家", "a"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["在家", "v"], ["。", "x"]],
    "tip": "zu Hause = 在家（固定搭配，注意 H 大写）。",
},
"Ich bin in einer Stunde zurück.": {
    "zh": "我一小时后回来。",
    "pat": "系动词 · 时间",
    "flow": [["Ich", "我", "s"], ["bin", "（回）", "v"], ["in einer Stunde", "一小时后", "a"],
             ["zurück", "回来", "a"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["一小时后", "a"], ["回来", "v"], ["。", "x"]],
    "tip": "in + 时间 = 之后（一小时后）。zurück = 回来。",
},
"Meine Frau ist so groß wie ich.": {
    "zh": "我妻子和我一样高。",
    "pat": "系动词 · 同级比较",
    "flow": [["Meine Frau", "我的妻子", "s"], ["ist", "是", "v"], ["so groß", "一样高", "x"],
             ["wie ich", "和我", "a"]],
    "kasus": [["Meine Frau", "Nominativ"]],
    "final": [["我的妻子", "s"], ["和我", "a"], ["一样高", "x"], ["。", "x"]],
    "tip": "so … wie = 和……一样（同级比较）。",
},
"Ich bin in Zagreb geboren.": {
    "zh": "我出生在萨格勒布。",
    "pat": "系动词 · 状态",
    "flow": [["Ich", "我", "s"], ["bin", "（状态）", "v"], ["in Zagreb", "在萨格勒布", "a"],
             ["geboren", "出生", "x"]],
    "kasus": [["Ich", "Nominativ"]],
    "final": [["我", "s"], ["出生", "v"], ["在萨格勒布", "a"], ["。", "x"]],
    "tip": "geboren（born）作表语状态。问：Wo sind Sie geboren?",
},
# ============================================================
# 六、haben + Akkusativ（最基础句式）
# ============================================================

"Ich habe eine Frage.": {
    "zh": "我有一个问题。",
    "pat": "haben + Akkusativ",
    "flow": [["Ich", "我", "s"], ["habe", "有", "v"], ["eine Frage", "一个问题", "o"]],
    "kasus": [["Ich", "Nominativ"], ["eine Frage", "Akkusativ"]],
    "final": [["我", "s"], ["有", "v"], ["一个问题", "o"], ["。", "x"]],
    "tip": "Ich habe eine Frage = 我想问个问题（课堂/会话开场）。",
},
"Hast du einen Bleistift?": {
    "zh": "你有一支铅笔吗？",
    "pat": "haben · 疑问句",
    "flow": [["Hast", "有", "v"], ["du", "你", "s"], ["einen Bleistift", "一支铅笔", "o"]],
    "kasus": [["du", "Nominativ"], ["einen Bleistift", "Akkusativ"]],
    "final": [["你", "s"], ["有", "v"], ["一支铅笔", "o"], ["吗？", "x"]],
    "tip": "ein → einen：阳性名词的 Akkusativ，A1 必考变化。",
},
"Hast du es eilig?": {
    "zh": "你赶时间吗？",
    "pat": "haben + 固定搭配",
    "flow": [["Hast", "有", "v"], ["du", "你", "s"], ["es eilig", "赶时间", "x"]],
    "kasus": [["du", "Nominativ"]],
    "final": [["你", "s"], ["赶时间", "v"], ["吗？", "x"]],
    "tip": "es eilig haben = 赶时间（固定搭配，es 是形式宾语）。",
},
"Ich habe heute keine Zeit.": {
    "zh": "我今天没有时间。",
    "pat": "haben + kein",
    "flow": [["Ich", "我", "s"], ["habe", "有", "v"], ["heute", "今天", "a"],
             ["keine Zeit", "没有时间", "o"]],
    "kasus": [["Ich", "Nominativ"], ["keine Zeit", "Akkusativ"]],
    "final": [["我", "s"], ["今天", "a"], ["没有", "v"], ["时间", "o"], ["。", "x"]],
    "tip": "keine Zeit = 没有时间。nicht 否定动词、kein 否定名词。",
},
"Hast du schon eine Fahrkarte?": {
    "zh": "你已经买票了吗？",
    "pat": "haben · 疑问句",
    "flow": [["Hast", "有", "v"], ["du", "你", "s"], ["schon", "已经", "a"],
             ["eine Fahrkarte", "一张车票", "o"]],
    "kasus": [["du", "Nominativ"], ["eine Fahrkarte", "Akkusativ"]],
    "final": [["你", "s"], ["已经", "a"], ["买票", "o"], ["了吗？", "x"]],
    "tip": "schon = 已经。乘车场景。",
},
# ============================================================
# 七、疑问句（疑问词 / 动词提前）
# ============================================================

"Wie heißt das auf Deutsch?": {
    "zh": "这个用德语怎么说？",
    "pat": "疑问词 · 怎么",
    "flow": [["Wie", "怎么", "a"], ["heißt", "说", "v"], ["das", "这个", "s"],
             ["auf Deutsch", "用德语", "a"]],
    "kasus": [["das", "Nominativ"]],
    "final": [["这个", "s"], ["用德语", "a"], ["怎么说", "v"], ["？", "x"]],
    "tip": "疑问词 Wie 占一位，动词第二位，主语第三位。auf Deutsch = 用德语。",
},
"Wie heißen Sie, bitte?": {
    "zh": "请问您贵姓？",
    "pat": "疑问词 · 怎么",
    "flow": [["Wie", "怎么", "a"], ["heißen", "叫", "v"], ["Sie", "您", "s"], ["bitte", "请", "a"]],
    "kasus": [["Sie", "Nominativ"]],
    "final": [["您", "s"], ["贵姓", "v"], ["？", "x"]],
    "tip": "heißen = 被叫作。回答：Ich heiße …。",
},
"Wie alt sind Sie?": {
    "zh": "您多大年纪？",
    "pat": "疑问词 · 年龄",
    "flow": [["Wie alt", "多大", "a"], ["sind", "是", "v"], ["Sie", "您", "s"]],
    "kasus": [["Sie", "Nominativ"]],
    "final": [["您", "s"], ["多大", "a"], ["年纪", "x"], ["？", "x"]],
    "tip": "Wie alt bist du? = 你几岁？回答：Ich bin 20 Jahre alt. 或 Ich bin dreiundzwanzig.",
},
"Woher kommen Sie? – Aus Frankreich.": {
    "zh": "您从哪里来？——来自法国。",
    "pat": "疑问词 · 来源",
    "flow": [["Woher", "从哪里", "a"], ["kommen", "来", "v"], ["Sie", "您", "s"],
             ["Aus Frankreich", "来自法国", "a"]],
    "kasus": [["Sie", "Nominativ"]],
    "final": [["您", "s"], ["从哪里", "a"], ["来", "v"], ["？", "x"], ["来自法国", "x"]],
    "tip": "Woher kommen Sie? = 您来自哪里？回答：Ich komme aus …（aus + 国名）。",
},
"Was ist das?": {
    "zh": "那是什么？",
    "pat": "疑问词 · 什么",
    "flow": [["Was", "什么", "s"], ["ist", "是", "v"], ["das", "那", "s"]],
    "final": [["那", "s"], ["是", "v"], ["什么", "s"], ["？", "x"]],
    "tip": "A1 第一课就会学到的问法。",
},
"Was ist Ihr Beruf?": {
    "zh": "您的职业是什么？",
    "pat": "疑问词 · 什么",
    "flow": [["Was", "什么", "s"], ["ist", "是", "v"], ["Ihr Beruf", "您的职业", "s"]],
    "kasus": [["Ihr Beruf", "Nominativ"]],
    "final": [["您的职业", "s"], ["是什么", "v"], ["？", "x"]],
    "tip": "询问职业。回答：Ich bin Lehrer. / Ich bin von Beruf …",
},
"Wie viel kostet das? – 10 Euro.": {
    "zh": "这个多少钱？——10 欧元。",
    "pat": "疑问词 · 价格",
    "flow": [["Wie viel", "多少", "a"], ["kostet", "花费", "v"], ["das", "这个", "s"],
             ["10 Euro", "10 欧元", "x"]],
    "kasus": [["das", "Nominativ"]],
    "final": [["这个", "s"], ["多少钱", "v"], ["？", "x"], ["10 欧元", "x"]],
    "tip": "kosten = 花费。Wie viel kostet …? 购物必问句。",
},
"Wo ist der Ausgang?": {
    "zh": "出口在哪里？",
    "pat": "疑问词 · 哪里",
    "flow": [["Wo", "在哪里", "a"], ["ist", "是", "v"], ["der Ausgang", "出口", "s"]],
    "kasus": [["der Ausgang", "Nominativ"]],
    "final": [["出口", "s"], ["在哪里", "a"], ["？", "x"]],
    "tip": "Wo ist …? 找地方的基本问法。",
},
"Wohin fährt dieser Bus?": {
    "zh": "这辆公交车开往哪里？",
    "pat": "疑问词 · 方向",
    "flow": [["Wohin", "往哪里", "a"], ["fährt", "开", "v"], ["dieser Bus", "这辆公交车", "s"]],
    "kasus": [["dieser Bus", "Nominativ"]],
    "final": [["这辆公交车", "s"], ["开往", "v"], ["哪里", "a"], ["？", "x"]],
    "tip": "Wohin 问方向（去向），Wo 问位置（静止）。",
},
"Wann kommst du zurück?": {
    "zh": "你什么时候回来？",
    "pat": "疑问词 · 时间",
    "flow": [["Wann", "什么时候", "a"], ["kommst", "来", "v"], ["du", "你", "s"],
             ["zurück", "回来", "v2"]],
    "kasus": [["du", "Nominativ"]],
    "final": [["你", "s"], ["什么时候", "a"], ["回来", "v"], ["？", "x"]],
    "tip": "zurückkommen 可分，zurück 在句末。kommst 是 du 的变位。",
},
# ============================================================
# 八、祈使句
# ============================================================

"Bitte schreiben Sie Ihren Geburtsort auf das Formular.": {
    "zh": "请把您的出生地写在表格上。",
    "pat": "祈使句 · 可分",
    "flow": [["Bitte", "请", "a"], ["schreiben Sie", "您写", "v"], ["Ihren Geburtsort", "您的出生地", "o"],
             ["auf das Formular", "在表格上", "a"]],
    "kasus": [["Sie", "Nominativ"], ["Ihren Geburtsort", "Akkusativ"]],
    "final": [["请", "a"], ["把您的出生地", "o"], ["写在表格上", "v"], ["。", "x"]],
    "tip": "aufschreiben 可分，这里 auf 在句末作介词短语的一部分。填表场景。",
},
"Gehen Sie immer geradeaus!": {
    "zh": "您一直往前走！",
    "pat": "祈使句",
    "flow": [["Gehen Sie", "您走", "v"], ["immer", "一直", "a"], ["geradeaus", "直", "a"]],
    "kasus": [["Sie", "Nominativ"]],
    "final": [["您", "s"], ["一直", "a"], ["往前走", "v"], ["！", "x"]],
    "tip": "指路用语：geradeaus = 直行。",
},
"Bitte nehmen Sie Platz!": {
    "zh": "请坐！",
    "pat": "祈使句",
    "flow": [["Bitte", "请", "a"], ["nehmen Sie", "您请", "v"], ["Platz", "座位", "o"]],
    "kasus": [["Sie", "Nominativ"], ["Platz", "Akkusativ"]],
    "final": [["请", "a"], ["坐", "v"], ["！", "x"]],
    "tip": "Platz nehmen = 就座（固定搭配）。",
},
"Bitte, schließen Sie die Tür.": {
    "zh": "请关门。",
    "pat": "祈使句",
    "flow": [["Bitte", "请", "a"], ["schließen Sie", "您关", "v"], ["die Tür", "门", "o"]],
    "kasus": [["Sie", "Nominativ"], ["die Tür", "Akkusativ"]],
    "final": [["请", "a"], ["关", "v"], ["门", "o"], ["。", "x"]],
    "tip": "schließen + Akkusativ（关……）。反义 aufmachen（打开）。",
},
# ============================================================
# 九、普通语序（主 + 谓 + 宾/状）
# ============================================================

"Wir haben eine neue Wohnung.": {
    "zh": "我们有一套新房子。",
    "pat": "普通语序 · haben",
    "flow": [["Wir", "我们", "s"], ["haben", "有", "v"], ["eine neue Wohnung", "一套新房子", "o"]],
    "kasus": [["Wir", "Nominativ"], ["eine neue Wohnung", "Akkusativ"]],
    "final": [["我们", "s"], ["有", "v"], ["一套新房子", "o"], ["。", "x"]],
    "tip": "eine neue Wohnung：形容词按阴性变化（neue）。",
},
"Die Wohnung hat drei Zimmer.": {
    "zh": "这套房子有三个房间。",
    "pat": "普通语序 · haben",
    "flow": [["Die Wohnung", "房子", "s"], ["hat", "有", "v"], ["drei Zimmer", "三个房间", "o"]],
    "kasus": [["Die Wohnung", "Nominativ"], ["drei Zimmer", "Akkusativ"]],
    "final": [["房子", "s"], ["有", "v"], ["三个房间", "o"], ["。", "x"]],
    "tip": "das Zimmer 单复同形。",
},
"Meine Familie lebt in Spanien.": {
    "zh": "我的家人住在西班牙。",
    "pat": "普通语序 · 处所",
    "flow": [["Meine Familie", "我的家人", "s"], ["lebt", "住", "v"], ["in Spanien", "在西班牙", "a"]],
    "kasus": [["Meine Familie", "Nominativ"]],
    "final": [["我的家人", "s"], ["住在", "v"], ["西班牙", "a"], ["。", "x"]],
    "tip": "in + 国名（不带冠词）= 在……。",
},
"Mein Bruder sucht Arbeit.": {
    "zh": "我哥哥在找工作。",
    "pat": "普通语序 · 宾语",
    "flow": [["Mein Bruder", "我哥哥", "s"], ["sucht", "找", "v"], ["Arbeit", "工作", "o"]],
    "kasus": [["Mein Bruder", "Nominativ"], ["Arbeit", "Akkusativ"]],
    "final": [["我哥哥", "s"], ["在找工作", "v"], ["。", "x"]],
    "tip": "Arbeit suchen = 找工作（求职场景）。",
},
"Die Kinder spielen draußen.": {
    "zh": "孩子们在外面玩。",
    "pat": "普通语序 · 处所",
    "flow": [["Die Kinder", "孩子们", "s"], ["spielen", "玩", "v"], ["draußen", "外面", "a"]],
    "kasus": [["Die Kinder", "Nominativ"]],
    "final": [["孩子们", "s"], ["在外面", "a"], ["玩", "v"], ["。", "x"]],
    "tip": "draußen = 在外面（反义 drinnen 在里面）。",
},
"Die Sonne scheint.": {
    "zh": "阳光明媚。",
    "pat": "普通语序",
    "flow": [["Die Sonne", "太阳", "s"], ["scheint", "照耀", "v"]],
    "kasus": [["Die Sonne", "Nominativ"]],
    "final": [["阳光", "s"], ["明媚", "v"], ["。", "x"]],
    "tip": "scheinen = 照耀。天气表达。",
},
"Das Essen schmeckt wunderbar.": {
    "zh": "饭菜味道好极了。",
    "pat": "感官系动词",
    "flow": [["Das Essen", "饭菜", "s"], ["schmeckt", "尝起来", "v"], ["wunderbar", "好极了", "x"]],
    "kasus": [["Das Essen", "Nominativ"]],
    "final": [["饭菜", "s"], ["味道好极了", "v"], ["。", "x"]],
    "tip": "schmecken + 形容词 = 尝起来……。wunderbar = 妙极了。",
},
"Der Kaffee schmeckt bitter.": {
    "zh": "咖啡尝起来苦。",
    "pat": "感官系动词",
    "flow": [["Der Kaffee", "咖啡", "s"], ["schmeckt", "尝起来", "v"], ["bitter", "苦", "x"]],
    "kasus": [["Der Kaffee", "Nominativ"]],
    "final": [["咖啡", "s"], ["尝起来", "v"], ["苦", "x"], ["。", "x"]],
    "tip": "schmecken + 形容词。bitter = 苦。",
},
"Die Farbe gefällt mir gut.": {
    "zh": "我很喜欢这个颜色。",
    "pat": "gefallen + Dativ",
    "flow": [["Die Farbe", "颜色", "s"], ["gefällt", "使喜欢", "v"], ["mir", "我", "o"], ["gut", "很", "a"]],
    "kasus": [["Die Farbe", "Nominativ"], ["mir", "Dativ"]],
    "final": [["我很喜欢", "v"], ["这个颜色", "s"], ["。", "x"]],
    "tip": "gefallen + Dativ：使（人）喜欢。主语是颜色，mir 是 Dativ。",
},
"Der Bus fährt zum Bahnhof.": {
    "zh": "这辆公交车开往火车站。",
    "pat": "普通语序 · 方向",
    "flow": [["Der Bus", "公交车", "s"], ["fährt", "开", "v"], ["zum Bahnhof", "去火车站", "a"]],
    "kasus": [["Der Bus", "Nominativ"]],
    "final": [["公交车", "s"], ["开往", "v"], ["火车站", "a"], ["。", "x"]],
    "tip": "zum = zu + dem（方向）。",
},
"Ich habe eine neue Stelle.": {
    "zh": "我有一份新工作。",
    "pat": "普通语序 · haben",
    "flow": [["Ich", "我", "s"], ["habe", "有", "v"], ["eine neue Stelle", "一份新工作", "o"]],
    "kasus": [["Ich", "Nominativ"], ["eine neue Stelle", "Akkusativ"]],
    "final": [["我", "s"], ["有", "v"], ["一份新工作", "o"], ["。", "x"]],
    "tip": "die Stelle = 职位/工作。求职场景。",
},
}
